### ISSUE TITLE
SSL negotiation failed on mail configuration

### ISSUE THREAD

**Issue by germanp** [osTicket/osTicket#1132]
I get this error when I try to configure the mail settings.

![osticket](https://cloud.githubusercontent.com/assets/1280122/3756559/903afb8e-182f-11e4-9894-dc7ed3193af4.png)

**Comment by Tanklionhearted** [comment]
Same problem.  I connected to the email I want to fetch from, using outlook successfully.  But I keep getting the above error when using OSTicket.

**Comment by davidboliveira** [comment]
Hello,
any ideas to solve this problem?

**Comment by JediKev** [comment]
@mariamghalleb 

You have PHP's openssl extension installed on your server, correct? Also, is port `143` open on your server?

Cheers.

**Comment by mariamghalleb** [comment]
@JediKev yes openssl is enabled. 

how to check if the port is opened ? thank you

**Comment by mariamghalleb** [comment]
My solution was: 
To put the server's url in the hostname (instad of mail.xxxx.com i did S1.xxxx.com) witth IMAP+SSL and 993 as the port number.

**Comment by newronas1** [comment]
I do not understand. The Ubuntu host file? My POP configuration is mail.dominio.com.ar only POP to port 110. Is not OST compatible with fetching emails by POP?
The error is:
TLS/SSL failure for mail.dominio.com.ar: SSL negotiation failed

**Comment by ntozier** [comment]
@newronas1 The error that you are getting says that the SSL/TLS negotiation failed.  Why did it fail?  Aren't sure.  Since you haven't told us what version of osTicket you are running, or anything else about your setup, or your configuration settings there isn't really much anyone here can do to help you.  This thread appears to be about IMAP and you are not using IMAP.

You might want to check your mail server logs to see if there is an error logged there and see if it helps clarify what your issue is.  

On a side note port 110 is not POP3's SSL/TLS port.  Port 995 is usually POP3 SSL/TLS.  So unless your mail server is configured to use SSL/TLS on a the standard unencrypted port that might be your problem.  

Either way this seems to me a question about how to configure osTicket and not bug report.

**Comment by newronas1** [comment]
Hi ntozier

Thanks for your answer. The information is:

Versión osTicket v1.10.4 (035fd0a)
Software de Servidor Web Apache/2.4.29 (Ubuntu)
Versión MySQL 5.7.25
Versión PHP 7.0.33-5+ubuntu18.04.1+deb.sury.org+1

I not want to use IMAP. I want to use POP without security, port 110.

My server does not support security, for this reason I want to configure it using POP110. But I have that error that I attached an image.

[cid:image001.png@01D4E64D.13654060]

It seems that if or if you are looking for emails safely, can I disable this option?

Thanks

NR

De: ntozier <notifications@github.com>
Enviado el: jueves, 28 de marzo de 2019 23:30
Para: osTicket/osTicket <osTicket@noreply.github.com>
CC: Julian Talin <julian.talin@vaix.com>; Mention <mention@noreply.github.com>
Asunto: Re: [osTicket/osTicket] SSL negotiation failed on mail configuration (#1132)


@newronas1<https://github.com/newronas1> The error that you are getting says that the SSL/TLS negotiation failed. Why did it fail? Aren't sure. Since you haven't told us what version of osTicket you are running, or anything else about your setup, or your configuration settings there isn't really much anyone here can do to help you. This thread appears to be about IMAP and you are not using IMAP.

You might want to check your mail server logs to see if there is an error logged there and see if it helps clarify what your issue is.

On a side note port 110 is not POP3's SSL/TLS port. Port 995 is usually POP3 SSL/TLS. So unless your mail server is configured to use SSL/TLS on a the standard unencrypted port that might be your problem.

Either way this seems to me a question about how to configure osTicket and not bug report.

**Comment by newronas1** [comment]
Hi, any idea?
Suggestion?

I think it may be forcing if or if ssl, and my mail server does not support. can i force some change in php files?

Thanks,

J

De: Julian Talin
Enviado el: viernes, 29 de marzo de 2019 4:33 p. m.
Para: osTicket/osTicket <reply@reply.github.com>; osTicket/osTicket <osTicket@noreply.github.com>
CC: Mention <mention@noreply.github.com>
Asunto: RE: [osTicket/osTicket] SSL negotiation failed on mail configuration (#1132)

Hi ntozier

Thanks for your answer. The information is:

Versión osTicket v1.10.4 (035fd0a)
Software de Servidor Web Apache/2.4.29 (Ubuntu)
Versión MySQL 5.7.25
Versión PHP 7.0.33-5+ubuntu18.04.1+deb.sury.org+1

I not want to use IMAP. I want to use POP without security, port 110.

My server does not support security, for this reason I want to configure it using POP110. But I have that error that I attached an image.

[cid:image001.png@01D4E8A9.C3E02230]

It seems that if or if you are looking for emails safely, can I disable this option?

Thanks

NR

De: ntozier <notifications@github.com<mailto:notifications@github.com>>
Enviado el: jueves, 28 de marzo de 2019 23:30
Para: osTicket/osTicket <osTicket@noreply.github.com<mailto:osTicket@noreply.github.com>>
CC: Julian Talin <julian.talin@vaix.com<mailto:julian.talin@vaix.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Asunto: Re: [osTicket/osTicket] SSL negotiation failed on mail configuration (#1132)


@newronas1<https://github.com/newronas1> The error that you are getting says that the SSL/TLS negotiation failed. Why did it fail? Aren't sure. Since you haven't told us what version of osTicket you are running, or anything else about your setup, or your configuration settings there isn't really much anyone here can do to help you. This thread appears to be about IMAP and you are not using IMAP.

You might want to check your mail server logs to see if there is an error logged there and see if it helps clarify what your issue is.

On a side note port 110 is not POP3's SSL/TLS port. Port 995 is usually POP3 SSL/TLS. So unless your mail server is configured to use SSL/TLS on a the standard unencrypted port that might be your problem.

Either way this seems to me a question about how to configure osTicket and not bug report.

**Comment by germanp** [comment]
This is a very old thread, I can barely remember howto made to work, but I think I tried again some time later and it worked. Be sure to enable imap support in google and also there is something they call "less secure apps" (please google it). 

Btw, maybe it is time to close the issue and create a new one.
