### ISSUE TITLE
"Access denied" error when closing a ticket created by myself

### ISSUE THREAD

**Issue by cmalbertschw** [osTicket/osTicket#1187]
**Problem**
I am an administrator at my osticket installation. I created a ticket and then assigned myself to it. Later, I closed that ticket. The problem is that I don't have access to it anymore, even though I am an administrator, created it and even closed it myself. Before closing I transfered the ticket to another department. 

Now, when I try to open the ticket directly, I get a "Access denied. Contact admin if you believe this is an error" message. 

Interesting is that the search bar suggests the ticket when I search for it: 

![image](https://cloud.githubusercontent.com/assets/3584201/4056525/2b79d092-2dbc-11e4-97f6-b02ef5a0db34.png)

But once I click on it I get: "There are no tickets here. (Leave a little early today)."

 Others can access the ticket without problems, but for some mysterious reason I can't. It appears that the permission check has a little glitch.

**Comment by artyPD** [comment]
> Maybe it should, because what about the following workflow?:
> 
> 1. User working for the marketing department creates a ticket
> 2. Somebody transfers it to the IT department and then the same person assigns it to a person in the IT department
> 3. The person the ticket is assigned to closes the ticket.
> 4. Now the ticket creator does not have any access to the ticket because he/she simply doesn't work in the IT department of the company and thus is not in a group that has access to the corresponding department in osticket.
> 
> Adding the user who is working in the marketing department to the IT department is not feasible.
> 
> What do you think?

I am still having this issue in v1.18.

We have cases where Department A needs to create tickets for Department B. However, when Dept A does this then they get an 'Access Denied' because they do no belong to Dept B. They still need to follow the ticket they created for Dept B.

Giving Dept A extended access to Dept B reveals **all** tickets under Dept B to Dept A which is a risk since we don't want confidential information spreading between departments. Dept B has tickets with confidential information that Dept A should not see. Dept A need only see the tickets they created for Dept B.

I am stumped.
