### ISSUE TITLE
Double new-lines when posting a reply throws a 406 error

### ISSUE THREAD

**Issue by Wykleph** [osTicket/osTicket#1355]
Here is what the error page looks like:

> # Not Acceptable
> 
> An appropriate representation of the requested resource /scp/tickets.php could not be found on this server.
> 
> Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

I have figured out how to reproduce this error.

If I use the "Post Reply" tab and there is a blank line between chunks of text(2 new-line chars?), it will produce that page.

Using the same text that throws an error while using the "Post Reply" tab will not throw an error if I use the "Post Internal Note" tab, so it seems to be an issue with the "Post Reply" tab.

Posting something like:

> Hello
> 
> World

will not work... 

However, when using something like:

> Hello World

Or:

> Hello
> World

It will work just fine.

I am not familiar with the structure of OSTicket or I would try to work up a fix, but I'm not well versed in javascript and php either, so there is that...

I figure that if the same filtering process that the "Post Internal Note" form uses is applied to the "Post Reply" form, it should fix it?(formatting issue?)  Not 100% sure about that though, because I looked into 406 errors and it makes me wonder if the fact that I'm using a godaddy web hosting account that is the issue, but the fact that it only happens in the "Post Reply" tab makes me wonder if that is actually the case.  Everything else works just fine.

[Issue was raised on OSTicket forum](http://osticket.com/forum/discussion/comment/87108/#Comment_87108) as well, but I'm not sure if there is an actual "fix" for this yet, as I have not seen any success stories while searching throught the forums and on google.

**Comment by huyabusa1300** [comment]
I was getting the exact same error and tried to delete one of the line breaks and sure enough it posted! I too am hosting on GoDaddy.

**Comment by grintor** [comment]
I have confirmed this issue is from their mod_security config. I contacted their support for our account with the same problem. Their support is *almost* useless.

I found that when I responded to a ticket with the text "​We can add or delete users from the group if you would like." I got that error Upon further investigation I found that the text "delete users from any_word" is the magic phrase in this case. I think we can guess why...

The moral of the story is-- godaddy has a very overzealous mod_security. More info on that here:
http://developers.wpeasycart.com/2014/07/31/godaddy-shared-hosting-now-an-issue/

**Comment by greezybacon** [comment]
@grintor thanks for the update

**Comment by jcbeto00** [comment]
I would like to limit with something about the error 404 exposed at the beginning of this post because I had the same error in this week and after 3 days investigating I found the possible solution.


{    Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

I have figured out how to reproduce this error.

If I use the "Post Reply" tab and there is a blank line between chunks of text(2 new-line chars?), it will produce that page.

Using the same text that throws an error while using the "Post Reply" tab will not throw an error if I use the "Post Internal Note" tab, so it seems to be an issue with the "Post Reply" tab.

Posting something like:

    Hello

    World

will not work...

However, when using something like:

    Hello World

Or:

    Hello
    World
}

# **In my case:**

I was using the Post Reply box to send this reply to you. This is where the issues were coming from previously. The current URL is http://www.domain.com/support/scp/tickets.php?id=1290 and when I hit 'Post Reply' the URL changes to http://www.domain.com/support/scp/tickets.php?id=1290#reply and the error has been occurring.
 Our Domain has https and when the agents use http or just www.domain.com they got the error 404

# SOLUTION

I wrote this  changed something in our configuration of redirection of pages web in our hosting server, on the file  **.htacces** I've tested replying a ticket and now is OK.

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>

# END WordPress

I hope this help you a little bit.
