### ISSUE TITLE
Response: "Original Ticket" breaks for text/plain Mails

### ISSUE THREAD

**Issue by tzeumer** [osTicket/osTicket#1490]
Assume receiving and sending HTML mails is enabled (using osTicket 1.9.4). If a plain/text message is received the linefeeds should be kept when inserting the "Original Ticket" (or the "Last Message") in a reply. Currently the result is that the whole message is shown as a single line only. I think that this definitely is a wrong behaviour.

A somehow related thought: wouldn't it make sense to disable the html editor automatically if a message was send as plain text - assuming the sender would expect that?

While I really like the new html editor (and the other new features), there are still old school mail purists out there :) :D

**Comment by ulfkreutzberg** [comment]
Hi all,

I expect a similar problem, too (v1.9.12 (19292ad)).
While the richt text editor is disabled, sometimes newlines are stripped off in plain text responses. So users get single-in-line responses which is unwanted (of course). This happens when using Firefox under MacOS Yosemite (just in case it has something to do with MacOS's handling of newlines).

Best regards,
Ulf
