### ISSUE TITLE
Feature-request: Create Ticket - Chose Department

### ISSUE THREAD

**Issue by Venice-89** [osTicket/osTicket#1542]
Hi,

we have many Help Topics for different departments, so the DropDown List  on the user interface is very long.
It would be nice to split these to a maintopic and a variable subtopic list.

Alternative, implement a Dropdown list for choosing the department and then only show the department based Help-Topics

**Comment by ejobran** [comment]
Hi jhonny9696,
We tried to use this code in our OSTicket system but unfortently when we select a department all topics are listed. we couldn't figure out where the problem is. would you please help us

**Comment by Macel** [comment]
I'd love to see this feature added to the core software as well.  Since my organization only has two departments, my workaround has actually been to clone our OSTicket instance and run the other department on their own site.  I am avoiding custom modifications to the code since doing so can cause issues at upgrade time.

I disagree with the design philosophy that help topics should automatically drive which department gets selected for every organization..  In our case, the two departments are vastly different (custodial and information technology) and the user is definitely expected to know which department to submit their issue to.  Between the two departments we have 40+ help topics, and having every topic in one big list is a cause for people to choose the wrong help topic.  And no, narrowing down our list of topics is not an option.
