### ISSUE TITLE
[API] Allow to check hostname or to disable check for a given key

### ISSUE THREAD

**Issue by Alex131089** [osTicket/osTicket#1670]
Hello, 

last time I tried osTicket I had to put an allowed IP with the API key (as documented in https://github.com/osTicket/osTicket-1.8/blob/develop/setup/doc/api.md).
I think this is too restrictive and the verification could be more flexible by allowing an host (which itself can have one or more A and one or more AAAA, osTicket has to interrogate the given host), and/or should be possibly turned off for a specific key.

The problem I had is the following : I wanted to use email piping on another host, they are connected with IPv4 and IPv6 and I want osTicket to be functionnal even if IPv4 or IPv6 is down. With the current restrictive system, it is not possible to do proper email piping as the client on the email server can only contain 1 API key, which is attached to either the IPv4 or the IPv6 address.

Could you change this ?

Regards,

**Comment by greezybacon** [comment]
@Alex131089 I agree with you. I'd like to see the key system change to a public/private key set, where the public key part can be used to fetch information from the API like help topic lists, etc., and the private part is used to post data, like new tickets. I'd then like to see the keys treated more like an automation "account" so to say, so that any host with the keys can push data to osTicket.
