### ISSUE TITLE
New feature request: disable ticket creation by email

### ISSUE THREAD

**Issue by fictionedge** [osTicket/osTicket#1694]
Can you make it possible to disable ticket creation (but not response) by email?
We get allot of emails from users that are not ticket related.
Also the use of ticket creation by email makes impossible to force them to fill required fields.

Cheers

**Comment by greezybacon** [comment]
Yes. Add a ticket filter to match a target of "Emails" and check the box to reject the ticket. Ticket filters are only applied to new tickets — not to email continuing an existing ticket.

**Comment by fictionedge** [comment]
I still have to add a filter rule, what is the best choice for this one?

**Comment by kevmimcc** [comment]
I might recommend a filter on your email system and have emails to be tickets forwarded to a dedicated email address for creating tickets.  That process could be automatic by a filter or manual as someone goes through the inbox and forwards all emails that need to be tickets to the dedicated email address.  I believe you could still set the email sending credentials to use your original email address so outgoing responses are still coming from there.

**Comment by jamesaepp** [comment]
I also want this feature. I would love if inbound emails for untracked/new tickets went into a queue so that they had to be manually approved by an agent. My use case is as follows:

I want all tickets to require signing of a liability waiver. We could circumvent this by having them sign a liability waiver when they sign up for a user account and not for every ticket, but what if our terms change in the future? Terms of use are dynamic things subject to changes and what they agreed to when they signed up for an account may not reflect the new terms.
