### ISSUE TITLE
Vague error messages

### ISSUE THREAD

**Issue by henrycoule** [osTicket/osTicket#1824]
Users are confused when they see the error message 

"Unable to update the ticket. Correct the errors below and try again!"

I mostly get the question, "I didn't see any error so what do I correct?"  Is there a way to just mark in red the affected reason for the error so users will clearly see where the error is so they can fix it?

**Comment by ntozier** [comment]
So... my installation puts red text after the sections that failed.
(see image)
![capture](https://cloud.githubusercontent.com/assets/1315768/6619133/93793b38-c89e-11e4-9ec1-f9635442bea3.PNG)

**Comment by protich** [comment]
@ntozier -- yes, but notice no error on issue details and yet it's required. We have a fix for it and will ship with the next version.

**Comment by Chefkeks** [comment]
@protich 
Just some thought on this...

Maybe you should put the little red star that indicates a required field before or after the field label instead of behind the field itself to indicate required fields a bit better.
* Issue Details
Issue Details *

Or replace the little red star with the exclamation mark icon when the user hits the "create ticket" button or so - anyway, excited to see with what you guys come up since you mentioned that you have already a fix for that ;)

**Comment by protich** [comment]
@Chefkeks - I agree with your suggestion of putting the error near the label especially for a text-area field --- I believe we've made such change in develop-next. 

Overall, form rendering and layout could most definitely use some TLC, we're planning on introducing a form designer in the near future -- which will also spot real-time data validation & errors.

**Comment by greezybacon** [comment]
@henrycoule could you see if the patch in #1821 addresses the issue?
