### ISSUE TITLE
New Feature : Browser Notifications

### ISSUE THREAD

**Issue by supportreq** [osTicket/osTicket#1830]
Hey @greezybacon we should have a feature like Gmail which pushes notification to the browser screen for the staff area. This will allow the staff to look at the notification even if he is on an another application.. Browser notifications are now standardized and present for all major browsers..

Suggest

**Comment by ntozier** [comment]
This is something that has become predominant in the industry for a lot of server style applications / standalone apps.  And maybe your right it is something that should be considered... 

But personally I hate pop up notifications like this.  I've disabled them in most of the apps that I use regularly [if they let me] because I find them distracting to the task that I am currently working on. IF something like this was added [and it probably should be] I'd ask that either the admin, or the end user have the rights to disable the notifications.

**Comment by fictionedge** [comment]
+1 this kind of notifications on a software with this importance would be greatly helpful

**Comment by greezybacon** [comment]
I agree. Considering how many server configurations have trouble with the PATH_INFO detection, it'll be an uphill battle using long poll or WebSocket interfaces along with threading or a message broker to get push notificiations from the sever backend. But again, I agree this would be a handy feature. 

For the near future. I'd like to see an "Recent Activity" dashboard page similar to the GitHub notifications view to help find recent activity on various tickets.
