### ISSUE TITLE
Double Submissions on clicking post reply (client and agent)

### ISSUE THREAD

**Issue by voarsh** [osTicket/osTicket#2004]
Clients and agents can, by accident submit replies multiple times by clicking submit more than once.

It would be good if this could be sorted so only one response is submitted.

**Comment by greezybacon** [comment]
This is addressed in `develop-next` with the locking feature as the lock code required to submit a reply or note is rotated on submit. A page refresh afterward will result in an error. This however, only applies to agents

**Comment by voarsh** [comment]
:+1: 
I hope this is applied in the next patch/release as default and that something can be done about clients sending loads of submissions by accident.

**Comment by erlangsec** [comment]
This bug is problematic in Edge (Windows 10) since there for some reason is not triggered any progress indicator (page loading) upon clicking the submit button (I've not observed this apply to forms in general). So, when the SMTP connection takes up a bit of time, one could end up clicking both 5 and 10 times before getting to the next page, hence sending the message an equal amount of times.

**Comment by simonebracaloni** [comment]
I am testing this quickndirty workaround on v1.9.4.
I added this line in the onSubmit method in ticket.js, but I'm not sure if there are cases where the button remain disabled until the user manually reload the page. 

```
                    return false;
                }
            }
        }
        //Prevent double click
        $(e.target).find('.btn_sm').prop("disabled",true);
        return true;
    },
```

**Comment by voarsh** [comment]
Any update from developers about this issue?
