### ISSUE TITLE
New tickets are being opened on replies.

### ISSUE THREAD

**Issue by brandonberney** [osTicket/osTicket#2046]
## Background Information
- We are using the latest code available on this repository for osTicket.
- This is our current configuration:
  ![Configuration](http://i.imgur.com/x9jDLA0.png)

We use Mailgun to send and receive emails. Mailgun uses a routing system, so we have setup a custom API to connect to osTicket's JSON API. Emails go through fine, but when a client replies a new ticket is opened. We are using the default configuration for templates, and the ticket number, [#1241523523] for example, is included in the subject.

**Comment by greezybacon** [comment]
Interesting. osTicket doesn't support continuing the conversation via the API. Would you be able to configure Mailgun to post the raw email to osTicket?

**Comment by misread** [comment]
I don't believe so. The only options Mailgun allows is to forward the incoming messages to another inbox (which causes it's own problems, since I can't specify a different username and password for pop/imap) or to forward it through post requests.

https://documentation.mailgun.com/quickstart-receiving.html

I've included their documentation on routes in case I didn't explain it well enough.

**Comment by vekexasia** [comment]
Hi @misread did you find a solution to this?

**Comment by icenine457** [comment]
Also interested in this. Would like to see how difficult it would be to enhance the API to allow for continuing the conversation via the API, as that would be an ideal workflow for our project.
