### ISSUE TITLE
1.10DPR installation error

### ISSUE THREAD

**Issue by harrisyn** [osTicket/osTicket#2072]
When trying to install the developer release, I am getting 
Fatal error: Can't inherit abstract function AuthenticatedUser::getId() (previously declared abstract in BaseAuthenticatedUser) in C:\webroot\auction\Redlin\include\class.auth.php on line 26

After completing the install.php form and submitting. The database gets created but the tables arent and i get a white screen.

Any directions will be appreciated.

**Comment by harrisyn** [comment]
Attempted an install of the 1.9.8 and it succeeded without the above issue.
1.10 still fails though.

**Comment by ntozier** [comment]
Did you re-download the 1.10 archive from the web page?  @greezybacon uploaded a new version to the web site on May 14, 2015 at 11:45 AM.

What version of PHP are you running?
Please provide a little more about your server setup.

**Comment by harrisyn** [comment]
I downloaded the archive from osticket/download and this was after @greezybacon  uploaded the new version. I noticed however that the class.auth.php files are different between what is on github and what I downloaded. tested using the files from Github to the same result.

Windows Server 2003
Apache Server
PHP 5.3.1

**Comment by mfelber** [comment]
I have just tested the actual download of 1.10 also on my windows test machine and have no problems. But my environment is different: 
osTicket Version 	          v1.10-dpr-6-g3e4b685 (3e4b685)
Web Server Software 	 Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.11
MySQL Version 	         5.6.16
PHP Version 	                 5.5.11
I have seen similar php errors due to a php bug. Maybe you have the option to test a newer php version. 
5.3.1 seems to me to be not so a good choice. I think 5.3.29 is the last version of the 5.3.x tree..

**Comment by greezybacon** [comment]
> PHP 5.3.1

I think PHP < 5.3.8 has some inheritance bugs. Are you able to upgrade your PHP?

**Comment by greezybacon** [comment]
It just occurred to me this is still an issue for v1.10. With we have to fix it or bump the requirements for v1.10 to php 5.4

**Comment by harrisyn** [comment]
Didn't work on 5.5 either so bumping up the PHP requirements to 5.4 may not
be the fix.

Had to upgrade to 5.6.10 to complete the install.

**Comment by greezybacon** [comment]
@harrisyn I know the install works on 5.4

**Comment by drewx0r** [comment]
Has there been any resolution of this? Is there a workaround for 5.3.3 (for example), or are the requirements getting bumped?

**Comment by ntozier** [comment]
The work around is to upgrade your PHP to a version of 5.3.4+.  
Such as 5.3.6, 5.3.11, 5.3.16, 5.3.27, etc.  I personally am running 5.3.13 and have been for quite a while.  Although i wouldn't be surprised if the PHP requirement was bumped at some point. (since 5.6.12 is current, and 7.0.0 beta 3 is out.)
