### ISSUE TITLE
Fast status change

### ISSUE THREAD

**Issue by lehha** [osTicket/osTicket#2137]
In viewing the ticket need one big button - to close (or "Resolved") a ticket (set status in one click). 

Now we have to choose the drop down menu "chang status", choose the desired status, in the form and click "Close." (too many clicks and slow), or set status without confrimation form.

**Comment by infectormp** [comment]
+1

**Comment by protich** [comment]
A single button to close a ticket is not viable, at the moment, due to possible addition statuses with closed state. In other words, the closed status (incase of multiple closed statuses) to use on click.

That said, we've discussed the possibility of adding default `closed` status setting in Admin Panel > Settings > Tickets -- which will allow us to add one click button to close ticket on reply  i.e  __[__ Post Reply & Close \/ __]__    __[__ Post Reply __]__  (Where \/ is a dropdown hint for more closed statuses -- if they exist).

**Comment by ntozier** [comment]
I really like the idea of a big [ Close ] button.
But if it was to be implemented I think that it should have a default "close" message [template] that gets sent if its used.

**Comment by AlexYoung28** [comment]
+1 It's an awesome idea!

**Comment by protich** [comment]
@ntozier --  Here is the issue, would you want to send the said message template every time a ticket is closed? What about if you're closing a duplicate or junk ticket? My point is, there're countless cases that such message shouldn't be sent --- which will result in more & more checkboxes in admin panel for exceptions..etc.

We think such action should be part of an upcoming  Automation feature (more on this later) and not baked into one-fits-all type of implementation, that we're currently fighting to unwind.

**Comment by Chefkeks** [comment]
@protich
I like the idea to have a default closed status. Beside I'd suggest to replace the "change status" with a "close" button <b>IF<b> there are no other statuses. For example we use only the 2 default statuses "open" and "closed" and so the drop down makes no sense since there is only one status to select.

I like the idea of having a dedicated button with a drop down arrow (post reply and close \/ ). As it works currently is not bad, but also not good since I sometimes forgot to change the status several times - so I guess to have a post reply and close button is really helpful as well as a default closed status.

**Comment by ntozier** [comment]
@protich I actually envisioned the template ONLY being sent if the button was used.  But I get your point. :)

**Comment by infectormp** [comment]
Guys, if you want make a real easy and fast interface for agents you need look to spiceworks :) They have most easy interface that i have еver used.

**Comment by protich** [comment]
@Chefkeks -- that is exactly the planned enhancement.

**Comment by markus4000** [comment]
Another Idea: 
what if the next status would be defined in the status properties?
Eg: with 4 status;
New
Planned
Work in Progress
Closed

The new status has the planned status as its BIG button
"answer and set status planned"
Etc.

The for "work in progress" -> "answer an close"

So you there will be full flexibility.
