### ISSUE TITLE
Quality Control Services

### ISSUE THREAD

**Issue by MAlexey** [osTicket/osTicket#2178]
Your system is excellent. And it is wonderful that you are improving it continuously.
I would like to suggest an important function. Customer feedback. Feedback is very important to control the quality of the service, but ostiket it has not yet.
The point is to control the quality of the service system itself.

One of the most effective methods in the world is called the Net Promoter Score, according to which customers enough to ask only one question: "Would you recommend us to your friends?"
At the close of the application is sent to the client with an opportunity to answer this simple question: "Would you recommend us to your friends?"
The system stores the result and displays it in the analysis section.

Thus, management can control the quality of its customer service department.

**Comment by ntozier** [comment]
You can do this easily with canned responses and an embedded link to the survey site of your choosing.

**Comment by MAlexey** [comment]
Then I can do without ostiket. I'll be in correspondence in the mail.
The point in the development of the functionality of the system.
At your option you will have to use third-party tool.

**Comment by ntozier** [comment]
Your response doesn't make much sense to me.  People use the tools that work for them that fit their criteria. osTicket is not a polling/survey software.  Its a ticketing support system.  If polling/surveying was added to osTicket it would never be as good as the solutions that already exist, because that's not the point of the software, and reporting would be nearly non-existent.  Sites like survey monkey or survey gizmo provide full survey/polling and reporting in a nice easy to use interface that you can push info to in the url you provide. Why try to recreate the wheel?

**Comment by infectormp** [comment]
@MAlexey you can use LimeSurvey

**Comment by greezybacon** [comment]
Even better, you could put the link in the reply/response template

**Comment by markus4000** [comment]
+1 for an additional emailtemplate in case of closing the ticket. So then the link for the survey is only added when the ticket is closed.

**Comment by arkhan** [comment]
+1
