### ISSUE TITLE
Bug: Back Color, none is broken

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#2229]
If you edit a message and you have first line where text have back color and second line who have back color to, you want remove back color in second line if you select the second line
1. (see screenshot)
   and then on Back Color selected "none" the button none not work, the back color is not removed. 
2. (see screenshot)

Tested in version 1.9.9

![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/8557403/7bcd4c48-24fd-11e5-8a2e-befbf472662e.png)

**Comment by ntozier** [comment]
I tried this in 1.10 in three separate browsers and highlighting the second line and clicking none, removed the back ground color from both lines.

This appears to be a problem with Redactor.

**Comment by greezybacon** [comment]
@ntozier can you confirm it is broken in v1.9.9?

**Comment by ntozier** [comment]
I currently don't have a 1.9.9 or 1.9.9-1 install but I'll set one up and report my findings if I get the chance today.  If not today then like Monday.

**Comment by greezybacon** [comment]
It seems broken in v1.9.9. What I did:

* Type two lines of text
* Highlight both lines and change the background color
* Then, highlight the second line and set the background color to "None"
* ... nothing happens

In v1.10, the problem is somewhat there still. When the second line is changed to a background color of "None", both of the lines have the background color cleared.
