### ISSUE TITLE
1.10 RC1 Update client and agent login banner 

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket#2288]
After updating 2. language at client and agent banner template changes are saved but last updated is not changed. If you change langugage at front end always the english template is shown.
![client](https://cloud.githubusercontent.com/assets/10116166/8873104/7fb58448-3203-11e5-84cf-885553c03fc8.png)
![frontend](https://cloud.githubusercontent.com/assets/10116166/8873103/7fb28ce8-3203-11e5-892a-e8f8cb828c05.png)

**Comment by ntozier** [comment]
What language is your webbrowser reporting?
My understanding is unless your browser pushes the language it will default to english.
Once a person logs in it will use their language settings on their account.

**Comment by gmt-it** [comment]
@ntozier 
1. What the hell should your statement about Browser pushes something? If a first time customer click the german flag he wants to read German. The text says please open an account. After the customer registered an account the System should set the language to whatever the customer setup. But a new customer has to read the banner in that language that he hopes to see after set language to the one which he understand. By the way: My Browser knows I'm in Germany.
2. The Browsersetting has also nothing to do with the Update flag in database. If you edit the second language, Updated has to set to current date and should not show the time when Standard language was updated.
Hope you understand my little English.

**Comment by ntozier** [comment]
1. What the hell should your statement about Browser pushes something?
When a web browser pulls a document from the web it sends a request to the server where the information is stored (the web server).  This is called an HTTP request, and with said request it send information about your language preference settings. ie The web browser identifies what language it wants.  It's typically transmitted in the HTTP header as "HTTP_ACCEPT_LANGUAGE".  What language is your browser sending?

New users don't have a language preference until they have an account and set one.  Until then if the browser doesn't set the language expected then my understanding is it defaults to English.  Because the user isn't logged in.

2. I have not commented on update flags in the database.  I'm explaining why the ui shows english instead of what you think it should.

**Comment by gmt-it** [comment]
Please take a look at the screenshot.  All text is German only bannertext is English. The user has the choice to select the language with the little flags at top of site at the right side.

**Comment by greezybacon** [comment]
It also looks modified. Care to share what modifications you've applied?

**Comment by gmt-it** [comment]
@greezybacon 
Hi Jared, no code changes, only colors and client design. It is a new installation not an upgrade. Second installation is an develop-next upgrade with same behavior.
