### ISSUE TITLE
Customers should see which agent has produced the entry

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket#2296]
Hello everybody,

to create more transparency, it would be nice if customers see the future, which has left some agent "public" in the ticket.

it would also be great if the customer sees that the ticket agent in processing has

![2015_07_24_23_34_03_ffg_de_uh_tss01](https://cloud.githubusercontent.com/assets/13413719/8885065/8fe90c96-325c-11e5-8435-d6c89a09f34c.png)

**Comment by ntozier** [comment]
Version of osTicket?

"it would be nice if customers see the future"
It would be nice if anyone could see the future, but since time travel hasn't been invented yet [to my knowledge]...  On a more serious note I'm not real sure what you are asking for.

On the second thing: Do you have Admin panel -> Settings -> Tickets -> Agent Identity Masking checked?

**Comment by oneilak** [comment]
ah ok, i test this function :-) thx

**Comment by oneilak** [comment]
that works perfectly ...

Now what would be even more beautiful,
If a customer sees which agent the ticket currently being processed

**Comment by ntozier** [comment]
Once the agent replies to the ticket the email tells them who is processing the ticket.

**Comment by oneilak** [comment]
that's right, but I find from a customer perspective, this is not really visible.

**Comment by greezybacon** [comment]
@oneilak Are you suggesting that the ticket assignee be shown on the client interface?

**Comment by oneilak** [comment]
yes, it would be good if you could make the show optional

**Comment by oneilak** [comment]
is it coming in v1.10? :-)
