### ISSUE TITLE
1.10 RC1 Issues - Open Task from Ticket

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#2298]
When you click on a task attached to a ticket from the ticket view it opens a page that is un-formatted with a url of `/scp/ajax.php/tickets/2/tasks/3/view`

**Comment by ntozier** [comment]
@greezybacon It looks like the headers are not being sent.
Page source: 
line 1 empty
line 2 <div class="has_bottom_border" class="sticky bar stop"

**Comment by jdelhome3578** [comment]
![image](https://cloud.githubusercontent.com/assets/5774055/9212616/87fde736-4058-11e5-81ad-33478df2649a.png)

**Comment by jdelhome3578** [comment]
@greezybacon this issue still happens in 1.10 rc2 but not every time.

**Comment by jdelhome3578** [comment]
@greezybacon I have noticed this happens when the action takes longer than 250ms

**Comment by a-schild** [comment]
We see this too in a new installed 1.10 version. Any hints?

Serverinformationen
osTicket-Version 	v1.10 (901e5ea) — Aktuell
Server-Software 	Apache/2.2.22 (Debian)  Wheezy
MySQL-Version 	5.6.35
PHP-Version 	5.6.30-1~dotdeb+zts+7.1

APC and Zend Opcache are enabled

**Comment by josencv** [comment]
Any news on this?

I've noticed that when this happens, the task preview ajax url appears in the browser, instead of the task url. I don't know why this happens though.

**Example**
Url should be: scp/tickets.php?id=553#tasks
But instead it is: scp/ajax.php/tickets/553/tasks/358/view

**Comment by sublervious** [comment]
We were having the same issue viewing a task from the ticket and came up with the following solution:
In ticket-tasks.inc.php change the following:
Line 93: $viewhref = sprintf('#tickets/%d/tasks/%d/view', $ticket->getId(), $id);
to
Line 93: $viewhref = sprintf('./tasks.php?id=%d', $id);
AND
Line 155: var url = 'ajax.php/'+$(this).attr('href').substr(1);
to
Line 155: var url = 'tasks.php?'+$(this).attr('href').split('?')[1];

Revised ticket-tasks.inc.php file attached. (Line numbers are different because I left the commented out code in there)
[ticket-tasks.inc.zip](https://github.com/osTicket/osTicket/files/1258648/ticket-tasks.inc.zip)
