### ISSUE TITLE
Feature request 1.10: Log changes to Tasks attached to Ticket in Ticket Thread

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#2316]
When changes or updates occur in a task attached to a ticket update the ticket thread with `updates to task # made at ...` or `Task # completed by someone at ...`

**Comment by Chefkeks** [comment]
:+1:
Good idea - definitely like this - but depending on the number of tasks and updates this could may confuse agents since then there are maybe too much info in the ticket thread. Maybe a combined ticket & task thread which lists all events would be good or just showing important messages, eg. when a task has been completed.

Wonder how the devs think about this ;)

**Comment by protich** [comment]
Logging updates/everything will be confusing -- I think system message log for events like created, completed and deleted will be the happy medium.

**Comment by jdelhome3578** [comment]
That's what I was thinking thank you @protich

**Comment by bwl21** [comment]
Why not have a Filter when displaying the ticket thread.

**Comment by JediKev** [comment]
Available via Audit Log Plugin.
