### ISSUE TITLE
DB Error 1054 - v1.10-rc2

### ISSUE THREAD

**Issue by arthursim** [osTicket/osTicket#2474]
> [SELECT page.*, count(topic.page_id) as topics FROM ost_content page LEFT JOIN ost_help_topic topic ON(topic.page_id=page.id) WHERE page.content_id=3 GROUP By page.id] Unknown column 'page.content_id' in 'where clause'

I've been getting about 10 of these per day. Any thoughts? The upgrader seemed to finish without any errors.

**Comment by arthursim** [comment]
>[SELECT id, f.type, size, name, `key`, signature, ft, bk, f.created,  count(DISTINCT a.object_id) as canned, count(DISTINCT t.ticket_id) as tickets  FROM ost_file f  LEFT JOIN ost_attachment a ON(a.file_id=f.id)  LEFT JOIN ost_ticket_attachment t ON(t.file_id=f.id)  WHERE f.id=6 GROUP BY f.id]

Started getting these as well, error 1146

**Comment by greezybacon** [comment]
I can't find the first query in the code base. Do you need to deploy into a fresh folder?

**Comment by greezybacon** [comment]
I can't find the second one either. Do you have a cron running on an old install path that is connected to the new database maybe?

**Comment by clonemeagain** [comment]
I had this error, fixed with: https://github.com/osTicket/osTicket/pull/3109

Error is in include/class.page.php `WHERE page.content_id=3` doesn't work, as `page.content_id` doesn't exist, only `page.id` exists.. 

Try browsing to edit a "page" as well, they don't show, just get an error. 
Didn't test publically, but I imagine the same error. 

FYI: I was running stock from osticket.com/download
