### ISSUE TITLE
v1.10-rc2 Tables in Canned Responses

### ISSUE THREAD

**Issue by rowlandan25** [osTicket/osTicket#2518]
I created a table in the canned response with some data filled in (like the headers and the first column) and hit save.  However, when I tried to pull the canned response into a ticket, it only brought the columns that had something in them.  The empty cells were removed from the table, and the table was shifted to fill in those gaps.

Workaround:  To work around this issue, I simply put a space in each of the blank cells.

**Comment by sagund07** [comment]
I have a similar problem.

I have an external formular which sends an email with an HTML table inside to the support address which is managed by osticket. The problem is that osTicket reads the table and posts it in the ticket but removes all empty cells.

For example I have a table with 3 columns (A, B, C). If someone fills in the fomular with the following data

A | B | C
Hello | World | Text
Test | {empty cell} | Text
{empty cell} | Test | message

osTicket will display it in the ticket as

A | B | C
Hello | World | Text
Test | Text
Test | message

The tables are completely messed up.

If I create a table with empty cells directly in the ticket response field, it will show the table correctly. It seems that there is a problem when importing/posting tables from outside the staff editor.
