### ISSUE TITLE
OST 1.10 "Lookup or Create User" bug..

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2582]
In the "Lookup or Create User" dialog box only pre imports user data if they are local it seems to ignore the LDAP/remote users and does nothing and just refreshes.

![09232015-220927](https://cloud.githubusercontent.com/assets/2892474/10063959/8fe7185e-6241-11e5-988e-f07038195788.png)

**Comment by greezybacon** [comment]
Would you be able to test the patch in osTicket/core-plugins#85?

**Comment by philbertphotos** [comment]
Yes in i can

**Comment by goobersmooch** [comment]
I'm having this issue as well. I would like to test the patch, but i'm not sure how to re phar the files after i've extracted and edited the authentication.php file. I used unphar.com to convert the auth-ldap.phar to a zip so i could edit the files. How do i put them back into a phar?

**Comment by goobersmooch** [comment]
After some digging I've finally found the cause of this problem.

I started with the  v1.10-rc2 branch and started adding commits from the develop-next branch one by one until I found which one broke the user lookup from LDAP when creating a new ticket via the agent panel. It seems that the culprit is commit  2763707605e7875072adabdd91d95c713eeff9ae from #2479.

**Comment by kest874** [comment]
Can confirm this is broken again.

**Comment by philbertphotos** [comment]
IS there is fix for this?

**Comment by ntozier** [comment]
Plugins are usual updated after a release. (Or just before)

So I doubt it.

**Comment by philbertphotos** [comment]
Wait you mean the actual plugin has to change but in what way?? I can easily alter my plugin but i need to know what changed:
