### ISSUE TITLE
v1.10 Final finish

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket#2630]
Hey together

there is a date when the 1.10 is "finished"?

**Comment by Chefkeks** [comment]
Usually "it's done, when it's done"... so there is no specific date or deadline. Reason is that a new version is released when all features are done and major/minor bugs are fixed and several made tests are passed.

Doesn't make sense to release a new version which is not finished or still missing features/fixes just because a specific deadline or date is reached - that would bother people more than a later release I think ;)

**Comment by oneilak** [comment]
hey

yes that's clear and "finished" is the whole anyway never :-)

thought I'll ask if there is a targeted schedule: P

**Comment by ntozier** [comment]
You are probably not going to get a satisfactory answer to your question.  
Yes there is a loose schedule, no you cannot see it, no you will not get an exact date.

**Comment by Aka4** [comment]
We would like to use 1.10 in production (now we have 1.9.8.1)
What do you recomend (we do not want to wait for official stable 1.10 realease):
-1.10-rc.2 beta release from https://github.com/osTicket/osTicket-1.8/releases/tag/v1.10-rc.2
-tip of develop branch https://github.com/osTicket/osTicket-1.8/tree/develop
-tip of develop-next branch https://github.com/osTicket/osTicket-1.8/tree/develop-next
?

Which one of this is more stable with more bugs removed?

**Comment by oneilak** [comment]
Hey boys

there is the something new? :-)
We are already waiting to finally upgrade :-)
