### ISSUE TITLE
v1.10-rc.2-135-g1aaa313 - Agent Access Select Role Drop-down Tool Tip Is Blank

### ISSUE THREAD

**Issue by goobersmooch** [osTicket/osTicket#2675]
Under Agents --> Selected Agent --> Access Tab, the select role drop-down box tool tip is blank.

![osticket1](https://cloud.githubusercontent.com/assets/15216195/10705133/66b4ff74-79a1-11e5-98cf-9f9d9090ef81.jpeg)

**Comment by c0nfused** [comment]
Same problem here.

**Comment by colonelpopcorn** [comment]
It looks like the staff.agents.yaml file (i18n/en_US/help/tips/staff.agents.yaml) is empty and the other tooltips might be hard-coded(?) No, that can't be right. So the tooltip that's supposed to show up is not showing up because it hasn't been put into staff.inc.php properly. I'll post what I mean when I get home. Line 251 of staff.inc.php has a "primary role" reference, but there isn't a "primary role" thing defined in staff.agent.yaml.
