### ISSUE TITLE
1.10 RC2 - Thread_entry body over 64k breaks reply form

### ISSUE THREAD

**Issue by Lauwens** [osTicket/osTicket#2730]
The relpy-to on our newsletters are fetched by osTicket as new tickets. Most reply with the newsletter quoted and this makes the mails exceed 64.000 characters.

Problem is that it breaks in the middle of some html from the newsletter resulting in bad html mark-up for everything underneath the entry.

![example](http://www.sennetshop.be/support.gif)

Most of the times if it happens nothing submits anymore in the reply form 

I tried changing the body field in the DB from TEXT to a blob, but the content is still trimmed to 64k somewhere

**Comment by ntozier** [comment]
Add an (invisible to the reader) Reply Separator Tag into your newsletter.

**Comment by Lauwens** [comment]
And if that is out of my control ?

I didn't have this problem on the 1.8branch so I was wondering if there is a reason why the field is now limited

**Comment by ntozier** [comment]
Well... I would be surprised if you couldn't have the HTML newsletter template altered to add a simple
'<div style="display:none">-- do not edit --</div>' near the top.

By default _ticket_thread body is a MEDIUMTEXT.  So it should be able to hold 16,777,215 bytes (or 16 MiB). If you are actually hitting the data cap for that field you could update it to a LONGTEXT (4 GiB)... or BLOB. Since you said that you already changed this to BLOB... I feel like something else is going on.

Whats your table Character set and Collation set to?

**Comment by Lauwens** [comment]
utf8 and utf8_general_ci this is on a MiariaDB 10.0.20

**Comment by ntozier** [comment]
What is your max_allowed_packet size?

**Comment by Lauwens** [comment]
SELECT @@global.max_allowed_packet 
result: 33554432
