### ISSUE TITLE
1.10-rc.2 "deploy" do not is executed 

### ISSUE THREAD

**Issue by Kozlov-V** [osTicket/osTicket#2781]
I try deploying cloning code, and run this command as root:
`php manage.php deploy --setup /var/www/htdocs/osticket/`
but nothing happens
/var/www/htdocs/osticket/ - is empty

all files and folders have 777 permission

**Comment by jk3us** [comment]
Same here.  RC1 does the same thing.  Both just print 

    <html></html>

to the console and do nothing to the deployment directory.  In fact, running `php manage.php` with anything (or nothing) after that does the same thing.

**Comment by Kozlov-V** [comment]
+1

**Comment by greezybacon** [comment]
Is this fixed in #2571?

**Comment by timwhite** [comment]
@greezybacon Seems to be working in develop-next, so I'm guessing #2571 has probably fixed it. Any idea when the next RC will be? RC2 seems a bit of a wash if you can't install it.

**Comment by greezybacon** [comment]
@timwhite @protich mentioned it would happen this month

**Comment by ntozier** [comment]
@timwhite 
FYI: The devs have asked that people download from http://osticket.com/download to install in the past.
My 1.10rc2 install is humming along just fine.  Also its a release candidate put out specifically for testing...

**Comment by timwhite** [comment]
@ntozier downloading from develop-next allows people to test if things have been fixed. There are features in 1.10 that I wish to use, and the best way to test them is with rc2. By using git, I can test rc2, and then roll forward along develop-next to ensure that they are working for the next rc. No point having a RC, and then in the next RC realise it's not actually fixed. I have no problem installing from Git and testing things, my query about the next RC was because in my projects I try and get major breakages in RC's fixed as quickly as possible, and a new RC out so people aren't still hitting the same broken bit when testing.
A "Release Candidate" should be basically release ready, so if it won't even install, then a new RC needs to be produce quickly.

Please understand, I'm not upset at anyone, just an active developer in other projects, who understands time is limited for developers, but was wondering when the next RC was planned. It helps me know how I can keep assisting by testing things, reporting back on bugs that are now fixed etc.

It may also help if milestones and labels were applied to the issues so the state of them isn't left up in the air. This bug could have a "fix available" tag for example, or even be closed with a comment that the fix is in develop-next waiting the next RC.
