### ISSUE TITLE
Advance search save filter issue

### ISSUE THREAD

**Issue by zeeshankhurshid** [osTicket/osTicket#2787]
By mistake once I saved a filter search case with no name, first it gets saved with null plus it took my osticket portal down. [ this is related to your new advance search release under 1.10]

**Comment by ntozier** [comment]
You would have to either manually edit your DB or run a SQL query to fix this.

This SQL statement
UPDATE ost_queue SET `title`='EDITME' WHERE `title` IS NULL;

Will update any saved search with out a name and set it to EDITME.  So then you can click on it in the ui and edit it.

**Comment by greezybacon** [comment]
This seems to still be an issue on the `develop-next` branch

**Comment by balojs** [comment]
@rayfoss  please check this bug
### Prerequisites
* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
       Yes
* [ ] Do you have any errors in the PHP error log, or javascript console?
       No
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
      No
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? 
     Bug

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
By mistake once I saved a filter search case with no name, first it gets saved with null plus it took my osticket portal down. [ this is related to your new advance search release under 1.10

### Steps to Reproduce

1. Click on Agents
2. Click Tab Tickets
3. Click [advanced]
4. Click check "Status"
5. Select Open
6.Click on Save

**Expected behavior:**
Validatión when "Enter a title for the search" is empty

**Actual behavior:** 
Allow save null the name for the search

### Versions

Server Information
osTicket Version	1.8-git (?)  Upgrade — 901e5ea is available
Web Server Software	Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.6.28
MySQL Version	10.1.19
PHP Version	5.6.28

OS Version: Windows 10
Browser: Chrome

**Comment by rayfoss** [comment]
I couldn't get it to take my portal down... regardless, I can reproduce the wierdness. on 1.10
![screenshot from 2016-12-29 15-44-58](https://cloud.githubusercontent.com/assets/876076/21555459/f653c552-cddd-11e6-9a1d-9df8a3b4bccf.png)
