### ISSUE TITLE
Attachment is not being sent when attaching to "Issue details" field

### ISSUE THREAD

**Issue by DonatelloNguyen** [osTicket/osTicket#2800]
Reproduction Step:
- Go to Ticket > Create Ticket
- Select existing user
- Prefill out the required form.  
- Upload an attachment in "Issue Details" wysiwyg
- Send message

Expected:
- Received attachment from recipient's email
- Attachment appears in the thread

Actual:
- Did not receive attachment from recipient's email
- Attachment appears in the thread.

**Comment by ntozier** [comment]
Version of osTicket?

This is how 1.9.x and lower works and is the expected behavior.

**Comment by greezybacon** [comment]
In version v1.10, you can add `%{message.files}` to the email template of choice and the files will be attached

**Comment by DonatelloNguyen** [comment]
Thanks for the quick reply.

I got this from v 1.9.12.  If this is the expected behavior, then this is a confusing UX design.  I'd expect at least a warning that the attachment will not be in the email for this particular field.

**Comment by greezybacon** [comment]
> I got this from v 1.9.12. If this is the expected behavior, then this is a confusing UX design. I'd expect at least a warning that the attachment will not be in the email for this particular field.

Perhaps, but I think this is an expectation issue. The email sent from the system after completing a new ticket is a confirmation and contains a link to the online ticket. The attachments are available online and are not intended to be brokered via email. In fact, many email systems have significant restrictions on the number, size, type, and content of attachments. osTicket has separate settings for those, agnostic of the email system backend. It makes more sense to keep the attachments in the ticketing system.

Furthermore, as a user, I would find it really odd if I visited a site to file a trouble ticket and added several attachments from my computer (since it's my request), and afterwards, I receive an email with all my attachments included again. Such would just be chewing up space in my inbox because I would already have access to the attachments. And, supposing I did not, I could access them via the link in the email received to the online ticket.

The only place this makes sense (to me) is when sending the new ticket notification to collaborators when creating a new ticket on the web interface, which is currently not possible.
