### ISSUE TITLE
Feature: Asset Management

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#2814]
I would love to see an Asset Management module built for osticket so that we can manage our devices.

**Comment by ntozier** [comment]
?

**Comment by jdelhome3578** [comment]
I use osticket in my it dept and would like to also manage my assets within osticket to see problem assets.

**Comment by greezybacon** [comment]
There is lightweight management already. You can create a "Custom List" and define properties for the list items. So you could create a "Server" or "Laptop" list with corresponding properties. Then you can add a selection to a form which would allow associating with tickets, tasks, users, and organizations. The things that are missing is associating a ticket with a list item, like a Laptop, rather than a user.
