### ISSUE TITLE
Cant removed Assigned Team in 1.10rc2

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2893]
I have a few tickets I can changed the assigned user but the "team" stays there needs to be a way to removed from the interface recently I had to change it in the database.

**Comment by greezybacon** [comment]
Is this new to v1.10? What was the interface previously to unassign a team? What should the interface be?

**Comment by ntozier** [comment]
@greezybacon I was of the opinion that "removing an assigned team" was not an option in the UI at all.

**Comment by Chefkeks** [comment]
If I am not mistaken I guess you're wrong @ntozier, since in 1.9.x a department manager could unassign an agent (and I guess a team too) from a ticket (via the "more" options menu), but not a normal department member - so it's a role/permission thing.

I currently really don't know if that is still so in 1.10 (hadn't had time really to test since rc2 release...) but if it's so I think it would make sense to extend the roles to include that there since often folks don't notice the differences (in the "more" options menu) between being a department manager and just a department member.

**Comment by philbertphotos** [comment]
I can add a team via the UI or by a filter ... but it cannot removed via the UI. Even when I reassign a new agent the "team" stays there.

The logic needs to change one would assume if you assigned that it would remove the "team" automatically not add the assigned user + the team

**Comment by ntozier** [comment]
We don't use "department manager"'s [its a fake account that is an email distribution group] so that would explain why I have never seen a way to un-assign a team.

assigning an agent does not un-assign a team.  It would un-assign the agent that had it before.

assigning a department should un-assign a team.  It would un-assign the team or department that had it previously.

**Comment by Chefkeks** [comment]
> We don't use "department manager"'s [its a fake account that is an email distribution group] so that would explain why I have never seen a way to un-assign a team.


That's why I suggested to move that maybe from department manager specific permission to the new role based permission model. Hope @greezybacon agrees :)

**Comment by philbertphotos** [comment]
We assign Departments automatically and there is usually no need to transfer a ticket twice just to remove a team.

"agent1/Team Name"
If I change to an agent that is not on the team say "agent14" it would now be
"agent14/Team Name"
So I just open my nifty Aminer and edit the database directly.
