### ISSUE TITLE
Time Reporting

### ISSUE THREAD

**Issue by tuudik** [osTicket/osTicket#2962]
Hi!

In new version of osTicket (develop-next), is there also Time Reporting per client?
I think it would be very nice feature, so it would be possible to create bills to client, accordingly how many work hours was used.

**Comment by ntozier** [comment]
No.

The time reporting mod here on github is a mod that was written by a community member.  It has not been updated for a version that hasn't actually been released.

**Comment by robintoy** [comment]
I have now done this and submitted a pull
https://github.com/osTicket/osTicket/pull/3231

Sorry it took me a while, but v1.10.x is very different!
Please be warned that this is based on develop-next which is v1.10-rc3 and should not be used in production due to many errors.

If you want a version for v1.10-rc2 which is a lot more stable please download this version
https://github.com/StrobeTechnologiesLtd/osTicket-1.8/pull/5

**Comment by robintoy** [comment]
also @tuudik this is not really an issue for the good folks of osTicket to solve and really should be posted in the community forums found here
http://osticket.com/forum/categories

To allow the guys to focus on this great system can you close this issue?

**Comment by tuudik** [comment]
Sure:)
