### ISSUE TITLE
Can't edit Task Due Date once its created.

### ISSUE THREAD

**Issue by Mike-Benoit** [osTicket/osTicket#2994]
In addition to the due date not being saved when a new task is created (#2799, #2547, ...), once the task is created, there doesn't appear to be any place to edit the due date, department, etc... 

You can just edit the task title and description, that appears to be all.

This is in the 'develop' branch.

**Comment by simonnzg** [comment]
I've noticed that. I naturally assumed this is a feature that will come along in due time, although it's definitely a feature I'd like to see.

**Comment by markus4000** [comment]
Bug still not fixed. I can't edit the due date in the current 1.10dev #3399

**Comment by jlar0che** [comment]
I'm having the same problem in version v1.10.1 (9ae093d). 
Specifically, the edit feature works for the Title and Internal Note for an already existing Task, but if I try to edit a post within an existing task I get a blank popup box. 

I am certain this is not due to the infamous blank popup issue because all my other popup windows work in osTicket - just not for posts within Tasks.
![editing issue - 1](https://user-images.githubusercontent.com/1959495/30965011-0325e484-a454-11e7-8392-12289597916f.jpg)
![editing issue - 2](https://user-images.githubusercontent.com/1959495/30965010-0314fa48-a454-11e7-8201-50212bc83eac.jpg)
