### ISSUE TITLE
new ticket from Agent has empty internal note / notification is sent for new internal note

### ISSUE THREAD

**Issue by RicKro** [osTicket/osTicket#3028]
We have installed latest 1.10 RC2.

When creating tickets through agent site the new created ticket gets an empty internal note ( we never enter an internal note when cdreating new ticket). The E-Mail which is usually sent on new ticket assignment now dont gets sent, instead there is sent the new internal activity alert with the *\* (empty) in the email. Hope I gave all neccessary informations, if not I will update if you let me know.

**Comment by robintoy** [comment]
Hi @RicKro 
I have seen this issue on the following version of osTicket: -

- v1.9.11
- v1.9.12
- v1.9.13
- v1.10-rc2

We only experience the issue when using Microsoft Internet Explorer, swapping to Mozilla FireFox or Google Chrome solved the issue for me and my team.

I know this is not a perfect answer or a solution but I do not think the issue is with osTicket, maybe @protich or @greezybacon feel differently though.
