### ISSUE TITLE
Forwarded Tickets

### ISSUE THREAD

**Issue by bwhatley87** [osTicket/osTicket#3032]
In our department (as I'm sure with most) we have an issue with people emailing our techs directly.

They then have to forward it into the system and go modify the user from themselves to the original user.

Secondly, the original user then misses out on the autoresponse with the ticket details, so we have a canned response saved to send them.

Is there any way we can automatically parse the "forwarded" information and generate a new ticket from the original user as opposed to the forwarding tech.

Of course, this should only work when an agent sends the forwarded email.

**Comment by ntozier** [comment]
You can get around this really easily... but not in osTicket.
Just have your techs add the mailbox for the ticket email to their client.
Drag the email from their inbox to the ticket inbox. Presto-chang-o.
Problem solved.

**Comment by kest874** [comment]
Works fine, never thought of doing this.

**Comment by clonemeagain** [comment]
I do a lot of inbound rewriting.. mostly because I don't want agents accessing the inboxes live*.. This is how I get around the forwarded email's issue.

Basically, in `include/class.mailfetch.php`,  modify createTicket($mid) (around line [633](https://github.com/osTicket/osTicket/blob/master/include/class.mailfetch.php#L633)) so you can rewrite things with something like:
```php

if (preg_match('/^Fwd: /i', $mailinfo['subject'])){
  $matchable_body = html_entity_decode(Format::stripEmptyLines($this->getBody($mid)));
  if(preg_match_all('/From: (.+) <(.*)>/i', $matchable_body, $sender) != false) {
      // Modify the ticket's source to be this person.
      $old_sender = $vars['name'];
      if (isset($sender[2][1]) && $sender[2][0] == $vars['email']) {
          // We got several matches.. assume the first is bad. (This instance, ticket likely more than once.. TODO: Make more elegant!)
          $vars['name'] = $sender[1][1];
          $vars['email'] = $sender[2][1];
  // echo "Rewrote ticket details: $old_sender -> {$vars['name']}\n";
          $vars['message'] = "Ticket modified upon receipt as it was forwarded to us.\n$message_body";
      } elseif (isset($sender[1][0]) && isset($sender[2][0]) && ! isset($sender[2][1])) {
          // Overwrite with the only match we found..
          $vars['name'] = $sender[1][0];
          $vars['email'] = $sender[2][0];
          //echo "Rewrote ticket details: $old_sender -> {$vars['name']}\n";
          $vars['message'] = "Ticket modified upon receipt as it was forwarded to us.\n$message_body";
      }
  }
}
```


I slot my (similar) function in just after: 
```php
$vars['subject']=$mailinfo['subject']?$this->mime_decode($mailinfo['subject']):'[No Subject]';
```

But your code might be different.. YMMV, untested.. maybe I should rewrite it as a plugin or something, so we could add "rewrite fwd" as an admin option.. either way, would still require mods to mailfetch.
Obviously if you aren't comfortable coding, then don't try this at home! (or at work). 
You can comment out the "message" modifications if you don't want them. 

If you are piping mail, this might not work at all (especially if you only modify mailfetch!), only tested with mailfetch.. all other disclaimers etc.. The point is, it's possible.

*: I use a lot of aliases, so messages to finance@ are in the same inbox as customerservice@ etc.. who do you give access to? none of the above, they all use tickets. Some staff don't even have company email address, they just get tickets assigned to them using filters. :-)
