### ISSUE TITLE
Items of lists are not handled correctly (1.10-RC2)

### ISSUE THREAD

**Issue by rbukovansky** [osTicket/osTicket#3037]
Hello devs of osTicket,
when I try to delete/disable any prepopulated item from list Ticket Statuses, item is not deleted/disabled. Renaming of item doesn't work either.

Could you please take a look?

Thanks.

Regards,
Richard Bukovansky

**Comment by ntozier** [comment]
screen shot?
which ones are you trying to disable/delete?  Some [read as most] are NOT mutable.

**Comment by rbukovansky** [comment]
Here is one.

But that's probably something I'm not allowed to do in osTicket.

![osticket-ticketstatuses-action](https://cloud.githubusercontent.com/assets/1004491/14532744/66c9a7ea-0262-11e6-8ffb-ccc40a36179b.png)

**Comment by rbukovansky** [comment]
I think, osTicket should allow completely rebuild this list from scratch as far as correct State is set to the item of this list.

**Comment by ntozier** [comment]
The UI used to show you which ones you could and could not delete, etc.  This screen shot of 1.9.x should clear that up for you.

![status](https://cloud.githubusercontent.com/assets/1315768/14533334/aa1e3b8a-0232-11e6-8999-fb088250acfa.png)

Open, Resolved, Closed, Archived, and Deleted are required statuses and cannot be changed.
You can however disable Resolved.

**Comment by rbukovansky** [comment]
Well, 1.10-RC2 allowed me to delete Resolved status. Can we get back those 

But as I said earlier, it should allow me to rebuild this list to my liking as far as I correctly setup the State of them. But maybe it's just me...

**Comment by ntozier** [comment]
"it should allow me to rebuild this list to my liking"
I kindly disagree, and here's why.  If you have this:
id 1, Open
id 2, Resolved
id 3, Closed
id 4, Pending

And you decide that you want your list to be.
id 1, Closed
id 2, Open
id 3, Pending

Since the Ticket's status is stored as a number (the id specifically) instantly the following would happen:
- Every single ticket that used to be status Closed (3) is now Pending (3).
- Every single ticket that used to be status Resolved (2) is now Open (2).
- Everything ticket that used to be status Open (1) is now Closed (1).

Can you say disastrous?

Furthermore every custom mod written that uses the default id's for Open, Closed, etc would all be broken (albeit they could be fixed by adding a DB query). I think that this would also require a re-write of the language packs which I believe store the translation for the statuses (I could be wrong about this).

I do agree it would be nice to have the ability that you mention. Mmaybe some sort of mapping could be done to allow the ui to "re-map" the values, but its not a simple change and would necessitate a lot of re-writing on the already beleaguered devs.

**Comment by rbukovansky** [comment]
The last paragraph is what I'm looking for with this report...
