### ISSUE TITLE
OsTicket 1.8-git

### ISSUE THREAD

**Issue by PaulBog** [osTicket/osTicket#3099]
Our site going offline for a while...almost every day between 5.30 and 6.00 pm IST and resuming automatically after 1 or 2 hrs...what could be the problem?

**Comment by ntozier** [comment]
What version of osTicket?  This does not sound like anything that would have to do with osTicket.  I would direct you to investigate at your server level.  Such as:
Are you running any updates at that time on the server?
scheduled maint?
scheduled backups?
etc.

**Comment by PaulBog** [comment]
Thank you ntozier for this reply.

I'm using osTicket 1.8-git ( as it shows at scp dashboard) for sure. Sure I
will see at server level about schduled maint and backups!

our site going offline for a while has anything to do with: something like
images saving in database itself? our client who is using the site uploads
a lot of pictures (jpgs) everyday.

Thanks again...
Paul
------

**Comment by ntozier** [comment]
You should download and install osTicket from the osticket.com/download site.

**Comment by PaulBog** [comment]
Thank you ntozier, i'm repeating same questiong again: our site going offline for a while has anything to do with: something like images saving in database itself? our client who is using the site uploads
a lot of pictures (jpgs) everyday.  Please help.

osTicket was downloaded from osticket.com/download site.

**Comment by ntozier** [comment]
If you downloaded and installed from osticket.com/download then there your version number is not 1.8/git.  My point is no one can answer your question with out knowing what version you are actually running.  You could actually be running a 1.8 version, where 1.9 is current.  We would also need a lot more information to judge if it was saving images to the DB (such as: how many is 'a lot', what your system specs are, how big your db is, etc.) Since you say this happens at a specific time of day I find it hard to believe that this has anything to do with osTicket unless the same user logs in ever day and does this between those hours.

**Comment by Hannibal226** [comment]
@PaulBog 
Beside the thing @ntozier mentioned, a stupid question:
Maybe a backup job running while this time?
- webserver stop
- every day
- 1-2 hours
...listen like

So if yes, you should check the configuration of the job.

PS: Anyway you should update to latest official (atm 1.9.12).

CHEERS!

**Comment by PaulBog** [comment]
Thank you ntozier:

I will get back to you with more information...

Paul
------
