### ISSUE TITLE
Search emails and open a new tickets OsTicket 1.10 RC2

### ISSUE THREAD

**Issue by suportgc** [osTicket/osTicket#3176]
Hello good day.
How to configure osTicket to get emails and open new tickets even when I'm offline ?

I saw something about a cron job , however, do not know how to do.

Can someone help me ?

I use a Hostgator hosting .
System installed on a CentOS Linux .
OsTicket 1.10 RC2

**Comment by ntozier** [comment]
You would probably want to open a thread on the support forums instead of here as this is a setup issue, not a coding issue.

I would recommend that you read the following:
http://osticket.com/wiki/Email_settings
http://osticket.com/wiki/POP3/IMAP_Setting_Guide

You would want to consult your webhost support for how to setup a cron job on their system.  If they do not allow such things (I'm pretty sure that Host Gator does) then you would want to investigate using a third party cron service.  

Once you have moved this thread to the forums if you still need assistance please close this issue report.

**Comment by suportgc** [comment]
Thanks for the answer "ntozier"

I will contact my provider .
