### ISSUE TITLE
Reply to tasks in 1.0-RC2 generates a new ticket

### ISSUE THREAD

**Issue by haraldhh** [osTicket/osTicket#3188]
If a task is created (under a ticket), and a recipient is added to that task, replies to that task create a new ticket.

Expected result would be that the reply to the task would be identifed and appended to the task.

**Comment by greezybacon** [comment]
You have some email issues. Are you including the ticket number in the subject line? `#%{task.number}`?

**Comment by nunoxyz** [comment]
I'm having the same problem, the task reply always creates a new Ticket, I have the [#%{task.number}] in header the email reply is like: Re: Tarefa - [#WO00000051]
Version: v1.10 (901e5ea)

**Comment by ntozier** [comment]
@nunoxyz you are using custom ticket numbers, I believe that the problem is with that.

**Comment by nunoxyz** [comment]
Noticed one thing: even with all options selected in "task creation", but if I add one comment one email is sent, after that email is sent all information is "updated correctly".

**Comment by killerbees19** [comment]
Same problem here… (v1.10.1)

**Comment by xWyatt** [comment]
Has there been any update on this? I noticed the [deprecated] tag attached to this issue which scares me a little; is replying via email to a task going to be deprecated in the future?

Replying to a task via email (without OSTicket opening a new Ticket from the Task response) is functionality we really would like to use. 

We also have the task number in the email subject line by default and we're also on v1.10.1.

**Comment by cole-1** [comment]
How come this is closed? The issue still exists...

**Comment by JediKev** [comment]
@cole-1 

Because this issue is very old and has not been updated in a year. If this is still an issue, please reopen.

I tried testing this with the latest codebase of v1.14.1 and this is no longer an issue. A collaborator can respond to a Task - **New Activity Notice** alert and it threads through the Task correctly and does not open a ticket. All other Task alerts you cannot respond to as clearly stated in the footer:
<img width="941" alt="Screen Shot 2020-01-10 at 08 55 01" src="https://user-images.githubusercontent.com/11823401/72162093-eb079b80-3386-11ea-8bfe-4ed03ddcec37.png">

Cheers.
