### ISSUE TITLE
OSTicket-v1.10-rc.3 Forms 

### ISSUE THREAD

**Issue by suportgc** [osTicket/osTicket#3213]
When upgrading to version RC3 identified that the forms are with an error when selecting the display mode .

As the Print below.

![ost](https://cloud.githubusercontent.com/assets/19677143/16201009/07be58f0-36e6-11e6-98e2-7f6153b14250.png)

**Comment by balojs** [comment]
+1

**Comment by suportgc** [comment]
I tried this method , however, without suesso

![image](https://cloud.githubusercontent.com/assets/19677143/16201429/b64891fa-36e7-11e6-8914-eaa5bb3494f6.png)



More print
![image](https://cloud.githubusercontent.com/assets/19677143/16201382/705654f2-36e7-11e6-983a-818a92a66fc8.png)

**Comment by greezybacon** [comment]
@suportgc sorry, I'm not really understanding what the problem is.

**Comment by suportgc** [comment]
Hi @greezybacon 
Sorry , I do not have detailed very well my problem.

The error is in the tab "Visualização".

The option to modify the optional property , mandatory , internal 
this locked.

by clicking the type > configuration.
The option Require entry to close a thread this blank.

**Comment by greezybacon** [comment]
So the error is that, some checkboxes cannot be changed in the popup, and the text for the label of 'Require entry to close a thread' is blank? What is the English translation of `Assunto`?

**Comment by suportgc** [comment]
Hi @greezybacon 

I put the system in default language .

follows new prints

![image](https://cloud.githubusercontent.com/assets/19677143/16202923/4378d656-36ee-11e6-9d5d-a903af066299.png)


![image](https://cloud.githubusercontent.com/assets/19677143/16202949/5be7794a-36ee-11e6-906f-cd2bf867b049.png)

**Comment by greezybacon** [comment]
@suportgc if I could make a general suggestion for posting issues. Please post screenshots that all correlate to the same issue. That is, the field listing and the popup dialog should be from the same page. And keep your shots consistent -- especially when changing languages. For instance, I think the top listing you posted is for your user information ("Contact Information" in English, but you asked a question about the "Ticket Details" form, then you posted more screenshots from your "Task Details" form.

Anyway, what I think you're asking is why can the "Visible" and "Required" settings not be changed from some fields. The answer is because some fields are used internally and, for historical reasons, are required for the system to function properly. For instance, the "subject" is required for email processing.

**Comment by suportgc** [comment]
@greezybacon 
Thanks for the feedback .
I'm new here.

The prints were examples .
The error I 'm getting.
It is that not being able to change the field visibility.

The choice of option is displayed only to create new fields.

Thank you and sorry for the inconvenience.

**Comment by ntozier** [comment]
"The answer is because some fields are used internally and, for historical reasons, are required for the system to function properly. For instance, the "subject" is required for email processing." @greezybacon

**Comment by greezybacon** [comment]
@suportgc on the help topic page, you can disable the field from the web interface. That might be what you are looking for.

**Comment by suportgc** [comment]
Thanks for the answers .
issue resolved
