### ISSUE TITLE
dashboard 

### ISSUE THREAD

**Issue by samogon13** [osTicket/osTicket#3313]
dashboard no statistic 
![sk](https://cloud.githubusercontent.com/assets/20986927/17619562/b9bd86e4-608e-11e6-8795-2a1217e2049a.PNG)

**Comment by ntozier** [comment]
Does it work in English?

**Comment by samogon13** [comment]
no

**Comment by ntozier** [comment]
Are you actually running osTicket?
or are you running the version from osticket.de.com?

**Comment by samogon13** [comment]
osTicket-1.8-feature-custom-queues

**Comment by samogon13** [comment]
[demo](http://xn--c1aafaqasphcb7b1b.xn--p1ai/sapport) 
login: admindemo pass:admindemo

**Comment by ntozier** [comment]
You did not answer the questions.

**Comment by samogon13** [comment]
https://github.com/osTicket/osTicket/pull/2577

**Comment by ntozier** [comment]
Linking to a feature commit, does not answer the questions either.

**Comment by wfoster** [comment]
Am i correct in assuming that you have a 1.10RC3 configured and trying to apply a 1.8x version MOD from #2577 ?

**Comment by wfoster** [comment]
I configured the setup you have and experience the same issue on Windows and Linux. I think that you should post in #2577 so that Jared can be aware of the issue. The version you have installed is specifically released for testing. It is basically two versions away from being released as far as I can tell.
