### ISSUE TITLE
OSTicket Install script not completing | Unable to access Admin Panel

### ISSUE THREAD

**Issue by BobOfTheFuture** [osTicket/osTicket#3344]
Purpose: 
- Installing OSticket on Windows 10, Sever 2012 or Ubuntu in an educational environment in order to keep track of technical issues.

Install Prerequisites: 
- OS: Windows 10 Home x64
- Installed Apache, MySQL and PHP using XAMPP 5.5.38  

Hello everyone, 

I am having issues installing OSticket. I fill out the Basic Installation form and press install now but I am not taken to the admin panel for further configuration. During the install I have had phpMyAdmin open to confirm that the install script is adding tables to the database and it absolutely is! I've tried filling out the Basic Installation form again and attempting the install but I receive an error that states: "We have a problem - another installation with same table prefix exists!". 

Please let me know if any of you have any idea how I may get past this issue. I am open to all suggestions and solutions.

**Comment by ntozier** [comment]
My advice: Ditch XAMPP, and install the pieces yourself (Apache2, Mysql/MariaDB, PHP 5.6).
As a side note the installer does not take you to the admin panel when it completes.
It takes you to a page that says that it finished, and gives you more information on how to access the Agent panel or the User panel. If you run the installer more than once yes it tells you that error... and it sounds like it is correct to.  The piece that you appear to have left out.. is what happens when you click the install button.
