### ISSUE TITLE
Osticket Mail(imap) configuration issue

### ISSUE THREAD

**Issue by sampathmende** [osTicket/osTicket#3363]
Dear Team,

While configuring imap email I am getting below issue .Pls help solving the issue.
**Getting No such Host as imap.xyz.in**
Pls find the attachment for configuration information
![capture](https://cloud.githubusercontent.com/assets/22193461/18509540/c0c48e3e-7a96-11e6-9a58-69c50a48250e.PNG)
![issue](https://cloud.githubusercontent.com/assets/22193461/18509564/d998914e-7a96-11e6-8f46-ad024e54e701.PNG)

Thanks,
Sampath

**Comment by ntozier** [comment]
Sounds like a DNS issue to me.

**Comment by sampathmende** [comment]
Dear ntozier ,
DNS issue means it's not able to connect to server because of internet  connection?? Can you explain clearly?
Thanks

**Comment by robintoy** [comment]
Hi @sampathmende 

What @ntozier is trying to say is that the DNS (Internet Phone book) does not contain an entry for imap.cdac.in

This can be for two reasons: -
1. The DNS server you are using does not know the entry and is not asking its neighboring DNS server
2. The address does not really exist.

Doing a quick check on the internet (see link http://mxtoolbox.com/SuperTool.aspx?action=a%3aimap.cdac.in&run=networktools), I can see the address does exist meaning the issue is reason 1

**Comment by ntozier** [comment]
When the software tries to connect to the server imap.cdac.in it returns host doesn't exist.  The only reasons I can think of why a host "wouldn't exist" is that your DNS servers do not have an IP address for it... or maybe a firewall blocking access to said host.

**Comment by rayfoss** [comment]
@sampathmende did you figure this out? if not restart the httpd/apache server and try again, let us know if that fixes it
