### ISSUE TITLE
RC3- Ticket Subject Link Data

### ISSUE THREAD

**Issue by bwhatley87** [osTicket/osTicket#3364]
Somewhere between RC2 and RC3 something changed in the ticket table on the subject column.

If you hover over the ticket number, it registers as a link to the web browser, you can right click on it (open in new tab, etc).

The subject line is a link, but doesn't have the properties of a link... If you right click on it, it doesn't register as a link, meaning you can't use it to open a new tab.

**Comment by JamesWaldock** [comment]
I'm not sure what the rationale was behind changing the subject line to a <DIV>, but I agree that the side-effects are undesirable. My workflow typically involves opening a number of tickets in tabs, which I'd do by middle-clicking their subject. This is no longer possible due to the change (at least in Firefox 49 and IE11) and I'd like to see it reverted unless there's a strong case for keeping it.
