### ISSUE TITLE
1.9.14 multiple attachment from scp

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#3376]
Hi, if an operator send an answer in a ticket, attaching 5 .xls files (the sum of the size is below the size limit ), or other file format, only some of them is attached (for example 4 or 3).

**Comment by cervedgroup** [comment]
i've done variuos try .. 
the problem happen only sometimes, i'm trying to find if there is a relationship with the filenames

**Comment by walcew** [comment]
I have the same problem here, trying to debug, scaning LOGs and no success...

**Comment by rayfoss** [comment]
I'm not having the same issue on 1.10, I tried sending 18 different files, no problem. Note, if three files are named differently but have the same hash, only one will send.

If you're still having the issue, try working through our issue template to help us reproduce it. Thanks!
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
