### ISSUE TITLE
1.10 Status Request

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#3385]
@protich @greezybacon What is the status of osTicket 1.10?

**Comment by ArthurBorsboom** [comment]
I noticed there hasn't been any commit since July.
Is there a development issue, maybe resource issue?

Can we (user/developers) help somehow?
Does osTicket need to be forked?

**Comment by Aka4Code** [comment]
I think there is no sense asking devs, see here what they will say if you try: https://github.com/osTicket/osTicket/issues/2664
They do not care about users, and do not want our help, so best IMO choose other solution like Redmine.
OsTicket is nice, but since year it looks like dead, no difference what they say.

**Comment by ArthurBorsboom** [comment]
I really like osTicket for its simplicity and in the same time offering all the functionality I need.

Is it allowed to create a fork, legally/license wise speaking?

**Comment by Aka4Code** [comment]
Yes, you can fork because it's under GNU GENERAL PUBLIC LICENSE:
https://github.com/osTicket/osTicket/blob/develop/LICENSE.txt
https://stackoverflow.com/questions/4475319/how-to-rebrand-copyright-a-forked-project-gnu-gpl - here is similar question

**Comment by rbukovansky** [comment]
Is @greezybacon AWOL?

**Comment by Aka4Code** [comment]
@rbukovansky It looks that @greezybacon (Jared Hancock) may be no longer working in Enhancesoft company who founded osTicket - see below. It's a shame they can't say a word.

At 29.02.2016:

![image](https://cloud.githubusercontent.com/assets/11789024/19322368/06fe5ac8-90b9-11e6-9f6b-5389f93a50c5.png)

And now:
![image](https://cloud.githubusercontent.com/assets/11789024/19322382/12df590a-90b9-11e6-8d4f-0ea62a7a6e65.png)

**Comment by ArthurBorsboom** [comment]
Hi,

Since there has been no commits or responses since July 2016 on the original osTicket project, I have decided to create a fork.

https://github.com/ArthurBorsboom/osTicket

There are many developers who have created awesome improvements by pull requests, which are eagerly waiting for merging.

This is an attempt to incorporate most pull requests to get create an improved version of osTicket. Hopefully this can later be reintegrated in the original project, or if the original project is dead as a rebranded project.

I am in the process of asking people who have send a Pull Request to resubmit it, to this fork.
Since these are almost 150 PR's and I am doing this in my spare time, this takes a bit of time. :)

If anybody is in for helping (merging, code review, improving, testing), I would love to hear it!

Best regards,
Arthur Borsboom.

**Comment by martin-rueegg** [comment]
As it seems, this project has stalled. As to [this discussion](https://github.com/BristolPound/osTicket/issues/18) a fork ([osTicketFork](https://github.com/osTicketFork/osTicket)) has been created to keep development up.

In the future, a merge back into the original project, a take-over of the original project, or a full-fledged fork may all be an option.

Currently we're just encouraging devs to join our effort to keep this up and running.

2016-10-14, @ArthurBorsboom  and @martin-rueegg

**Comment by kest874** [comment]
@ArthurBorsboom @martin-rueegg  wouldn't mind assisting.

**Comment by rbukovansky** [comment]
@ArthurBorsboom @martin-rueegg Just one thing: you probably also need to create a new translation project on Crowdin...

**Comment by JediKev** [comment]
#3399
