### ISSUE TITLE
1.10RC3 comment

### ISSUE THREAD

**Issue by gitfve** [osTicket/osTicket#3432]
Sorry to say, but GUI (front-end) look wrong or bad in v1.10RC3 compared v1.9.14.
I don't know why there are so many CSS change. When using v1.10RC3 for testing it look totally screwed up compared to my v1.9.14.
Nothing fit nice on the front-end page. If i going to create a new ticket from the front-end the page on my 1.9.14 is about to fit the screen, but in 1.10RC3 there are more like two pages to scroll, too much space and most off the field is placed on new lines... look real bad.

Same problem in the QA front-end section.

I am not ready to skip my 1.9.x over the 1.10RC3.

The ticket editing (back-end) in 1.9.14 in Firefox have a lot of problem, but 1.10RC3 have a lot of the same problem!

*All my testing is done with Firefox (latest 49.0.2 at the moment).

*I know some picture will be nice to attach i will find some to attach. For now i have just updated my text to be more accurate.

Hope for a 1.12 where all this is solved.

**Comment by ntozier** [comment]
You should consider using some screen shots to elaborate and clarify your statements... because I have no idea what you are talking about.  You should also specify what web browsers you have test with and their versions.

1.9.x
![1 9 x](https://cloud.githubusercontent.com/assets/1315768/19808796/73027a0a-9cf4-11e6-83e9-598514da7138.png)


1.10rc3
![1 10rc3](https://cloud.githubusercontent.com/assets/1315768/19808803/7a4b6d58-9cf4-11e6-9f80-ceade3224c26.png)

**Comment by gitfve** [comment]
You are right, and i have put some more text in. 
What you show is from the back-end and the bact-end is ok. All the problem is in the front-end. I only have Firefox, and will only use Firefox. Maybe not the best, but for me the most safe one.
