### ISSUE TITLE
when creation a Task, agents list is not restricted to department. All the agents are showing

### ISSUE THREAD

**Issue by edukondalugorla** [osTicket/osTicket#3436]
When creating a Task . All the agents are shown even if a specific department is selected. The agent list should be restricted to the department selected only.
 Why all agents list is showing ?

**Comment by markus4000** [comment]
@ntozier , I see you point and it makes sense to me. but:

Scenario:

Agent A is member of Department A
Agent B of department B

Agent A is assigned to a TICKET and he makes some tasks for different other agents. Also one for Agent B.

Why shouldn't he assign the ticket to Department B too? 
 => Because if he does, he's loosing the Access to the TASK and cant see the Progress.

How can Agent B's Boss see that Agent B has a Task from Department A ?

If agent A choose the agent B and department B, how can agent A still access to the task? because Agent A is owner of the ticket, he wants to know what's going on in the task.

From my point of view:
- the owner of the ticket should have access to all the tasks of the ticket.
- the department manager should have access to all the tasks of the members of the department.

What do you think ?

Another point: once the task is generated and someone wants to reassign it, there are only the department-members available. but you wrote assignment outside of the department should be possible. so the idea is not clear to me.

**Comment by markus4000** [comment]
i wouldn t close this issue. it still an issue for me

**Comment by zakoleo** [comment]
**Its an issue for me also.**
It doesn't make sens for my case, to create a task, and not be able to follow up.
Ex 1: Agent A is asking agent B from  departement B, to give him an information,
Agent B provide the information in the task as a note, and close the task, 
Agent A, doesn't have the information.
Ex 2: Agent A is asking agent B from  departement B, to give him an information,
Agent B need more information to finish the task, how can he ask agent A ? create another task ? that he can't follow up ?
