### ISSUE TITLE
Language Pack for 1.10

### ISSUE THREAD

**Issue by nilschrishahn** [osTicket/osTicket#3451]
Please update the language packs on the download area, to use these in 1.10
Thanks a lot for your work.

**Comment by JediKev** [comment]
I was able to download/install/use the language packs on my fresh v1.10 install. Try choosing the language and and press 'Save Changes' twice and see if that works. Some times it doesn't catch on the first try.

**Comment by nilschrishahn** [comment]
I can download and install it. But the problem it is not completly translated. I think in the download area it is not for 1.10.
I need language german.
On crowdin I can find the complete translated files. But I need the phar file. Do you know how can I create this file or where I can download the last version?

**Comment by JediKev** [comment]
Ah I see, we will be rebuilding the phar files within a couple of days and update them on our website! Thank you.

**Comment by nilschrishahn** [comment]
OK. Nice to hear this. Is it possible to rebuild by myself the files from crowdin? If yes, how?

**Comment by JediKev** [comment]
I don't believe so. I think you'll just have to wait it out.

**Comment by ntozier** [comment]
I'd also like to point out that the translation feature has **NEVER** been announced as completed. So if you are seeing most things being translated then chances are that's as far as the devs got.  Feel free to report things that are not translating though so that they can check their to do list and see if that one is on it.

**Comment by nilschrishahn** [comment]
I know it is not completed. This is not the Problem. In the 1.10 the folder "Tasks" is new. For this feature the translation is not downloadable. On crowdin, where I would help to translate, I see many translation which would help. But to download the translated files it is not working. For this ask to rebuild the phar file. And it could help to know how to handle the translated files of crowdin, to try and see in a running system and it could help me and other to translate it completly.

**Comment by Chefkeks** [comment]
@JediKev
Due to the fact that I'm currently on vacation in New York City and next week in Miami :) I haven't tried yet to rebuild the phar from the files on crowdin, but unless there have been major changes in the new version 1.10 and the phar files, I think it shall be possible - at least in 1.9.x it was possible to update the phar files with the latest files from crowdin, which I did sometimes for our internally hosted osTicket and I guess I even posted a little how-to over at the osTicket forum some (long) time ago ;)

Anyway great to hear 1.10 was finally released, which I accidentally found out yesterday :D (vacation has priority ;) ) and also that the 1.10 translation files will be available soon.

Btw. Could you tell who'll take over Jared's part of translation related stuff and if there are any plans to make it possible for proofreaders (or let's say managers) of a language to update the phar on their own? Asking since I'm feeling responsible for the German translation and sometimes it'd be great to trigger phar creation apart from the official osTicket releases. Personally I think this could be a win-win for both - proofreaders and osTicket customers using the phar files. 

My idea is that some or all proofreaders of a language which are trustworthy enough are allowed to update the phar of a language (maybe limited to x updates per month or week). I know that I have no clue how easy or hard it is to build and release the phar files on osTicket.com currently, but when this process could be done automatically I'm sure it'll be a huge advantage for proofreaders, customers and hopefully you guys too :)

Cheers from NY :D
Michael

PS: Sorry for getting a bit off topic, but I would really appreciate when we could work together on improvements in the translation process and also the translations' itself as in one of my still pending pull requests

**Comment by fabioandreteles** [comment]
Hello. It would be great to build on the crowdin files. I'm trying to help on the portuguese language and posted anothger topic with some issues with the current translation file. Thank you again for the great work!

**Comment by JediKev** [comment]
@Chefkeks I'm glad you see vacation has priority and have fun in NY and Miami! I'll definitely ask Peter because that sounds like it would be worth looking into!

**Comment by nilschrishahn** [comment]
@JediKev 
Any news for the compiled translation pack?
Many thanks for your work.

**Comment by markus4000** [comment]
any news?

or is there a way to work with the unphared folder?

**Comment by markus4000** [comment]
does somebody know how to use the translation files as files and not as a phar file?
or does someone know how to phar the files?

**Comment by nilschrishahn** [comment]
I don't know. I have the feeling, it is a big secret to get the new phar file :-) I can not understand, too, why nobody could provide the actual phar file. On crowdin, it is 99% approved. And you can download all the files. But you can not use these files. I need a phar file. Maybe anybody can explain how to phar.

**Comment by mfelber** [comment]
It is not necessary to use phar files. Osticket can also handle the extracted content of the phar files.
The extracted content should be in a folder below the i18 folder.
The folder name for the german language pack is for example „de“, I guess you can find the definition for the folder name of other languages in the langs.php.

Phar files are only php archives, you could write your own script (https://secure.php.net/manual/de/phar.extractto.php)
or use this script (http://empir.sourceforge.net) or use an online service (http://unphar.com) to extract it to a normal zip archive. The created zip-file you only have to unzip.

You can’t download the actual 1.10 files from crowdin in one zip file (only the latest build, which doesn’t include the latest translations yet). You can only download the newest translations file for file (via the three dots button on the right side).
The messages.po(t) file must be converted after the download (for example with https://poedit.net.) to a mo-file. After that you can use the class.translation.php to create a messages.mo.php file like I described it here (https://github.com/osTicket/osTicket/issues/3101).

After that I use the last official download of a language pack from osticket.com unphar it and copy the new translated content for 1.10 to the designated locations of the language pack folder (overwrite existing files).
On crowdin you can see which file has to be in which folder.
This file you could use under the i18 folder. As far as I know you could only use this file after the installation of 1.10. I guess there are some changes necessary for using it during the installation process (for example in order to have translated email templates).

This is the only method I know that works. But it doesn’t really make fun ;-)
Maybe you wait better till the official builds are out..

**Comment by markus4000** [comment]
you're right. it works :+1:  thank you!

**Comment by mfelber** [comment]
Glad to hear that..

**Comment by nilschrishahn** [comment]
Any news when we can get the final or a preliminary phar file for the german language?

**Comment by rayfoss** [comment]
new language packs are up as of Jan 13.

**Comment by Af0x** [comment]
where can I find them? official homepage (http://osticket.com/download) says for all the language packs: 

> Last Built March, 28th, 2016

**Comment by rayfoss** [comment]
@Af0x  Ignore the dates on the website... the files are actually new, doing `phar extract -f` and taking a look at the MANIFEST.php will tell you the real date they were updated.

**Comment by Af0x** [comment]
ok, thank you :)
