### ISSUE TITLE
Cron / rCron wont collect mail - support.xxxx.com? (Solved)

### ISSUE THREAD

**Issue by gitfve** [osTicket/osTicket#347]
Hi

osticket 1.8.0.1 (Git)

1) OK
On my imap mail server there are mail.
I log in to osticket
osticket collect and move the mail, OK.
Then a new mail hit the imap server, after 5 minutes (poll time) it show up in osticket.

2) Error
Email Polling:  Enable POP/IMAP polling     Poll on auto-cron  -> Both are enabled!
When running rcron with API key nothing happened!
- Is this working in 1.8.0.1?
  *Is there some advanced log to search in?

*******Update 211213

My installation is: support.xxxx.com -> HTTP/1.1 404 Not Found
Another installation is: xxx.com/support -> And it seen to work

***The problem is in ".htaccess" but I cant figure it out?

***The problem was: My hoster have now activated "suPHP" and all is NICE and running!

**Comment by webermax** [comment]
I suggest to use sth. like the following instead of calling "rcron.php" if it is hosted next to osticket.

`<?php shell_exec('/usr/bin/php55 -q /full/path/to/api/cron.php');`

following the osticket wiki is quite confusing and what i've read so far most people using rcron.php are doing it "from behind through the chest in to the eye".

**Comment by ntozier** [comment]
@webermax you commented on a issue that was closed in Dec 2013.  
I am of the understanding that many webhosts disable shell_exec.
You should really just use cron as intended,

**Comment by webermax** [comment]
@ntozier Sure, this won't work in "safemode". But many webhosts do not offer crontab, either.
