### ISSUE TITLE
Bug : Cron don't work on 1and1 server in osticket v 1.10 and Bug DB Error #1054

### ISSUE THREAD

**Issue by SynchronicHossein** [osTicket/osTicket#3510]
Hello @greezybacon,

I have an issue with osticket v1.10, I can not run the "cron.php" for creating tickets from emails. I managed to run a version v1.9 on a local server, I have the tickets created from the emails.

I try to duplicate the same thing on the 1and1 server but nothing works correctly.

Could you help me please ? What information do you need?

Thank you
![db1054](https://cloud.githubusercontent.com/assets/23450682/20341173/50946532-abe5-11e6-81fd-6e2de4b5ebc3.jpg)
![information](https://cloud.githubusercontent.com/assets/23450682/20341174/509b104e-abe5-11e6-8102-97febd7cb8f6.PNG)

**Comment by ntozier** [comment]
If you can make it work on the local host, and have replicated the settings on the remote host then it stands to reason that your problem is with something the remote host is doing.  Many folks have mentioned having issues using 1and1 on the forums.  Your screen shot does not convey the full error.  Please cut and paste the whole error so that someone can look into what the error says.
