### ISSUE TITLE
Loading windows appears for a long time during closing and opening of Task.  (Need to Refresh the Page)

### ISSUE THREAD

**Issue by blhf** [osTicket/osTicket#3609]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch? No
* [ ] Do you have any errors in the PHP error log, or javascript console? No
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)? Yes
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? Yes

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Loading windows appears for a long time during closing and opening of Task. 

### Steps to Reproduce

1. Task>View Open Task>Select Task>Close Task>Loading Page Appears>Need to refresh to get the updates Task Status.

**Expected behavior:** Loading Page should not stay in screen for very long time

**Actual behavior:** Loading Page stays need to refresh the browser
### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

![image](https://cloud.githubusercontent.com/assets/10716429/21840143/d12d7d16-d816-11e6-814e-b323b9da0618.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

Windows 7. Google Chrome. FireFox. Edge

**Comment by fdellwing** [comment]
Can not reproduce that with my installation. Tried it on the tasks overview and on the task details.

Ubuntu 14.05, Firefox 50.1.0

![ost4](https://cloud.githubusercontent.com/assets/22813377/21842029/39f3442a-d7e5-11e6-8919-3267fa53c336.png)
Zend Cache is not available for PHP 5.45, so ignore the warning ;)

**Comment by ntozier** [comment]
You are the only person that I can think of who has reported slowness on 1.10 either here or the forums.
System hardware specs of your windows 7 box?
Do you have other things running on this box?
Are you accessing it via localhost or network?

**Comment by blhf** [comment]
This is the hardware specs:
[image: Inline images 1]

Accessing it via localhost.

Additional Information:

*The task is inside the ticket. The issue happens when we close or post an
update in this form.
[image: Inline images 1]

[image: Inline images 2]

But when we view the task:
[image: Inline images 3]

[image: Inline images 4]

[image: Inline images 5]

and close is from there. The issue is not happening. I think there's an
issue with ticket/task form? What do you think guys?

**Comment by fdellwing** [comment]
Well I can confirm an problem in this view, but not your problem. Please provide us with the images.

**Comment by ntozier** [comment]
Looks like you forgot to include the images.
Maybe you would be better suited asking your question on the Forums since this is not reproducible with the instructions that you have provided.

"Task>View Open Task>Select Task>Close Task>Loading Page Appears>Need to refresh to get the updates Task Status."

Breaks at Select Task.  One cannot Select a task that one is viewing.  I presume that you mean:
Click on the Tasks tab.
Click the check box to the right of any open task.
Click on Change Status (top right menu bar)
Select Close.
Which results in the "Close Selected Task" dialog screen.

**Comment by blhf** [comment]
This is the hardware specs:
![image](https://cloud.githubusercontent.com/assets/10716429/21915715/ca32929c-d976-11e6-9e6b-0cb6e492e8f8.png)


Accessing it via localhost.

Additional Information:

*The task is inside the ticket. The issue happens when we close or post an
update in this form.
![image](https://cloud.githubusercontent.com/assets/10716429/21915736/f1592a5c-d976-11e6-9fd8-bcdf4f0c75ba.png)

But when we view the task:
![image](https://cloud.githubusercontent.com/assets/10716429/21915748/03df8a54-d977-11e6-930f-f9b7377f0452.png)

and close is from there. The issue is not happening. I think there's an
issue with ticket/task form? What do you think guys?

--resending with pictures. Thank you

**Comment by fdellwing** [comment]
Can confirm this now.

Trying to describe it a bit better:

If you close the status with the action menu, all works fine.

But if you post an update and post it, the update gets posted, the status gets changed but the loading circle does not go away afterwards.

This has nothing to do with changing the status. The problem is the posting of an update. Can someone  (@rayfoss) please rename the ticket and look into it?

**Comment by blhf** [comment]
@fdellwing  yes. I think that is more specific. Thank you for clarifying this.

**Comment by blhf** [comment]
@rayfoss  please look into this.. Thank you.

**Comment by blhf** [comment]
Experiencing it on the latest osticket version on the creation of ticket also.
