### ISSUE TITLE
Bug in RegEx Filter

### ISSUE THREAD

**Issue by MishaFrenkman** [osTicket/osTicket#3694]
I think there's a bug in your RegEx Filter code in class.filter.php

The code is 
```
function pregMatchB($subject, $pattern) {
    return preg_match($pattern, $subject);
}
````

but I think the parameters are misplaced.

Shouldn't it be 

```
function pregMatchB($subject, $pattern) {
    return preg_match($subject, $pattern);
}
```

?

I found this after I tried to reject tickets based on a regex. But instead, it rejected the exact negative of the regex.
Regex: ``(.*\..*@company.com)``
Meaning: match email address if it ends with @company.com and contains a dot before that.

In osTicket -> Email : Does not match : "regex" -> action: reject
If I try "Does match" instead, I get the same result.

**Comment by fdellwing** [comment]
http://php.net/manual/de/function.preg-match.php

I dont know WHY it is this way, but `preg_match($pattern, $subject)` is correct.

**Comment by MishaFrenkman** [comment]
Ok so I tested the Regex in plain php and it works just like it should.

```
<?php
	$email1 = "john.doe@company.com"; // Should match
	$email2 = "noname@company.com";  // Should not match
	$email3 = "john.doe@mail.net";  // Should not match
	$email4 = "noname@mail.net";	// Should not match
	
	$pattern = "/(.*\..*@company.com)/ui";
	
	echo preg_match($pattern, $email1) . ";";
	echo preg_match($pattern, $email2) . ";";
	echo preg_match($pattern, $email3) . ";";
	echo preg_match($pattern, $email4) . ";";
	
?>
```

``Output: 1;0;0;0``

But when I try to implement it into the filter, it rejects the tickets that match and passes tickets that do not match. 
Same result, when I use the "Does Match" option, instead of "Does not match"


My config: 
![screen shot 2017-02-16 at 13 43 58](https://cloud.githubusercontent.com/assets/8081364/23021802/0ff2415a-f44e-11e6-80fb-a6ae7a3bdd8e.jpg)


Any Ideas?

Thanks in advance

**Comment by fdellwing** [comment]
I just tried it and this works for me.

![ost14](https://cloud.githubusercontent.com/assets/22813377/23022014/111f84c4-f44f-11e6-84fb-dd2de0310ca8.png)

**Comment by MishaFrenkman** [comment]
And your filteraction is reject?
What is your target? web-tickets or email-tickets?

When I run this filter on email-tickets, all matches get rejected and the ones that don't fit are being  passed.

**Comment by fdellwing** [comment]
We dont use mail tickets. But the reject works by webtickets: `Dieser Helpdesk kann nur von autorisierten Benutzern verwendet werden`

v1.10 (901e5ea) — Aktuell

**Comment by scottycroy** [comment]
I am trying to use the regex filter to only track emails if there is a Ticket ID in the subject line. 
I would like to ignore the other emails, as far is osTicket is concerned. 

I have tried Ticket/Issue Summary - Does Not Match Regex - \[\#\d{7}\] (When I save the settings for the filter it changes the regex field to /\[\#\d{7}\]/iu ) 

The Filter Action is Reject Ticket. 

Execution Order is 1 and Stop processing further on match is checked. 
Target Channel is the Email being polled through IMAP. 

What happens is, it creates a ticket for every email in the inbox. 
What I expect to happen is for it to poll the emails and use the regex to match the contents of the subject line. If it doesn't match a ticket number format in the subject line then, basically disregard the email, or "reject ticket". Otherwise if a match is found then I expect that it either create a new ticket or attach that email content to an existing ticket. 

I am certain I can delve into the code and force this behavior, however, the purpose of me using osTicket is to save me the time of coding the tool myself. 

Please don't bypass the fact that I haven't even looked at the code, and I only installed it today and haven't had any prior experience with it. 

Thanks for any help.
