### ISSUE TITLE
Print function produces garbled data

### ISSUE THREAD

**Issue by Reamis** [osTicket/osTicket#3695]
Printing does not work after i moved the database and website files to an another host. 

Attached a screenshot 
![screenshot_4](https://cloud.githubusercontent.com/assets/1516773/23023665/4ca99a88-f45f-11e6-8b83-b774683184af.png)

**Comment by ntozier** [comment]
I'm unsure why you would be posting this issue report here.  This bug is not reproducible. Clearly you have something configured very differently on your old host compared to the new.  You haven't provided us with any environment details, nor have you provided any version information about the many parts.  You even deleted the issue template instead of answering the questions in it.

**Comment by antriver** [comment]
This is a problem with your web server configuration. You need to set it up to correctly serve pdf files with the mime type application/pdf

**Comment by fdellwing** [comment]
Do you have a ForceType or something like that in you apache config?

**Comment by iHunt101** [comment]
You can setup a new one and dump your database, so your system will adopt the new machine settings.
