### ISSUE TITLE
Client side search issue

### ISSUE THREAD

**Issue by andreadg88** [osTicket/osTicket#3733]
In the last release 1.10 i have a search issue on client side.
The search filter does not work.

I use this release: 
- OsTicket 1.10
- Apache 2.4.6
- Php 5.4.16
- CentOS 7.3.1611

![19d3ed9521280927ba181864ae0724](https://cloud.githubusercontent.com/assets/26273930/23699571/ed51c3bc-03ef-11e7-88c8-6781295441a8.png)

![98c7820ca672c586e9fd0cea6f7b22](https://cloud.githubusercontent.com/assets/26273930/23699574/f100dd68-03ef-11e7-96aa-6cbfdc804c44.png)

**Comment by ntozier** [comment]
There are a number of search issues already reported..  I believe that this is a duplicate.

**Comment by andreadg88** [comment]
Hi notzier,
sorry but i don't find them.
I only find agent search issue.

Can you link me them?

**Comment by mfelber** [comment]
Here are some: https://github.com/osTicket/osTicket/issues/3268 https://github.com/osTicket/osTicket/issues/2669

**Comment by ntozier** [comment]
Please close this duplicate thread then.

**Comment by ashembel** [comment]
andreadg88,

were you able to find any information on this issue? looks like mentioned bugs #3268 #2669 have no fix

**Comment by elambro** [comment]
I have the same problem and haven't been able to find a solution.

**Comment by djmrsmith** [comment]
**osTicket Version** 	v1.10 (901e5ea) — Up to date
**Web Server Software** 	Apache/2.4.18 (Ubuntu)
**MySQL Version** 	5.7.18
**PHP Version** 	7.0.18-1+deb.sury.org~xenial+1

Hi Guys,  just a quick note, i had the same problem where STAFF would work and CLIENT not... 

I played around with LOTS of code change and always had to put them back as no luck... until i made one changed which made the opposite happen, so that CLIENT would work, and STAFF would not

Below is the default in 1.10
include/class.search.php on line 373:  **case 'TicketModel':**
Staff would search, Client would not

If i changed to:
include/class.search.php on line 373:  **case 'Ticket':**
Client would search, Staff would not

So, after confirming the change wopuld alter which part of OsTicket would search correctly... i decided to have both :-) :

include/class.search.php on line 373:  **case 'Ticket':**
include/class.search.php on line 374:  **case 'TicketModel':**

Basically adding a new line to include/class.search.php

It helped me a lot... not sure if will help you guys but worth a try...

I also have lots of DB#1024 errors due to **Order by __relevance__** i fixed these by changing the code referring to that by replacing **__relevance__** with **lastupdate** in the following locations:

include/staff/tickets.inc.php:324:    $tickets->order_by(new SqlCode('**__relevance__**'), $orm_dir);
include/ajax.orgs.php:44:        $orgs->order_by(new SqlCode('**__relevance__**'), QuerySet::DESC)
include/ajax.users.php:67:                $users->order_by(new SqlCode('**__relevance__**'), QuerySet::DESC)
include/ajax.tickets.php:59:            ->order_by(new SqlCode('**__relevance__**'), QuerySet::DESC);

So again, it solved a headache for me, but not sure if it will help you guys or not... but worth a try...

Cheers

Ben
