### ISSUE TITLE
RIP osTicket

### ISSUE THREAD

**Issue by slopokeit** [osTicket/osTicket#3776]
Thanks to the osTicket team (@greezybacon @protich) for the support these past couple years.  Today we made the decision to abandon use of the project.

The continued use of sql transactions that are not replication safe made it impossible for us to continue.  

Thanks again for your effort!

[CREATE TABLE `ost__unknown_inlines` AS SELECT A2.`attach_id` FROM `ost_file` A1 JOIN `ost_ticket_attachment` A2 ON (A1.id = A2.file_id) JOIN `ost_ticket_thread` A3 ON (A3.ticket_id = A2.ticket_id) WHERE A1.`type` LIKE 'image/%' AND A2.inline = 0 AND A3.body LIKE CONCAT('%"cid:', A1.key, '"%')] Statement violates GTID consistency: CREATE TABLE ... SELECT.

#3384

**Comment by GoodbyeWorld** [comment]
I gather you're using MySQL replication.  Rather than abandon osTicket, have you considered an alternative DR/HA approach? 

For example, assuming you're running in a VM, the underlying hypervisor and clustering should help considerably in achieving low RTO, and you could use something like say regular exports of the DB to flat-file and backup, or disk replication, etc. as an alternative to DB clustering.

Just my $0.02.

**Comment by ntozier** [comment]
Of course this mentions nothing about the fact that pretty close to 90% of the SQL queries have been removed in 1.10 and the move towards ORM to make it back end agnostic.  Also 2.0 is supposed to be 100% ORM so that you can use MSSQL or Postgres etc.

**Comment by ntozier** [comment]
@peter can you close this as it is not actually an issue report.

**Comment by Chefkeks** [comment]
@ntozier
I guess you wanted to mention @protich ;)
