### ISSUE TITLE
Editing Thread Entry Issue

### ISSUE THREAD

**Issue by alfie013** [osTicket/osTicket#3876]
Dear All,

We are having an issue in our osTicket v1.10. When we tried to edit the thread entry that came from email, it keeps on loading when we hit the Save button, but nothing happens, and when we refresh the page, it duplicates the thread entry. Also, on the RichText Editor, there is no insert image icon in the menu bar. 

Below is info of our osTicket:

**Server Information**
**osTicket Version**	         v1.10 (901e5ea) —  Up to date
**Web Server Software**	 Microsoft-IIS/8.5
**MySQL Version**	                 5.7.17
**PHP Version**	                 7.0.15

Attached file is the PHP error log file. Kindly remove the **_.docx_** file extension on the attached file as I am getting an error where I cannot upload the .zip file. 

[php_errors.log.docx](https://github.com/osTicket/osTicket/files/1110702/php_errors.log.docx)
Thank you,

**Comment by alfie013** [comment]
Hi Support,

Please help me with my concern. 

Thank you,

**Comment by ntozier** [comment]
This is not the support forum.  This is the place where you would report replicatable bugs and feature requests.  Since I cannot replicate your issue on PHP5.6 IIS8.5 I would invite you to seek your support experience on the forums at: 
http://osticket.com/forum

Please help us to help you by reading and following the posting guidelines located in this thread: [Please read before requesting assistance](http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance).  I highly recommend screen shots and steps to reproduce the error that you are having.  The more information you give us the better we will be able to assist you. Thank you.
