### ISSUE TITLE
Forwarded link of ticket allows impersonation of original recipient

### ISSUE THREAD

**Issue by hshuaib90** [osTicket/osTicket#3907]
If a ticket link is forwarded to a 3rd party, the 3rd party is able to post to the thread and it doesn't record the post in the thread as a guest user but instead as the person who was the original recipient of the email.

**Comment by ntozier** [comment]
Version of osTicket?
Screen shot?

**Comment by hshuaib90** [comment]
Version is 1.10 (901e5ea)

In the screenshot you will see the last message as posted by 'Geoff', this is not correct. It was in fact posted by me after Geoff had forwarded me the link to access that ticket itself.

![edited_sc](https://user-images.githubusercontent.com/19840489/28721663-07a42dc6-73a9-11e7-803a-287abc6df61d.jpg)

**Comment by JediKev** [comment]
That's because they used the link that went to Geoff in the first place so the system thought they were Geoff. Every ticket link has an auth token attached that points to a User. When you click the link it auto logs you in, as the User, using the auth token. Simple fix is to not forward any ticket links to anyone other than the ticket owner 😁
