### ISSUE TITLE
Upgrader gives 20+ fatal errors from version 1.6 to 1.10

### ISSUE THREAD

**Issue by esamo** [osTicket/osTicket#3925]
The upgrader contains simple SQL syntax errors, they keep on coming and some are totally disrupting the update process. I gave up after 20 errors. Seriously nobody validated those SQLs? I encourage to do so...

I can share the code and DB from version 1.6 if needed, but I didn't see any errors related to the actual data, other than the data structure from v1.6.

The fresh install of 1.10 is fine as I'm almost done importing all the data manually.

Regards & respect

**Comment by JediKev** [comment]
What version of PHP do you have? I can upgrade from 1.6 to 1.10 just fine?

**Comment by esamo** [comment]
I tried on the server 5.5.38 and locally 5.6.25.

These are mainly SQL syntax errors. Plain queries. Why would PHP version matter?

**Comment by esamo** [comment]
Maybe this is because the original 1.6 version was installed on the nginx.

**Comment by esamo** [comment]
Though SQL syntax should be fixed nonetheless :).

**Comment by JediKev** [comment]
>These are mainly SQL syntax errors. Plain queries. Why would PHP version matter?

1.6 wouldn't upgrade correctly if you were using PHP 7 or 7.1...just ruling out everything I can since you provided no environment details.

>Maybe this is because the original 1.6 version was installed on the nginx.

The server shouldn't matter, it would be the Database type/version that would affect this.

As I mentioned earlier I am able to upgrade without any errors and my environment details are as follows:
- **OS:** CentOS 7
- **Webserver:** Apache 2.4.6
- **PHP:** PHP 5.4.16
- **Database:** MariaDB 5.5.52 (MySQL 5.5 equivalent)
- **osTicket:** v1.6ST

If you can provide your environment details I can try to replicate it and test the upgrade.
