### ISSUE TITLE
This project are dead ?

### ISSUE THREAD

**Issue by cloudcon** [osTicket/osTicket#3936]
I wish to know if this project has been active.
The last commit is november 2016.

**Comment by JediKev** [comment]
Yes it's active. This is not an issue or feature request so please close this. Thanks.

**Comment by cloudcon** [comment]
Thanks man 👍

**Comment by Chefkeks** [comment]
@JediKev
Folks who are new to osTicket or do not know yet about it and just come across here at the github repo are often looking at the latest commits at first sight I guess. I know the project is active, but based on the commits or the lot of pull request and issues from the community as well as the osticket team it seems that the project is may be dead. 

I assume this since I'm watching several projects on github by checking the latest activities (mainly commits) every few months to check the development status and the direction the devs/the project is going. These are mostly projects in beta status or with big plans for the next major version and it's the easiest way to do. So when there are no commits or releases over several month people often consider a project to be stalled / dead.

**Comment by cloudcon** [comment]
@Chefkeks 
You're right my friend, I actually use as parameter to know if a project is active or not the amount of commit's that are done during a period and releases.
I'm happy to know that the project is active, I'm thinking of starting to test it to see if it fits my reality. Today I use Redmine.
What do you think?

**Comment by JediKev** [comment]
@chefkeks I understand that but that's not how everyone operates. We are going to start being a lot more active and post roadmaps, etc. soon but just because something hasn't had commits in a while doesn't mean it's dead. You could view the website and forums and see that it's clearly not dead. Cheers. 👍🏻

**Comment by Chefkeks** [comment]
@JediKev
Wow, what's wrong with you guys, seriously, roadmaps? No, just kidding ;P :D :D ... I and a lot of others will be happy I guess and I know that everyone operates differently and there's a lot more than just the github commits/releases, but sometimes when you're discovering such an awesome project on github like osTicket and you don't know about the other stuff like website and forums you're often just looking at commits. And unless on the (top of the) readme(.md) this stuff is mentioned, so you can quickly get more sources to discover and explore, folks will tend to just look at the latest commits/releases based on my experiences. E.g. bearly all of my colleagues do it like that and I'm always shocked how fast they're giving up on finding more info and not just looking at commits.
Cheers!

**Comment by JediKev** [comment]
@chefkeks true stuff. We should definitely reference the site and forums on the readme to give people more reference! Cheers.

**Comment by JediKev** [comment]
@cloudcon I think you'll love osTicket. It's really robust and you can customize almost everything. Plus it's only going to get better from here 😉

**Comment by cloudcon** [comment]
Many thanks @JediKev, I did not think my question would go that far. ;P
I'm going to look with a lot of affection osTicket can be sure.
Thank you very much for your attention.

**Comment by JediKev** [comment]
@cloudcon no problem! If you have any trouble at all you can search through here under Issues or visit the forums at http://osticket.com/forum. More than likely someone has had the same problem and it is now fixed or a fix is on the way.

**Comment by clonemeagain** [comment]
FYI: Started a repo about how Awesome osTicket is, happy to merge pulls:

https://github.com/clonemeagain/awesome-osticket

**Comment by ntozier** [comment]
"May require modifications to osTicket core."
Does.
