### ISSUE TITLE
Serbian flag does not show up when Serbian lanaguage pack is installed

### ISSUE THREAD

**Issue by jlar0che** [osTicket/osTicket#3952]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
Yes
* [ ] Do you have any errors in the PHP error log, or javascript console?
No
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
Yes
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
Yes

### Description
After installing the Serbian language back I noticed that the icon for the Serbian flag was not appearing, but the link to change the language was active and working properly. This was happening on a fresh install of osTicket v1.10.

I reverse engineered osTicket and fixed the problem for you. The flags.png file does not have the Serbian flag in the correct place. I handmade a small Serbian flag for this fix and am using it in our production environment. I'm attaching the fixed flags.png and the handmade Serbian flag I created for the fix. Figured you all should have it as well.

### Steps to Reproduce

1. [First Step] Install osTicket v1.10
2. [Second Step] Download Serbian Language pack from http://osticket.com/download (under the "Language Packs" tab).
3. Activate the Serbian Language
4. Look for the Flag under the support login pages

**Expected behavior:** [What you expected to happen]
The Serbian flag should show up in the corner where the link to the language translation is.
**Actual behavior:** [What actually happened]
The link is available and active (if you put your cursor where the link should be), but the flag is no visible.

### Versions
1.10
Note: this is running on a Synology DS1517+ running the newest DSM (6.1.3-15152 Update 4)
Browser is Firefox 55.0.3 64bit
![flags](https://user-images.githubusercontent.com/1959495/30280837-182c0610-9711-11e7-8b27-94d468eed6b8.png)
![handmade serbian flag icon](https://user-images.githubusercontent.com/1959495/30280836-1802541e-9711-11e7-8d36-b5cda3e99444.jpg)

**Comment by JediKev** [comment]
I have made a pull request that fixes this issue (#3953). The reason the flag wasn't appearing was due to the incorrect class name for the language link. All you have to do is make the change in the pull request, clear all the cache for your site, and you should see the correct Serbian Flag. Cheers. 👍

**Comment by jlar0che** [comment]
JediKev, 
No, that isn't correct. The flag was not appearing was because the Serbian flag was actually not in the flags.png file at all. In other words, the space where the flag was supposed to be was blank / missing a flag. So, for me the issue was not an incorrect class name.

**Comment by JediKev** [comment]
No, I was correct...? The Serbian flag is in the original picture. Look at `-208px x -121px` (W x H). The reason there was "no flag in it's place" is because it was using the wrong class name which had no pixel placement for the file. So if it has the correct class name it will look in the correct place in the picture. Makes sense?

If you still don't believe me remove all your changes, inspect the flag icon with Chrome or Safari, and change the class from `flag flag-cs` to `flag flag-rs`. You'll see the Serbian flag now.

**Wrong Class:**
<img width="84" alt="screen shot 2017-09-14 at 09 00 09" src="https://user-images.githubusercontent.com/11823401/30434189-371ea20e-992c-11e7-8f05-5b9dfef52a22.png">

**Wrong Pixel Placement:**
This class didn't give me a pixel placement to look into the file.

**Correct Class:**
<img width="84" alt="screen shot 2017-09-14 at 09 00 25" src="https://user-images.githubusercontent.com/11823401/30434199-410c757a-992c-11e7-8351-ab81e32e4589.png">

**Correct Pixel Placement:**
<img width="294" alt="screen shot 2017-09-14 at 09 00 34" src="https://user-images.githubusercontent.com/11823401/30434213-49da7558-992c-11e7-93c9-c61e40bb5ed6.png">
