### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by suportgc** [osTicket/osTicket#3985]
Hello good day.

Not a problem, just a doubt.

Can you tell me if it is possible to insert a small form of satisfaction in the call?
Something very simple that just saved next to the ticket the customer response?

Type 3 buttons inserted in the finishing email

Good
OK
Bad

Nothing more.

Something extremely simple so that I can release my clients?

I tried to integrate with the survey monkey, but I do not know how the form could automatically get the customer data, such as (ticket number and name)

**Comment by Dubz** [comment]
You could add a custom field to the ticket and set it up so only end users can edit it and not agents.

Go to:
Admin > Manage > Forms > Ticket Details

Then add a field you want and set up its options. Be sure agents don't have permission to edit the field, otherwise they may tamper with the response from the client to always show good.

**Comment by suportgc** [comment]
Very interesting.

Can I send something to the customer at the end of the call?

Example: a button that interacts with this field?
