### ISSUE TITLE
Email not sent on "manually set" overdue date/time

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#3998]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

On a custom set of due time, overdue email is not sent

### Steps to Reproduce

1. Set a due time in the ticket (example 10 min after current time)
2. Save the changes
3. Wait the due date and time

**Expected behavior:** [What you expected to happen]
email was sent to staff

**Actual behavior:** [What actually happened]
no email sent
(when the automatic SLA time was reached the email was sent normally)

### Versions
1.9.14

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
windows server 2012 - mariadb

**Comment by fdellwing** [comment]
Can confirm that in 1.10

**Comment by JediKev** [comment]
Very strange...I'm on v1.10.1 and get the email every time I update the Due Date.

### Proof

**Ticket Number:**
<img width="185" alt="ticket number" src="https://user-images.githubusercontent.com/11823401/31743023-3e947d8e-b41f-11e7-9b2a-959451ffbe66.png">

**Updated Due Date**
<img width="264" alt="due date" src="https://user-images.githubusercontent.com/11823401/31743076-63e531aa-b41f-11e7-855d-c91e37fb0210.png">

**Update Time of Due Date**
<img width="162" alt="update time of due date" src="https://user-images.githubusercontent.com/11823401/31743094-74c9d444-b41f-11e7-9b8b-17e4b9463a0d.png">

**Overdue Email**
<img width="535" alt="overdue email" src="https://user-images.githubusercontent.com/11823401/31743104-814e2d1e-b41f-11e7-9f75-60608322fac1.png">

**Time Received Overdue Email** (8 minutes late...probably due to my SMTP)
<img width="147" alt="time recieved email" src="https://user-images.githubusercontent.com/11823401/31743129-95b50d22-b41f-11e7-842b-5761a666e268.png">

**Comment by JediKev** [comment]
@fdellwing have you checked your Spam box as well?

**Comment by fdellwing** [comment]
I have checked our mailserver. Two mails where send for opening the ticket. No one was send after due time.

**Comment by JediKev** [comment]
Okay. Hmm...

So, you have **Overdue Ticket Alert** and all its options is enabled under **Admin Panel > Settings > Tickets > Alerts & Notices** and the Agent has access to ticket's Department with the **Alerts** option enabled for the Department?

**Comment by fdellwing** [comment]
I did just set up a new test with an SLA of 1 hour. Will check back after that. For now, here are my settings:

![ost16](https://user-images.githubusercontent.com/22813377/31775081-db0325b2-b4e7-11e7-9488-052818e3ce00.png)
![ost17](https://user-images.githubusercontent.com/22813377/31775083-db1fce1a-b4e7-11e7-8975-853ffd78adfb.png)

Just to be sure, the ticket has no assigned agent, but a notification should be send to the department members.

**Comment by JediKev** [comment]
I see you have the option "Department Members" disabled. Are you the Department Manager or the Assigned Agent to the ticket?

**Comment by fdellwing** [comment]
Well that is the default config..

**Comment by JediKev** [comment]
Okay..

Got to **Admin Panel > Agents > Departments > click the Department the test ticket is under** and post a screenshot of the **Manager** setting.

Also, are you Assigned to the ticket or is the ticket Un-assigned?

**Comment by fdellwing** [comment]
Well...thanks for the hint. Works now *shame*

**Comment by JediKev** [comment]
Awesome! Glad it's working now! Cheers.

**Comment by cervedgroup** [comment]
still not working for us, just checked all the settings. The email was sent only if the dafult SLA overdue, not if a staff set a manual SLA date and time.

**Comment by JediKev** [comment]
@cervedgroup 

It could be your version as I see you are using osTicket v1.9.14. You should upgrade to either v1.9.15 or v1.10.1 and retest to see if that resolves your issue.
