### ISSUE TITLE
View Problem When Ticket Created via Email with Table Content

### ISSUE THREAD

**Issue by tomzquad** [osTicket/osTicket#4010]
osTicket Version | v1.10 (901e5ea)
Web Server Software | Apache/2.4.6 (CentOS) PHP/5.4.16
MySQL Version | 5.5.52
PHP Version | 5.4.16

Dear All,

Please help with this issue (Screenshot attached), when Ticket Created via Email with Table Content then we can't write post reply with normally view.

Br,
Thomas Marsetyo

![screenshot_2](https://user-images.githubusercontent.com/32896238/31709585-a23d1cea-b41c-11e7-8045-35621429006a.png)

![screenshot_1](https://user-images.githubusercontent.com/32896238/31709305-d12bc098-b41b-11e7-86c9-af9d2b5bc170.png)

**Comment by JediKev** [comment]
Was the table created in a separate program and pasted in the message, or was it made in an email client and sent through email, or was it created via Redactor (text editor) in osTicket?

**Comment by tomzquad** [comment]
Hi JediKev,
The table was pasted in email client and sent through email.

On Oct 18, 2017 8:39 PM, "JediKev" <notifications@github.com> wrote:

Was the table created in a separate program and pasted in the message, or
was it made in an email client and sent through email, or was it created
via Redactor (text editor) in osTicket?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/osTicket/osTicket/issues/4010#issuecomment-337593418>,
or mute the thread

**Comment by JediKev** [comment]
Ah, yea. This is a known issue where the code that makes the table will exceed the character limit for the column in the db for the thread body and it will mess everything up. There really is no way to fix that ticket unless you fix the code for the thread entry in the `body` column of the `ost_thread_entry` table. However you can _help_ prevent this in the future by changing the `body` column in the `ost_thread_entry` table to be `MEDIUMTEXT` type or `LONGTEXT` type instead of `TEXT` type. This should give you a larger character limit and should let basic tables be displayed correctly (if it doesn't exceed the character limit of `MEDIUMTEXT` or `LONGTEXT`).

**Comment by JediKev** [comment]
No problem! 😁
