### ISSUE TITLE
Drop files Here or choose them...Not working while opening ticket at user/client side

### ISSUE THREAD

**Issue by thiru506** [osTicket/osTicket#4011]
Hi Team,

When I create a new ticket and add an attachment, the attachment is stripped from the ticket. Once ticket created then I am able attach files,  it works.

I have gone through  #2992, #1309 issues, still i am unable to resolve my above mentioned issue. Here I am providing Details of my osTicket System.

About this osTicket Installation
Server Information
osTicket Version 	v1.10 (901e5ea)
Web Server Software 	Apache/2.4.25 (Ubuntu)
MySQL Version 	5.7.19
PHP Version 	5.6.30-1+deb.sury.org~yakkety+1

Any Help? Thanks in Advance...!!

**Comment by JediKev** [comment]
I am definitely not seeing the same issue.

Just a couple of questions:
- Where did you download osTicket from?
- Do you have any mods/customizations?
- What PHP extensions do you have installed?

**Comment by thiru506** [comment]
HI JediKev,
Thanks for response.
I have downloaded from osTicket official site.
Yes, I did some customizations in open.inc.php file.
I am using PHP 7.0 v

Can you please help me solving this issue.?

**Comment by JediKev** [comment]
I would first remove any customizations and test again to see if it's the custom code that's affecting it. If that doesn't work try checking your Apache or PHP error logs to see if anything is throwing an error.

**Comment by perryk** [comment]
I think I'm running into this or something similar now. Only for attachments into a field for a custom form however. I'm not able to replicate the error myself, however, I've now had 2-3 reports of this. The field is required before the ticket can be created so they must be trying to upload something.

I have the attachments on filesystem plugin installed, and nothing obvious is showing up in the httpd error logs.

**Comment by JediKev** [comment]
@perryk I've probably asked you this 1.2 million times but what version of everything are you running? (server, php, mysql, osTicket)

**Comment by mfelber** [comment]
@JediKev Side note: This sounds to me like a good feature request: Integrate a formular in osticket that allows the admin to send an github issue or forum report from osticket which automatically contains the data from the information tab of the system dashboard ;-) I don't know if this is possible but I could imagine that would help you a lot to troubleshoot and save time. This would help both sides (end users and osticket support). Maybe somebody has an idea how to implement this..

**Comment by perryk** [comment]
All good, my details are:

Server: Centos 7
Web Server Software:	Apache 2.4.6
MySQL Version:	5.5.56
PHP Version:	5.6.32
OsTicket: 1.10.1 then a whole stack of PRs applied, only a few minimal changes from me.

I can try in a stock 1.10.1, however, I'm generally not able to replicate the problem very well.

I was initially trying to find a way that people might be able to submit the ticket without the required custom field for the attachment however now I'm thinking they must be attaching something. It is just then being lost when it saves into the attachments on filesystem plugin.

Sorry I don't have anything more concrete for you to go on, if I figure out anything further I'll update it here.

Cheers.

**Comment by perryk** [comment]
@thiru506 Do you use the attachments on filesystem plugin ?

@JediKev I've confirmed a couple more cases of this today. I asked one person to make another ticket with the same filename but renamed slighty, this worked, however, I'm able to make other tickets with his original file and name so it doesn't seem to be the naming that is a problem. It looks a little more random, perhaps it happens more when the system is being used more in the morning ?

When looking over the database and going through the tables and ids of the 2 tickets, I found there is are entries in the `ost_form_entry_values` table.

For the ticket that failed to attach it has: `{"filename.doc":305}`

For the ticket that attached ok it has: `{"filename.doc":301}`

Next when I look at the `ost_file` table it has an entry for id 305 however the previous id is 300. It seems most of the ids are in order, however it is skipped some ids, perhaps they were from deleted tickets although I doubt we have many tickets being deleted.

**Comment by JediKev** [comment]
@perryk are you seeing any errors via php or apache?

**Comment by perryk** [comment]
Nothing in my httpd errors log file which has the php errors also.

**Comment by JediKev** [comment]
It's so strange that it's dropping some and not throwing an error. 🤔 Have you checked your CentOS error logs? Maybe it's some weird permissions issue or selinux issue?

**Comment by perryk** [comment]
Nothing in messages and whilst I don't have all the selinux tools on this system to really confirm, nothing in the audit log file seems to relate to this. I've just now set the system to permissive anyway, however, I don't really suspect it is the trouble as other attachments are saving ok.

Permissions seem ok, although the initial directories look a little odd this looked to be the behaviour out of the box. i.e there is a directory for each letter of the start of the file key, and the t attribute at the end which looks to be just for increased restriction to just the owner apache.  

Just a few directories:

```
d-wxr-xr-t.  2 apache apache   4096 Nov  7 11:40 _
d-wxr-xr-t.  2 apache apache    246 Nov  8 17:40 -
...
d-wxr-xr-t.  2 apache apache    126 Nov  9 09:42 5
d-wxr-xr-t.  2 apache apache    126 Nov  9 09:42 I
d-wxr-xr-t.  2 apache apache    206 Nov  9 09:42 p
d-wxr-xr-t.  2 apache apache     86 Nov  9 09:42 Y
d-wxr-xr-t.  2 apache apache    126 Nov  9 09:57 u
d-wxr-xr-t.  2 apache apache    166 Nov  9 11:56 Q
```

What is interested is that the 2 tickets I am comparing, the first one without the attachment was at 9:42 and the other was at 9:57. 

The file key for the successful attachment is `uDegJPr07U9X2WZdAh-R0k4j_RbxTgk4` and I see that in the file system ok.

```
ls -al u/uDegJPr07U9X2WZdAh-R0k4j_RbxTgk4 
-rw-r--r--. 1 apache apache 246784 Nov  9 09:57 u/uDegJPr07U9X2WZdAh-R0k4j_RbxTgk4
```

The other 4 directories (5 I P Y) however only have some files from around Oct 30 and don't have any recent files.  

I'm guessing this also relates to the missing `ost_file` IDs of 301-304.

Is it possible that something like the auto-saving of drafts is saving the file attachments, then when the ticket is posted all the saved attachments are removed ?

**Comment by perryk** [comment]
I've just heard from the user again and now he is seeing something weird with the file naming. There are some brackets in the file name he wants to attach, e.g something (a).doc and when the file does save successfully it is renamed to (something a).doc. When I save this file myself from the ticket, it actually saves out a file with the name that has the brackets.  N.b this isn't the exact name he is using, the real name is a bit longer, maybe 55-60 characters.

This looks to be a different problem to the attachments not being saved, but there must be some link as it is same user and the same files that are having the trouble.

Annoyingly, I'm unable to replicate this with a copy of his file, he is in another building but perhaps I can go over and try again just to see it myself but I do believe him in what he is saying.

He uses a Mac but we both use Chrome so not sure if there much in the way of a browser difference.

The other case today of this problem was for someone else on a Mac using Chrome who uploaded 3 files at once, all the names of files were standard and relatively short, however. In this case, it is the attachments were not saving, nothing changed to their name. I've not seen any other case of an attachment being renamed.

**Comment by perryk** [comment]
Just as a bit of a status update, I've not seen the problem again. That department only has a couple of tickets a day, and it perhaps it is only Windows users and not Mac users who have recently logged tickets, however, I'm not really convinced there is any difference between the different OSes for this. 

One thing I did change however was one of the bigger departments changed their email collection interval down to every 2 minutes instead of the others which are 5 minutes. I wasn't sure it made much difference as the cron job runs every 5 mins however perhaps there is something in this in that that period was just too short.

I'll post another update in a few days, hopefully, everything will have settled down and be going ok still.

Cheers.

**Comment by JediKev** [comment]
@perryk that sounds good! I wonder if the system tried processing too many at once and messed up somehow? Like I said before I've never seen this and it's super strange...

Hopefully it is fixed for good! If you come across any hidden errors or anything post them here as well! Cheers.

**Comment by perryk** [comment]
Ok, no sign of this problem coming back so I've chalked it up to the 2 min email collection interval. The couple of people who this problem occurred for haven't created new tickets yet but I'm confident that no one else is having any trouble. I'd say close out this issue except it isn't created by me, oops.

**Comment by GocellaGit** [comment]
I have run in to this issue on OSTicketV1.10. After some testing it appears the $note_form attachment field is not being referenced upon ticket open. I was able to get file uploads working by changing a few lines in scp/tickets.php.

Changed: 
`$vars['cannedattachments'] = $response_form->getField('attachments')->getClean();`

To:
`$vars['cannedattachments'] = $response_form->getField('attachments')->getClean();
if(empty($vars['cannedattachments'])){
	$vars['cannedattachments'] = $note_form->getField('attachments')->getClean();
}`

Not sure if this is the best way or if this can help others but it seems to be holding for me for now.
