### ISSUE TITLE
New Ticket -> Forbidden: with hostheader URL and long none-html ticket details!??

### ISSUE THREAD

**Issue by devbox** [osTicket/osTicket#4077]
Hi! 
I really have a problem and do not know, how to slove it:

System Information:
Server OS: Win 2012 R2 with IIS 8.5
PHP: 5.6.10
MySQL: 5.6
osTicket 1.10 
Website binding has a hostheader configuration.

Szenario A (working):
1. Login to osTicket over **Hostheader URL**
2. go to Creat Ticket, fill up all textfields.
3. Typing only **1-2 words** into the Ticket Details textarea!
4. click open Ticket -> All works fine!

Szenario B (Fails)
1. Login to osTicket over **Hostheader URL**
2. go to Creat Ticket, fill up all textfields.
3. Typing a **complete sentence** into the Ticket Details textarea!
4. click open Ticket -> Failed with the following Website output:
"Forbidden
You don't have permission to access /scp/tickets.php on this server."
Console output:
"tickets.php Failed to load resource: the server responded with a status of 403 (Forbidden)"

Szenario C (works!)
1. Login to osTicket over **direct local URL!**
2. go to Creat Ticket, fill up all textfields.
3. Typing **complete sentence** into the Ticket Details textarea!
4. click open Ticket -> All works fine!

Szenario D (works also)
1. Login to osTicket over **Hostheader URL**
2. go to Creat Ticket, fill up all textfields.
3. Typing only **complete sentence as HTML without breaks** into the Ticket Details textarea!
4. click open Ticket -> All works fine!

The goal is to use Hostheader URL and write complete Ticket Details with breaks.
I do not know whats going wrong, but maybe it has something to do with the Hostheader URL? Are there some settings for that?

Hope someone can help me!

Best regards
Dave

**Comment by mfelber** [comment]
This seems not to be a bug report or feature request which github actually is used for. More an IIS and forum issue (http://osticket.com/forum/categories/osticket-1-10-troubleshooting-and-problems) 

I'm not using the IIS but I can remember some people have problems with the correct configuration of the IIS because it has multiple filter settings that are not configured at the same place which is confusing. This was not in conjunction with ostTicket but maybe it helps you anyway. In this case the ISAPI Filter blocks some request although the normal configuration was set to allow this requests. The filter had to be adjusted to make the site work completely..

The only place I know where you can set an URL in osticket is this place:
![image](https://user-images.githubusercontent.com/5539456/32776246-39b004e6-c932-11e7-9ef2-0ed43b6b71a6.png)

And my understanding is that this setting only influences template links which are used for email communication with customers.

**Comment by devbox** [comment]
Thanks for your answer @mfelber 
I´ve registered me in the forum, but can´t create a thread, so I thought i have to post it here. 
The Helpdesk URL is set to my Hostheader URL.

Because of hostheader URL works with small Ticket Details, I think it has to do with osTicket configuration.

**Comment by mfelber** [comment]
I think the moderator of the forum @ntozier must approve your account. He observes github too and I guess he will do this in a few hours (he lives in a different time zone!).

All settings you can do in osTicket are available in the gui and I'm not aware that you can configure there another setting which has something to do with URL settings. I have not heard from other people who use the IIS that they have this problem with osTicket. It looks to me that something in your web server config is wrong.

That only some parts of osTicket doesn't work are for me a hint that a filter or security rule from the web server is preventing the access. Therefore the forbidden error. This type of error is coming from the web server. Unless you changed the folder structure of osTicket or modified some parts of it I can't imagine in which way osTicket would cause such an behavior.

**Comment by ntozier** [comment]
I use IIS 8.5 and have never had this issue.  I do not see an account pending for "devbox"  feel free to email me privately neil at osticket dot com.  

As a side note hostheader url is usually just called domain by most people.

**Comment by mfelber** [comment]
> As a side note hostheader url is usually just called domain by most people.
Good to know. I started to think this is a special microsoft vodoo that passed by me..
