### ISSUE TITLE
OsTicket - Email settup

### ISSUE THREAD

**Issue by rrodriguezs** [osTicket/osTicket#4094]
Hi,

I am trying to settup the mailing feature on OsTicket so we can communicate with our providers that way, however I am unable to the the option for outgoing and incomming emails on OsTicket.

Can someone help me please?
Thank you!

**Comment by JediKev** [comment]
**Admin Panel > Emails > Emails > Add New Email** is where you can start. Cheers.

**Comment by rrodriguezs** [comment]
Thank JediKev, even I did that I still have issues sending emails, on the logs i see the next message: _Unable to email via php mail function:"tester user" mail(¨myemail¨) returned failure_

What I would like to know is if the email is generated by the ticket or if there´s somewhere to create it, also is we need to configure the third partie´s email l before they can receve our messages.

**Comment by ntozier** [comment]
I think that you would be better suited taking questions like this to the forums as they do not appear to be bug related. osticket.com/forum.  Also please make sure that you read: "[Please read before requesting assistance](http://osticket.com/forum/discussion/89130/please-read-before-requesting-assistance)" 

The error "Unable to email via php mail function"  means that osTicket is configured to use the PHP mail function.  So my guess is that PHP isn't configured correctly to allow mail sending this way.  You should probably configure osTicket to utilize a mailserver instead of phpmail.

These might help:
http://osticket.com/wiki/Email_settings
