### ISSUE TITLE
FrontPage for Client 

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4118]
Hello,anyone can help me, i just want to edit the homepage for client. i just want to show the log in area no more tabs tabs at the button of the logo. which should i edit? thank you
![untitled](https://user-images.githubusercontent.com/30627667/33925710-1c9f9b5a-e016-11e7-9366-36cde2a1dced.png)

**Comment by mfelber** [comment]
Normally you would ask this type of question in the corresponding category in the forum (if you use 1.10.x): http://osticket.com/forum/categories/osticket-1-10-mods-and-customizations

**Comment by johnkalangha** [comment]
thanks for the reply i will also post this in that link. thank

**Comment by mfelber** [comment]
No problem. I think it is better to close this issue since it is no feature request or bug report. Also duplicate posts aren‘t a good thing. It makes it harder for the developers to keep the overview for other open issue reports. The developers also have an eye on the forum and there are really experienced users that are able to help you with modification attempts.
