### ISSUE TITLE
SLA Plan None

### ISSUE THREAD

**Issue by rejivincentc** [osTicket/osTicket#4144]
The overdue flag resetting while closing the ticket.

Server Information
--
osTicket Version | v1.10.1 (9ae093d)     —  Up to date
Web Server Software | Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/5.6.30
MySQL Version | 10.1.21
PHP Version | 5.6.30

**Comment by ntozier** [comment]
Huh?

Terse issue description.
No steps to replicate issue.
No why you think that this is an issue.
I'm not real sure what it is you expect us to do to help you.

Yes if you close a ticket, it is no longer overdue... it's closed after all.

**Comment by rejivincentc** [comment]
Hi Ntozier,

While closing the overdue tickets the SLA plan change to none and isoverdue value is changing to 0. 

![sla](https://user-images.githubusercontent.com/22562419/35496788-29225cda-04d0-11e8-9b46-2985ecc5492f.png)
![flagged](https://user-images.githubusercontent.com/22562419/35496789-295590fa-04d0-11e8-9187-a5698146d703.png)

**Comment by rejivincentc** [comment]
Pls find the attached document. It looks like bug in the system.

[Overdue Tickets.docx](https://github.com/osTicket/osTicket/files/1673063/Overdue.Tickets.docx)

**Comment by ntozier** [comment]
why do you think that this is an issue?

Yes, if you close a ticket, it is no longer overdue... it's closed after all.

**Comment by mlipok** [comment]
I think that @rejivincentc mean that when ticket have not anly SLA Plan then system should not Flagging tickets as overdued....

Bu as we see overdue status is an prehistoric state in relation to next thing that happend to the tickets.
So the overdud status is only for prosperity to see the fact that this ticket is some time frame, was overdued, and after all currently is closed which should be visible as last status in tickets.

**Comment by mwhitneysdsu** [comment]
So, what the document states is basically this:
- A ticket is opened, with an SLA assigned to it
- The ticket becomes overdue and the system flags it accordingly
- The ticket is closed, at which point both the Overdue status and the SLA are removed from the ticket

Further, if the ticket is not overdue, the SLA will remain assigned to the closed ticket.

So, the expected behavior, at the minimum, is that the SLA should remain assigned to the closed ticket, even if the ticket was overdue before it was closed.

In my opinion, the overdue flag shouldn't necessarily be removed, either, but I don't believe that was the point of the issue. After all, whether a ticket was overdue when it was closed is information of some value.

**Comment by mlipok** [comment]
I thnik this Overdue state is not the current state but is a one of many states on the timeline for this ticket that OP described.
