### ISSUE TITLE
How to unassign a ticket? Is there easy workaround?

### ISSUE THREAD

**Issue by esamo** [osTicket/osTicket#4152]
So many of Staff representatives are asking for a function to unassign a ticket, function that was present in some previous version.
I've looked into the code and it seems that several classes would have to be modified and if there is not staff_id on ticket the assigned person can show up from different source.
Is there an easy workaround or are you planning on such function?

Generally it is needed for cases in which client has made a ticket, Staff has responded, waiting for client's response, nothing happens for ages but can not close the ticket.

Regards & respect.

**Comment by ntozier** [comment]
This feature already exists, but only Department managers have access to this feature.

**Comment by esamo** [comment]
Thanks for reply.
I understand access/security idea, but how about removing an assignment from the current user (unbinding  a ticket from yourself)? This specifically is what Staff needs.

**Comment by perryk** [comment]
Hopefully I am understanding you correctly here. The ability for all agents to access the option for "Release (unassign) Ticket" which will unassign whoever is the current assignee, is something I felt was absolutely needed. People make mistakes and if they can assign themselves a ticket they should be able to unassign themselves. Also I feel all our Agents are responsible adults and don't need to be restricted.

I'm not quite sure now which forum/github post pointed me in the right direction however it wasn't too hard to massage the code into allowing the option for anyone.

See here for the actual code change: https://github.com/perryk/osTicket/commit/8eb89d2d818d1310a8d2967d38bcc2ddd0983fcc

If you wish to apply this, feel free to fetch/pull directly from my branch "mod-allow-agents-unassign-themselves-from-ticket" from my fork.

Fairly obviously this is an unsupported mod either by me or osTicket crew, just because it is changing some intended permissions.

Cheers.

**Comment by esamo** [comment]
Great, thanks @perryk !
