### ISSUE TITLE
unable to create ticket for new added help topic

### ISSUE THREAD

**Issue by iitsunbeam** [osTicket/osTicket#4175]
I have added Online Services / Patent Search topic in os ticket but when I try to create new ticket with Online Services / Patent Search as a help topic I get the following error in

[SELECT A1.* FROM `ost_help_topic` A1 WHERE (A1.`Id` = 13 AND A1.`name` = 'Online Services / Patent Search') ORDER BY A1.`topic` ASC] Unknown column 'A1.Id' in 'where clause'

error in the system log of os ticket

**Comment by ntozier** [comment]
You added a "search topic"?  osTicket doesn't have any "Search Topics: in it.  Perhaps you mean Help Topic or something else entirely.  When you open an issue report it is important that you provide us with as much information as possible to diagnose and replicate your issue.  Unfortunately with the information you provided we cannot do that.

version of osTicket?
version of mysql?
version of php?
steps to reproduce error?

I can tell you that query results in the same error on my system, and is caused because its asking for an id column from the table, and that table does not have an id column.

**Comment by iitsunbeam** [comment]
Yes I mean help topic, Please see following information
Version of osTicket = 1.10.1
Web Server Software = Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.6.32
MySQL Version = 5.6.35
PHP Version = 5.6.32
