### ISSUE TITLE
User in organization list - is active - how to disable them ?

### ISSUE THREAD

**Issue by mlipok** [osTicket/osTicket#4180]
### Prerequisites

* [Y] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [N] Do you have any errors in the PHP error log, or javascript console?
* [Y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

http://osticket.com/forum/discussion/comment/121212

### Steps to Reproduce

I go to organizations.
Click on first position on the list.
And I see all users which are ssigned to this organization.
In column called "Status" I see "Active"
How to deactivate this single user ?

**Expected behavior:** [What you expected to happen]
Have possibility to set/disable active status for user
Have possibility to find user per status

**Actual behavior:** [What actually happened]
What mean Active status ?

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

v1.10.1 (9ae093d) 
Not releated to browser/system etc...

**Comment by JediKev** [comment]
>In column called "Status" I see "Active"
>How to deactivate this single user ?

There is no way to "Deactivate" Users but you can Lock their account or Delete them from an Organization. You can Lock a User's account by clicking the User's name, click Manage Account, go to the Manage Access tab, Enable Administratively Locked, and Save Changes. Once you do this the User will be Administratively Locked and should not be able to login. In order to Delete a User from an Organization, check the box next to the User's name, click the Remove button, and click Yes, Do it!. Once you do this the User should be removed from the Organization.

I hope this helps. Cheers.

**Comment by mlipok** [comment]
So if the user is Locked then it should be visible inside of Organization as disabled / Deactivated .
I have user's which alreade are not staff in their organization.
But I need to keept the assignation USER <> Organization to have a calrity of data in my osTicket instalation.

btw.
This Locked / Disabled / Deactivated user should not be attached each time new ticket is createad for Organization.
