### ISSUE TITLE
Printing ticket without the messages?

### ISSUE THREAD

**Issue by EnisKirgoer** [osTicket/osTicket#4194]
Hello,

i have osticket 1.10 and ist there a posibillity to save the ticket in pdf without the messages? if yes what need i do? (in the code etc)

**Comment by ntozier** [comment]
I would think that you would have to neuter the print option (or clone it and then neuter it, and add a button for it to the ui).

**Comment by perryk** [comment]
This plugin should be able to save the ticket in pdf, not sure if it has an option to exclude the messages however it might be easier to modify the code of the plugin rather than the osTicket code and still be able to update the OsTicket code at a later date.

https://github.com/clonemeagain/osticket-plugin-archiver
