### ISSUE TITLE
Feature request: Sugar CRM integration

### ISSUE THREAD

**Issue by F3000** [osTicket/osTicket#4216]
A pairing between the two systems would be grade. In our company we done all the order management things with Sugar.

**Comment by JediKev** [comment]
This would be handled by a plugin. You can find information on how to build a plugin for osTicket here:
https://github.com/osTicket/osTicket-plugins

If you can't build one yourself you can ask the community on our [Forums](http://osticket.com/forum) to help out. This is more of a Forum post rather than a Github post so please post this on the Forums and close this issue.

Cheers.

**Comment by F3000** [comment]
Thanks for the tipp :)
