### ISSUE TITLE
logout appears to fail to logout

### ISSUE THREAD

**Issue by legatoj** [osTicket/osTicket#4245]
In preparation for making our osTicket site open to a wider audience, we performed an Appscan of osTicket version 1.10.1 using IBM Appscan Standard 9.0.3.7 Rules:12428. Appscan notes the following on logout.php (Page), "It may be possible to steal or manipulate customer session and cookies, which might be used to
impersonate a legitimate user, allowing the hacker to view or alter user records, and to perform
transactions as that user"
Fix: Invalidate relevant session identifiers when a user signs out
Reasoning: The test result seems to indicate a vulnerability because the test response is identical to
the original valid response, showing that after logging out it was still possible to access a
protected resource.

We can provide more detail if needed.

**Comment by JediKev** [comment]
@legatoj 

When you logout we update the session in the database to a new session that has a different `session_id` and different `session_data`. So even if an attacker got your previous logged-in token it wouldn't work because there is a completely new `session_id` and completely new `session_data` in the database.

Ultimately, they would have to know your password and Username/Email in order to login as you.

Cheers.

**Comment by legatoj** [comment]
Thank you, our security team agrees that this is a false positive. However they believe that a Cross Site scripting vulnerability may exists in tickets.php and logout.php this may also be a false positive, Their reasoning is that because the response they receive back from their test "is the same the original response they received even though it included a fictive 'Referer' Header"
