### ISSUE TITLE
Checkout and deployed latest Branch, but osticket tells me differently

### ISSUE THREAD

**Issue by rapsli** [osTicket/osTicket#4254]
I have checked out osticket (https://github.com/osTicket/osTicket.git)

I have done some back and forth because it's my first time working with osTicket. I can switch back and forth between branches:

    git checkout develop
    php manage.php deploy -vC ../public

Nevertheless OSTicket tells me that I'm on Version 1.8

osTicket Version | 1.8-git (?)  Upgrade— 9ae093d is available
-- | --
Web Server Software | Apache/2.4.28 (Unix) OpenSSL/1.0.2g
MySQL Version | 5.7.21
PHP Version | 5.6.34

I wouldn't care, but I do have some issues with the mail fetcher authentication so I have to sort this out first.

**Comment by ntozier** [comment]
Generally speaking I recommend that people download the source archive from the official web site.  There is some packaging that happens before it is released so that it will do things like show the right version number.  Checking it out from git means that you will always see that instead of the actual version.
