### ISSUE TITLE
Queue Bugs and Request addinitional features or the system

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4459]
OSticket Details

![image](https://user-images.githubusercontent.com/30627667/44305089-c7af0b80-a3a1-11e8-877f-dfd9aadad97d.png)
 **Issue 1:  Adding personal queue.** 
     _a. When i add personal queue as an agent.. i only check the assignee but when i save there are some fields included.._
![image](https://user-images.githubusercontent.com/30627667/44305150-7869da80-a3a3-11e8-9858-0f00afed3477.png)

   _b. When i add the a personal queue, there are 2 names in my drop down menu.._
![image](https://user-images.githubusercontent.com/30627667/44305164-b109b400-a3a3-11e8-9ca2-dfe40973714c.png)

**Request for the system**
     1. Option if the agent can add personal queue. If Enable (agent can add custom queue, if Disable, only admin can add/modify custom queue
    2. Admin only can set custom queues to specific team. 
           For Example: i have a team1 and i want them to see only the issue1 in an open queue tab without affecting other teams or other members.
     3.   i will think the 3rd request :)

**Comment by JediKev** [comment]
@johnkalangha 

>a. When i add personal queue as an agent.. i only check the assignee but when i save there are some fields included..

That's because you are creating a personal queue from a main-level queue (My Tickets). This will INHERIT all main-level queue criteria hence the "Inherited Criteria (My Tickets)" dropdown. Not a bug; expected behaviour.

>b. When i add the a personal queue, there are 2 names in my drop down menu..

I'm seeing the same thing...will look into why this is.

>1. Option if the agent can add personal queue. If Enable (agent can add custom queue, if Disable, only admin can add/modify custom queue

Almost 100% positive this will not be implemented as all agents should be able to create/edit/delete their own queues. They have access to all other queues so why not?

>2. Admin only can set custom queues to specific team.

_Might_ be in version 2 of CC/CQ.

Cheers.

**Comment by johnkalangha** [comment]
ah i see, thanks sir
