### ISSUE TITLE
wrong Organization link URL

### ISSUE THREAD

**Issue by matuscak** [osTicket/osTicket#4579]
When I add "User / Organization / Name" column to my Open Ticket queue and I put "Organization Link" filter on this column, generated URLs for the links are wrong.

Instead of linking to:
/scp/orgs.php?id=XXX

created links are directed to:
/orgs.php?id=XXX

(the scp part is missing, so the link does not work).

Tested on last commit on the 1.11.x branch (v1.11.0-rc1-333-ge7793c95), running on PHP 5.6.

**Comment by Aka4Code** [comment]
this bug still exists with v1.11 release (7b1eee8)

**Comment by Aka4Code** [comment]
![image](https://user-images.githubusercontent.com/11789024/53234951-fbd8f100-3690-11e9-9eea-74378214e24e.png)

![image](https://user-images.githubusercontent.com/11789024/53236875-a3f0b900-3695-11e9-81a7-71691cd4d372.png)

it's:
https://domain.pl/orgs.php?id=9

instead of https://domain.pl/scp/orgs.php?id=9

**Comment by JediKev** [comment]
@matuscak @Aka4Code 

Here you go:
#4755

Cheers.

**Comment by Aka4Code** [comment]
Thank you. 👍

**Comment by matuscak** [comment]
Thanks
