### ISSUE TITLE
NPS at the end of the ticket?

### ISSUE THREAD

**Issue by lglucas** [osTicket/osTicket#4611]
v1.10.4 

I would like to know if it's possible to create a form that could **appear** for the user only when the ticket is closed by an agent.
For example, my idea is to have a NPS to score the satisfaction of the user by choosing between one to five stars, but I want to present that form only in the end.
Do we have a way to put, for instance, inside some thank you page?

Thanks. :)

**Comment by JediKev** [comment]
@lglucas 

Unfortunately, there is no way currently to show fields AFTER a ticket has been closed. You can edit the Thank You Page **(Admin Panel > Manage > Pages > Thank you)** to your liking but I'm pretty sure you can't put a working "survey" as this will not POST data. With this being said the code is completely open source giving you the freedom to customize to fit your needs.

Cheers.

**Comment by lglucas** [comment]
> @lglucas
> 
> Unfortunately, there is no way currently to show fields AFTER a ticket has been closed. You can edit the Thank You Page **(Admin Panel > Manage > Pages > Thank you)** to your liking but I'm pretty sure you can't put a working "survey" as this will not POST data. With this being said the code is completely open source giving you the freedom to customize to fit your needs.
> 
> Cheers.

Thanks!
That's what I was thinking.
Actually we're gonna integrate with another system that we have for lawyers. And very probably we're gonna to do this customizations. 
Again, thanks!

**Comment by ntozier** [comment]
@lglucas I know that you closed this but...

What we did for a while is utilized a 3rd party survey site (like surveymonkey or surveygizmo), and we used a canned response when we closed the ticket which gave the url for the satisfaction survey to the end user.  They could then click on it and go to the survey and answer some quick questions so that we could track additional information for each ticket.  Ultimately the company that I worked for decided to discontinue the use of this third service survey site but while we had it this worked quite well and didn't involve any source code changes to the core product.  I thought that you might find this solution useful.
