### ISSUE TITLE
OsTicket v1.11.0-rc1 user can only send 1 attachment with a ticket

### ISSUE THREAD

**Issue by gdenabt** [osTicket/osTicket#4625]
When a user makes a ticket and put 3 attachments in it, only 1 attachment is vissible for the support.  
We use PHP 7.1 and OsTicket OsTicket v1.11.0-rc1
My Ticket Attachment Settings are ok

Regards,
Gerry

**Comment by ntozier** [comment]
I think that @JediKev would say if you are going to run 1.11rc1 then please pull develop-next from github so that you have all the patches.  There have been a large number of bugs addressed in github.

I would say that people should probably not be running an RC (release candidate) in production.  You should be running stable software (1.10.4 as of this writing).
