### ISSUE TITLE
Email content from incoming mails is messed up

### ISSUE THREAD

**Issue by Thijzer** [osTicket/osTicket#4764]
The content of Incoming email is completely cut off when using foreign characters.

I'm a dutch native speaker so my example is in dutch

Incoming message
```
Beste,
Prima hoor, ik laat het inplannen door één van de project managers.
```

BECOMES
```
Beste,
Prima hoor, ik laat het inplannen door
```

The cut-off happens at the` é`

the version I'm running
```
osTicket Version | v1.10.4 (035fd0a) —  Up to date
```

**Comment by JediKev** [comment]
@Thijzer 

Not seeing the same issue:
![screen shot 2019-02-27 at 09 47 27](https://user-images.githubusercontent.com/11823401/53503055-f276cc80-3a74-11e9-8fff-65e045b0e651.png)

Maybe it's due to the email's character set or the database character set? Have you changed either of these from UTF8 to something else?

Cheers.

**Comment by Thijzer** [comment]
Hey JediKev, thanks for helping out.

My installation comes from https://hub.docker.com/r/campbellsoftwaresolutions/osticket.
He's [https://hub.docker.com/r/campbellsoftwaresolutions/osticket/dockerfile](dockerfile) doesn't look all that weird.

**Comment by JediKev** [comment]
@Thijzer 

Ouch...I wouldn't trust a Dockerfile. We haven't developed one so you're pretty much using it at your own risk. Also, they are using NGINX which is not a supported webserver at this time (it can work but it takes extra configurations in NGINX to be supported). I would try to setup/configure an actual server with the suggested pre-reqs installed/configured and see if you get the same issue. (which I doubt since I cannot replicate this using v1.10.4, MariaDB, Apache, and PHP 5.6)

Cheers.

**Comment by JediKev** [comment]
@Thijzer 

You're saying the text is in the database properly but doesn't show up in the UI or you were just saying the database appears to be fine?

Cheers.

**Comment by Thijzer** [comment]
@JediKev 

Indeed this docker container is way to exotic for the required spec.
I'm a docker kind of guy which if done correctly should make no difference what so ever to a VM or physical hardware. It's just a container on top of your kernel.

I will try to create my own dockerfile with the one from Campbell as a starting reference but running on the required spec with debian as it's core and see if get this error fixed.

**Comment by Thijzer** [comment]
Maybe we could boot up the old osticket/osticket link for it if it has any value.

**Comment by Thijzer** [comment]
A restart of the container seems to have fixed the problem. So I'm good for now, still going to invest some time in building a decent container. I'll close this issue for now and reopen when I have a working container.
