### ISSUE TITLE
Upgrade from v1.10.1 to v1.11 cannot see tickets at all

### ISSUE THREAD

**Issue by Vudubond** [osTicket/osTicket#4809]
After updating from v1.10.1 to v1.11 cannot see tickets at all:

[https://i.imgur.com/UFN1z3a.png](url)

And the menus behave strangely, see video:

https://www.dropbox.com/s/1c6y6qya9qvxne7/2019-03-20_14-25-41.mp4?dl=0

I don't get any error, neither during update or after that.

Accessing a ticket with URL rewrite is possible:

https://domain/orlando/scp/tickets.php?id=137286

When accessing like this the menus are fine as well:

https://i.imgur.com/PYg6Y3B.png

Please help.

ost_queue look like this:

https://i.imgur.com/5RQll21.png

**Comment by ntozier** [comment]
This looks like a question for the forums.  
https://forum.osticket.com/

What version of PHP are you running?  What webserver software?
Where did you download the 1.11 files from?
Have you changed the ownership and permissions on the upgrade files?

**Comment by JediKev** [comment]
@Vudubond 

In regards to the first image you posted, this is due to one of two things:
**# 1** The queues are still trying to load; after the queues fully load you should see the entire page with it's styling in tact.
**# 2** There is a fatal error causing the queues/page to crash.

I would wait up to 3-4 minutes to see if it's a loading issue. If it's a loading issue check your server resources to see if it needs more. If it's not a loading issue then there has to be a fatal error which you should be able to see in your php error logs.

Cheers.

**Comment by bramkragten** [comment]
Update your PHP version, that will probably solve it.

**Comment by hescher** [comment]
I had the exact same error as OP.
The problem was my PHP version. It was 5.4.
With PHP 5.6 the problem is gone. 

@bramkragten your solution worked for me, thank you

**Comment by Vudubond** [comment]
Thank you, changing the version was fine, from 5.5 to 7.1
