### ISSUE TITLE
Ticket creation through generic email

### ISSUE THREAD

**Issue by ankitsaurabh** [osTicket/osTicket#4886]
Hello Users

I have installed osTicket on windows and configured the settings as explained in the installation documentation. The interface can send emails to users/agents when a ticket is created on the osTicket interface from my default IThelpdesk email address.

But, is it the only way to create tickets? I was looking for an option where if a user sends email to my IThelpdesk email address, it captures on osTicket and creates a ticket as well.

Any help on this

**Comment by JediKev** [comment]
@ankitsaurabh

This does not appear to be an issue report, rather a request for help or guidance. GitHub is meant for Issue Reports, Feature Requests, and Pull Requests. Questions, requests for help, etc. is more suited for our community supported [Forum here](https://forum.osticket.com/).

I will close this so that you may submit this to the forum. I will provide you with the following two links to get you started though. What you need is to setup Email Fetching and if you want to make it automatic you have to setup a  Cron job or scheduled task.
### Email Fetching/Sending via IMAP/SMTP

- https://docs.osticket.com/en/latest/Admin/Emails/Emails.html

### Cron Job/Scheduled Task

- https://docs.osticket.com/en/latest/Getting%20Started/POP3-IMAP%20Settings.html#schedule-polling

Cheers.

**Comment by ankitsaurabh** [comment]
thanks JediKev. I followed the steps and it works good. Will use forum to ask questions moving forward.
