### ISSUE TITLE
Upgrading Instructions Are Not Clear

### ISSUE THREAD

**Issue by greenlanegreb** [osTicket/osTicket#4921]
Hi, I am currently running version 1.10.4. I have attempted to upgrade by downloading the files and FTP'ing them across. When I went to log in, the version remained at 1.10.4 and no upgrade script was triggered. I have read the upgrade and read me files but there are no clear instructions on how to upgrade. Sorry to post this here but I wasn't sure where else too. 

Many thanks.

**Comment by JediKev** [comment]
@greenlanegreb

Since this is not an issue report or feature request I will direct you to post this on our [Forum](https://forum.osticket.com). There you may ask questions and receive community assistance.

With this being said I’ll go ahead and answer you here. All you need to do is copy and replace the new files (v1.12 in this case) over the existing files. Make sure you take a database backup and code file backup beforehand just in case anything happens.

Cheers.

**Comment by greenlanegreb** [comment]
Hi Jedikev, 

Thank you for this! What you instructed me to do is what I have been doing but, when I log in, it's still got the old version in the admin section so I guess it's not updating! Sorry about posting here and thank you again!
