### ISSUE TITLE
how to change the content of message when ticket is created in os ticket

### ISSUE THREAD

**Issue by khotamr** [osTicket/osTicket#4927]
I want to add the ticket number in that message

**Comment by JediKev** [comment]
@khotamr 

This does not appear to be an issue report or feature request, but rather a question on how to accomplish something. GitHub is meant for Issue Reports, Feature Requests, and Pull Requests. Questions, requests for help, etc. are more suited for our community supported Forum [here](https://forum.osticket.com).

With this being said I will go ahead and provide you with a quick answer below:
```
If you are talking about adding the ticket number to the Email Alert that gets sent out 
to the User/Agent when a ticket is created then you can edit any of the email templates
under Admin Panel > Emails > Templates and utilize the %{ticket.number} variable.

If you are talking about adding the ticket number to the body (message) of the ticket itself in
osTicket, that is not a current feature of the helpdesk so it is not possible at this time.
You could accomplish this with modding osTicket but we cannot provide assistance with that.
```

I will close this now so that you may submit this to the Forum.

Cheers.
