### ISSUE TITLE
1.12 Editor strips 'tags' 

### ISSUE THREAD

**Issue by NdK73** [osTicket/osTicket#4937]
Probably related to #1711 #3479 and #4639 .

When sending an answer, everything after a '<' disappears till the end of line or a '>'.

I usually insert verbatim command sequences like
-8<--
$ cd $HOME
-8<--

or 'old style' comments like &lt;evil mode on>.

**Expected behavior:**
I'd expect that what I typed got included in the mail and shown in the ticket history.

**Actual behavior:**
-8<--
becomes
-8
and &lt; evil mode on> simply disappears (this happens here on GitHub, too! I had to use the lt entity).

That's on OsTicket 1.12 (a076918), Apache/2.4.25, MySql 10.1.38, PHP 5.6.40-8+0\~20190531120521.15+stretch~1.gbpa77d1d .

**Comment by JediKev** [comment]
@NdK73 

Why open a new issue when there are some already open..? I will close this in favor of the original(s). 

Please read this comment for more details:
https://github.com/osTicket/osTicket/issues/3791#issuecomment-500506685

Essentially the same is happening to you for `<evil mode on>` but since it is not a _valid_ HTML tag it strips it from the content. `-8<--` becomes `-8` as the system could not _balance_ the HTML so it strips the tag and whatever is after/in it.

Cheers.
