### ISSUE TITLE
New or editing notes is broken

### ISSUE THREAD

**Issue by TechCare-Aus** [osTicket/osTicket#5053]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [X] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Problem with the notes since upgrading to the latest version of osticket-develop (presumably very similar to 1.14rc1). Organisation notes are broken.

### Steps to Reproduce

1. Click organisation
2. Click on notes
3. Edit existing note

**Expected behavior:** 
Same behaviour as before. Edit by default opens up in WYSIWYG editor, then option to change to code mode, then ability to save is displayed. Ideally an option to undo changes or at least see the changes made too (this is a sneaky attempt to add a brilliant option to notes)

**Actual behavior:** [What actually happened]
Display is cut to small version, only shows up as code (no WYSIWYG editor mode) and no save button

### Versions

osTicket Version | 1.14-git (5ea4fb5)
Web Server Software | Apache
MySQL Version | 10.3.18
PHP Version | 7.3.9

**Comment by JediKev** [comment]
@TechCare-Aus 

I see you say you are using the `develop` branch but that branch actually correlates to `1.12-git`. I think you meant you're using the latest from `develop-next` branch if you're using v1.14-rc1. 😉

I notice the same issue with v1.14-rc1 and I do believe it was due to the Redactor upgrade. We will look into this. 👍

Cheers.

**Comment by TechCare-Aus** [comment]
> I see you say you are using the develop branch but that branch actually correlates to 1.12-git. I think you meant you're using the latest from develop-next branch if you're using v1.14-rc1. 😉

haha sorry mate. yes typo.

On a side note. When I've updated to the latest git on branch develop-next and go to information next to `osTicket Version | 1.14-git (5ea4fb5)` it tells me to upgrade. Is this due to it thinking that v1.14RC1 is a higher version?

**Comment by JediKev** [comment]
@TechCare-Aus

It’s just not in our dns yet as it’s an RC so it’s going to say that for now.

Cheers.

**Comment by TechCare-Aus** [comment]
@JediKev I can understand the RC not being in your DNS, but Git should be the latest version always surely? Or are you saying that this function only works with officially released versions?

**Comment by protich** [comment]
@TechCare-Aus - I was a little confused by @JediKev response as well. To answer you - it depends on which branch you pull. 

**master**  - latest stable release `v1.12.2`
**develop** - latest + bug fixes `v1.12.2+` 
**develop-next** - upcoming release / new features / bleeding edge  `v1.14-rc1+`

We of course don't recommend pulling from develop-next for production-use unless you like living on the edge... we're ironing out bugs and do indeed require upgrade since the next version comes with database patches.  I think this is in essence what Kevin was pointing out, we are squishing as many bugs as possible before we cut the second release candidate.

**Comment by TechCare-Aus** [comment]
@JediKev @protich @greezybacon - any fix coming for this?

**Comment by JediKev** [comment]
@TechCare-Aus 

Typically if there are any updates, they will be posted in the original issue thread (here).

With this being said it was a pretty easy fix:
- https://github.com/osTicket/osTicket/pull/5066

Cheers.

**Comment by TechCare-Aus** [comment]
@JediKev Thank you sir.

**Comment by TechCare-Aus** [comment]
@JediKev - actually I jumped the gun, still broken in relation to editing existing notes.

**Comment by TechCare-Aus** [comment]
https://github.com/osTicket/osTicket/pull/5066#issuecomment-535777441
