### ISSUE TITLE
Ticket count 

### ISSUE THREAD

**Issue by bertaviader** [osTicket/osTicket#5341]
### Prerequisites

* [-] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [N] Do you have any errors in the PHP error log, or javascript console?
* [Y] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

The count of the ticket takes 5 minutes to update.

### Steps to Reproduce

1. Create the ticket or delete one ticket
2. Go to the tickets:

![Kazam_screencast_00001](https://user-images.githubusercontent.com/18306366/72533789-076b7280-3876-11ea-8b86-6812d557a32e.gif)

**Expected behavior:** Actualization of the count

**Actual behavior:** Having to wait for the count to actualize

### Versions
Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

![image](https://user-images.githubusercontent.com/18306366/72533948-4e596800-3876-11ea-8a32-13df4aef6bf1.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

Ubuntu 16.04
Chrome Version 65.0
Firefox 72.0.1

**Comment by JediKev** [comment]
@bertaviader 

Yes, we cache the counts, otherwise there would be way too many queries running and your helpdesk which might drop your performance, etc. The code responsible for this is here:
- https://github.com/osTicket/osTicket/blob/develop-next/include/class.search.php#L991-L992
- https://github.com/osTicket/osTicket/blob/develop-next/include/class.search.php#L1015-L1023a

You are welcome to change this behavior if you'd like as the code is open source. 👍

Cheers.

**Comment by bertaviader** [comment]
Thank you so much for the fast response and explanation, I will proceed to close it, then. 
Cheers,
Berta
