### ISSUE TITLE
Usage of Crowdin translations

### ISSUE THREAD

**Issue by fred-cardoso** [osTicket/osTicket#5378]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

I contributed with some translations on Crowdin and downloaded the translations into i18n folder. osTicket detects the folder and the translation, but after changing the primary language in system settings the system doesn't change and remains in English.

I also changed in profile to the newly installed language.

I know I am not using a .phar file, but I didn't found any instructions on how to compile the data from Crowdin into a usable .phar file.

### Versions

osTicket version: v.1.14.1
Chrome, Windows 10

**Comment by JediKev** [comment]
@fred-cardoso 

I will close this as this is more of a question for our [Forum](https://forum.osticket.com) rather than a Bug Report/Feature Request for Github. Github is a place for Bug Reports, Feature Requests, and/or Pull Requests. Our Forum is a place to ask questions, debug, get assistance, etc. 

With this being said I will go ahead and answer you here. Take a look at the [i18n CLI module](https://github.com/osTicket/osTicket/blob/develop/include/cli/modules/i18n.php) or [this](https://github.com/osTicket/osTicket/blob/develop/setup/doc/i18n.md).

Cheers.

**Comment by fred-cardoso** [comment]
Thank you @JediKev.
