### ISSUE TITLE
No email when ticket is created

### ISSUE THREAD

**Issue by unixbird** [osTicket/osTicket#5382]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

OsTicket sometimes sends email when a ticket is created but other times not. I have checked the forums and no one has the same exact issue or their solutions are not my solutions

### Steps to Reproduce

1. user puts in ticket
2. Sometimes we get an email, sometimes not

**Expected behavior:** Receive email to our email group that we have received a ticket

**Actual behavior:** The above doesn't happen

Running 
OsTicket Version 1.14.1
Mysql 10.1.44
php 7.033
Apache 2.4
Debian 9 Turnkey Linux

**Comment by unixbird** [comment]
I am also not seeing anything in the logs

**Comment by JediKev** [comment]
@unixbird 

Well, if you get the alerts sometimes then that means it working. Maybe you just don't have access the Ticket's Department? If you don't have access to a Department then obviously you won't receive alerts for tickets created in that Department. So, first, make sure you have access to the Department(s).

Next, check every Departments' settings (**Admin Panel > Agents > Departments > click Department > Settings**) and ensure that you don't have the `New Ticket` option disabled. You should also check to make sure the `Recipients` dropdown is set to `Department members only` or `Department and extended access members` so that the alerts go to Department members. This setting overrides the Global alert recipient settings so if you have the Global set to send to Department Members but the Department is set to Admin Email only, then only the Admin will receive the alert.

I hope this helps.

Cheers.

**Comment by unixbird** [comment]
@JediKev 
I have checked the settings on OsTicket and found that some of the departments had some weird settings. I found that the tickets I was receiving were put in from one department however, after cloning the settings to the other departments it still does not email. I should note that this install was upgraded from a 1.9.12 osticket version

**Comment by JediKev** [comment]
@unixbird 

Being upgraded shouldn't matter tbh, it should be the current configurations that matter.

Can you post screenshots of:
- An example Ticket that didn't send an Alert (including the Ticket Header; please redact sensitive information)
- Your Global Ticket Alert Settings
- Your Department Alert Settings/Recipients
- Your Department Access (go to **Admin Panel > Agents > Agents > click your name > Access**)

Also, provide us with any other information that could be relevant such as was the ticket created and automatically transferred to another department via filter, etc. Once we have this information we can better debug this issue.

Cheers.

**Comment by unixbird** [comment]
@JediKev 
Alright so the problem was actually that the settings weren't saving and it was an issue with autoresponse email not being set correctly and what you were saying with Department and extended access members. The reason why it was sometimes working was for whatever reason that one department that transferred over had the settings while the others didn't. Sorry about that I overlooked that!
