### ISSUE TITLE
Internet Explorer cannot Paste Image 

### ISSUE THREAD

**Issue by ADM-RMZ** [osTicket/osTicket#5411]
Good Morning everyone,

I try to copy an image but nothing appears, nor any error message. it's just empty. This only happens when I use IE. Thanks for the help.

![image](https://user-images.githubusercontent.com/62133855/76603155-bf329e80-650c-11ea-89ec-fc85b783c053.png)

![image](https://user-images.githubusercontent.com/62133855/76603283-fdc85900-650c-11ea-882a-5eebf1b9988b.png)

**Comment by ntozier** [comment]
Microsoft support for IE10 ended on 1/12/2016.
Support for IE11 does not have a hard end date at this time, because it is tied to Windows 10.  Microsoft wants you to upgrade to Edge.  IE 11 has 3.4% of the browser market share [source](https://www.w3counter.com/globalstats.php).

I would highly recommend not using any version of IE.

If you are experiencing a problem with a single browser then it is that browser.  I do not believe that the devs are going to spend time on trying to get the product to work on a browser that is effectively dead and older than dirt.

As a side note I do not believe that osTicket officially supports PHP 7.4 at this time.

**Comment by JediKev** [comment]
@ADM-RMZ 

Also, see this post for more info:
- https://github.com/osTicket/osTicket/pull/5228

Cheers.

**Comment by ADM-RMZ** [comment]
Moin !
Thank you very much for the information!

Best regards,
ADM-RMZ
