### ISSUE TITLE
Attempting to upgrade from 1.10.1 to latest via the GUI doesn't work

### ISSUE THREAD

**Issue by StewAlexander-com** [osTicket/osTicket#5430]
Hi,

We are attempting to upgrade following the steps outlined here:
```https://docs.osticket.com/en/latest/Getting%20Started/Upgrade%20and%20Migration.html```

From version ```1.10.1```  on Ubuntu 14.01, PHP 5.x and MySQL 5.5

When we click the upgrade link in the GUI, instead of going to a wizard it takes to a download link.

Reading the documentation, it appears to show that we can just upgrade if we are greater than 1.6.x

What are your upgrade recommendations?

**Comment by JediKev** [comment]
@StewAlexanderACC 

You should take a look at our Upgrade Guide here:
- https://docs.osticket.com/en/latest/Getting%20Started/Upgrade%20and%20Migration.html

The guide also includes a link to our YouTube video on how to upgrade if you prefer that medium instead.

Cheers.

**Comment by StewAlexander-com** [comment]
Hi @JediKev 
I read that, but if you see my link, its the same or nearly the same one you posted.

The GUI step it points to does not work

**Comment by StewAlexander-com** [comment]
![image](https://user-images.githubusercontent.com/48565067/77463944-cd21d280-6ddc-11ea-9df0-15f55fa81ffc.png)

Takes us here:

https://osticket.com/download/?cv=v1.10.1

Not to a script that takes through the install

**Comment by JediKev** [comment]
@StewAlexanderACC 

>I read that, but if you see my link, its the same or nearly the same one you posted.

Don't know how I missed that, my bad.

>Takes us here:
>
>https://osticket.com/download/?cv=v1.10.1
>
>Not to a script that takes through the install


Oh, so you haven't gone through the steps to Upgrade then because it still shows you are on v1.10.1 and if you click that link, yes, it will take you to the download page for you to select which version you want to upgrade to.

So, upgrading is quite simple. First, you need to download the latest version from our website [here](https://osticket.com/download). Upload and unzip the ZIP file somewhere on your webserver. Move everything out of your current osTicket directory on the webserver into a new directory for backup (you'll need this later). Next, move everything in the `upload/` folder from the downloaded ZIP file to your osTicket directory on the server. Next, copy the `include/ost-config.php` file from your backup to your `include/` folder within your osTicket directory. Now, login to osTicket and you should be presented with the Upgrade Wizard. If not, you probably missed a step.

**Note:**
You will also need to backup the database just in case the upgrade has issues.

Cheers.

**Comment by JediKev** [comment]
@StewAlexanderACC 

I also just noticed that you are using PHP 5.5 which you will need to upgrade to PHP 5.6-7.3 before upgrading. (PHP 7.3 is recommended)

Cheers.

**Comment by StewAlexander-com** [comment]
Phew, sounds easier than I was thinking thanks
