### ISSUE TITLE
Forbidden error after upgrading, with something about "anomaly score exceeded" in error log

### ISSUE THREAD

**Issue by StewAlexander-com** [osTicket/osTicket#5434]
In order to upgrade PHP I upgraded my Ubuntu 14.01 to 18
Then I upgraded PHP to 7.3

The HTML folder wasn't in the updates folder, so when I moved the /var/www folder over to /var/old-www and made a new /var/www folder dumping the contents from the zipped upload folder from 1.14.1 zip into the new /var/www/ folder I didn't have an html director (??)

So I copied the old HTML directory from the old-www over to the new /var/www/ folder and now I get permissions issues, as in a 403 Forbidden error

Here's the repeated entry in the var/log/apache2/error.log:
```
[Fri Mar 27 20:25:02.146025 2020] [:error] [pid 16981] [client 172.16.1.193:240rning. Operator GE matched 4 at TX:outbound_anomaly_score. [file "/usr/share/moION.conf"] [line "82"] [id "980140"] [msg "Outbound Anomaly Score Exceeded (scorrelation"] [hostname "support.alamancecc.edu"] [uri "/"] [unique_id "Xn6ZXng0W
```

**Comment by StewAlexander-com** [comment]
```DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"```
```PHP 7.4.4 (cli) (built: Mar 20 2020 13:47:45) ( NTS )```
```Apache/2.4.29 (Ubuntu)```
```osTicket-v1.14.1.zip```

**Comment by StewAlexander-com** [comment]
Any help would be greatly appreciated, thanks

**Comment by JediKev** [comment]
@StewAlexanderACC 

First, don’t use PHP 7.4.x, use PHP 7.3.x. We don’t fully support 7.4.x just yet.

Secondly, the errors you posted are due to Mod Security. It may be worth researching how to configure the Mod Security. You can find many helpful guides online including Mod Security's documentation on Anomaly Scoring here:
- https://www.modsecurity.org/CRS/Documentation/anomaly.html

Cheers.

**Comment by StewAlexander-com** [comment]
What's with the html folder missing? @JediKev seems an issue

Thanks for the docs....

**Comment by StewAlexander-com** [comment]
If we started from a fresh kvm, instead of trying to upgrade Ubuntu 14.04, what would we need to move from the old 1.10.1 release to the new kvm?

**Comment by JediKev** [comment]
@StewAlexanderACC 

> What's with the html folder missing? @JediKev seems an issue

osTicket does not have an HTML directory and never has. Apache, your web server, comes with a default HTML directory. You can either use the default HTML directory or use a directory from pretty much anywhere by configuring Apache to look/serve from there. Just because you created /var/www doesn’t mean the html/ directory will magically appear. You have to either copy the original HTML directory (which you did) or create a new one. Besides this, the HTML directory really doesn’t matter, it’s how you configure Apache and what directory you point it to.

osTicket comes with a setup/ folder and an upload/ folder. The upload/ folder contains all of osTicket's code that you typically put in your existing HTML directory.

> If we started from a fresh kvm, instead of trying to upgrade Ubuntu 14.04, what would we need to move from the old 1.10.1 release to the new kvm?

Well if you’re upgrading all you need is your database and the include/ost-config.php file. Then you upload the latest version's code into the HTML directory, import your database, copy the config file to the new include/ folder and ensure the database info is still correct. Then you can sign in and upgrade.

Cheers.

**Comment by StewAlexander-com** [comment]
Closing
