### ISSUE TITLE
Cross Site Script Vulnerability on "profile" feature in osTicket version 1.14.2

### ISSUE THREAD

**Issue by r0ck3t1973** [osTicket/osTicket#5515]
### Description
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "profile" feature.

### Steps to Reproduce

1. Login into the panel osTicket
2. Go to 'scp/profile.php'
3. Click 'Signature'
4. Insert Payload XSS:
     `$unicode {41<img src=1 onerror=alert(1337)>}$`
 
![payload](https://user-images.githubusercontent.com/62001260/82549523-40e71e00-9b87-11ea-98e4-86726a9ce9fa.PNG)

5. xss message alert

### Expected behavior
The removal of script tags is not sufficient to prevent an XSS attack.
### Screenshots
![alert_mess](https://user-images.githubusercontent.com/62001260/82549419-1b5a1480-9b87-11ea-9c84-59f4d6824816.PNG)

### Versions osTicket
 v.1.14.2
### Desktop (please complete the following information):
OS: Windows
Browser: Firefox 76.0.1
###
I Hope you fix it ASAP

**Comment by JediKev** [comment]
@r0ck3t1973 

Please refrain from reporting vulnerabilities like this in the future. Please, next time follow Responsible Disclosure practices by reporting directly to us. You can send all POCs to `security[at]osticket[dot]com`. This will give us time to mitigate the vulnerability before it is made public. Luckily this is Low severity as you have to be authenticated as an Agent first.

It looks like this is an issue with the 3rd party text editor we use called Redactor as the payload executes immediately when pasting into the editor. You will need to report this to the developers of the text editor [Imperavi](https://imperavi.com/redactor/).

I can confirm that we sanitize the content correctly in the backend as you can paste the payload into the editor, click Save Changes and nothing happens, this is because we strip the content like we should. So the only issue here is when pasting into the editor.

Cheers.

**Comment by r0ck3t1973** [comment]
@JediKev  yepp, tks!

**Comment by r0ck3t1973** [comment]
Hi, @JediKev 
Any Updates ...?

**Comment by JediKev** [comment]
@r0ck3t1973 

Did you report this to the developers of the text editor (Imperavi)? As mentioned above, this is not an issue with osTicket, rather Redactor, the 3rd party text editor.

Cheers.
