### ISSUE TITLE
Language pack has different size when selecting plugin

### ISSUE THREAD

**Issue by Af0x** [osTicket/osTicket#5571]
Hello,

when I visit the [official download page](https://osticket.com/download/), select 1.14.2, select a language (e.g. German), select a plugin (e.g. Storage :: Attachments on the Filesystem) and download. The provided file contains a language pack with double the size compared to not selecting a plugin. Also the bigger file seems to break the language functionality and the whole system seems to be in English from this point on, even when changing back to the smaller file.

Regards,

Af0x

**Comment by JediKev** [comment]
@Af0x 

There was an issue not too long ago which caused some of the language packs to be broken. We have since addressed the issue however there are some download combos that still contain the broken language pack(s). The best thing is to make a report letting us know which combo doesn’t work (like this) and we will remove the broken combo so it can be repackaged.

So the specific combo that’s currently broken for you is v1.14.2 + German + Storage FS?

Cheers.

**Comment by Af0x** [comment]
Hello, that is correct. 1.14.2 + German + Storage FS seems to be broken. Regards

**Comment by JediKev** [comment]
@Af0x 

Okay, we have removed the broken combo so it should work correctly now. Please retest the download (**v1.14.2 + German + Storage FS**) and let me know the results.

Cheers.

**Comment by Af0x** [comment]
Looks good to me, thanks!
