### ISSUE TITLE
Fetching is stuck yet fills IMAP-folder

### ISSUE THREAD

**Issue by mchobbel** [osTicket/osTicket#5645]
Our environment:
   - osTicket v1.14.3
   - Dovecot IMAP-server v2.2.36
   - MySQL  10.5.5
   - PHP  7.4.6

Our config:
  - We have configured IMAP fetching with a 1 minute frequency,
  - Fetched emails are moved to the IMAP-folder "ost_done".

Recently our fetching was stuck for a period (1 week). At the end, after I found out this was the case, I could solve it by manually
emptying the IMAP inbox, but in the meantime we had the following scenario:

   - osTicket fails to fetch any emails from the inbox.
   - all new incoming emails are stuck in the inbox.
   - at every fetch-attempt by osTicket every email found in the inbox is copied to "ost_done"
   - These copied email-messages are piling up, without deduplication, so e.g. if you have 10   messages in the inbox, each minute you have 10 more copies in ost_done.  600 per hour, 14.4 K per day, etc. (it grows exponentially as new email keeps coming in).
   - finally this fill up the disks  and other things start to break

At least 3 things go wrong:
 1) something causes the fetcher to fail of crash 
 2) copies of emails are created in "ost_done", which should never happen, i think, emails should be MOVED to "ost_done" and only after completing the fetch.
 3) No error alert is sent. No Error is found in the ost_sys_log.

I haven't been able to reproduce this of found out what caused it.

**Comment by JediKev** [comment]
@mchobbel 

That's very strange behavior. We use PHP's `imap_mail_move()` function to move the mail so I have no idea why it's Copying instead of Moving the mail. Typically if you wanted to copy mail you'd use `imap_mail_copy()` but we use `imap_mail_move()` which should move the mail entirely.
- https://github.com/osTicket/osTicket/blob/develop/include/class.mailfetch.php#L952

If you have email that's stuck that means osTicket can't process it for one reason or another. Typically you'd want to find the mail in question, get the FULL raw mail (including headers), redact any sensitive info, and post it here for us to review and attempt to replicate with.

Typically it should leave a syslog like:
- https://github.com/osTicket/osTicket/blob/develop/include/class.mailfetch.php#L967-L968

If it doesn't then that means the check for `$this->createTicket($i)` passed and will not leave a syslog entry.

Cheers.

**Comment by mchobbel** [comment]
Thanks for your response, clearly it is not osTicket in this case which failed. Somehow it is the IMAP backend which is not behaving correctly upon the  imap_mail_move commands. I known around the time it happend there were some malfunctions in the network connection between the osTicket VPS and the mail-server's VPS. My guess is it must have have been the connection dropping right in the middle of  processing  the imap_mail_move command, so it could not finish the operation.
