### ISSUE TITLE
upgrade to v 1.15.2

### ISSUE THREAD

**Issue by Ressy66** [osTicket/osTicket#5836]
is it correct that this still shows in dashboard/information?

osTicket Version	1.15-git (?)  Upgrade — fe1d1f8 is available

upgrade by extracting files over, login and the only message says delete the /setup/ directory.

Incidentally clicking on the upgrade button next to "is available" sends me to website, where I d/l'd, scp'd and extracted, helpdesk is working, (I change the captcha to use 7 digits, so on upgrade it now shows 5 - correctly so the upgrade must has succeeded, is there something just not updating the version number?

**Comment by JediKev** [comment]
@Ressy66 

It appears you’re attempting to upgrade using the files from git. If so it’ll always show the branch as the version (ie. 1.15-git). You should really be using the files from [our website’s download page](https://osticket.com/download). Once you upgrade using those files it’ll show the correct version number.

Cheers.

**Comment by Ressy66** [comment]
Hi,
I once before did get a git update from the automatic update, however this time, I d/l's from the website osticket.com/download 
v1.15.2, I did it twice incase the first one screwed up, I am downloading the tar.gz version

**Comment by Ressy66** [comment]
Just an update, I checked the tar.gz source package directly from the website download page, and yes bootstrap still refers -git
      
#Current version && schema signature (Changes from version to version)
define('GIT_VERSION','$git');
define('MAJOR_VERSION', '1.15');
define('THIS_VERSION', MAJOR_VERSION.'-git'); //Shown on admin panel

So looks like some of teh release script is not updating some files for  tar.gz

**Comment by ntozier** [comment]
Go to http://osticket.com/download
download the product.
unzip it.
over write your files.

If you have a tar.gz it is not from the the address mentioned above.

**Comment by Ressy66** [comment]
OK, therein lies the confusion...    I've always clicked on the release tag, this takes me to 

https://github.com/osTicket/osTicket/releases/tag/v1.15.2   where the zip and tar.gz is
so the github "releases" are not treh same as the website "releases" despite having trhe same version number in its tag, as exampled by the above url, its even called   osTicket-1.15.2.tar.gz 

I see going back to website, ignoring the release tag, and clicking on the next next next stuff does give me a zip file to d/l that refers to minor .2

This is how I've always done it since I came to osticket around 1.10

So the question for devs is why are they called the same release filename but are infact different :)
Now you see the confusion.

**Comment by JediKev** [comment]
@Ressy66 

So, you must be downloading the Source code (.zip)/Source code (.tar.gz) files from the releases page instead of the `osTicket-v1.15.2.zip` from the releases page. You see, the Source code (.zip)/Source code (.tar.gz) files are auto-generated by Github and is not a release packaged by the core osTicket dev team. When you use the auto-generated zip files from Github it doesn't have the appropriate tag number in the `bootstrap.php` file as it wasn't packaged using our package command. The `osTicket-v1.15.2.zip` file from the releases page on the other hand is a packaged release using our package command so it has the appropriate tag number and should reflect as such in the `Dashboard > Information` page. The same applies to the packages downloaded from our website.

So the difference is with the release files packaged by us vs. the auto-generated files by Github. If you want the appropriate tag number to show in the Information page you have to download a packaged release.

Cheers.
