### ISSUE TITLE
How to closed ticket by email response from agent

### ISSUE THREAD

**Issue by dangngovan** [osTicket/osTicket#5920]
Dear all
i have a question, when an agent wants close ticket by email sent to the user. how to do it via email (e.g. using hashtag #closed in email body )

Thank so much 

### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@dangngovan 

Thank you for opening an issue. GitHub is a place to report Issues, Bugs, Feature Requests and Pull Requests. If you would like to ask questions, please use [the Forum](https://forum.osticket.com) instead.

With that being said I’ll go ahead and answer you here for ease. There is no way to close tickets by Agents Replying via email. When Agents reply via email their reply is only added as an internal note (not visible by end users). You will need to modify the code in order to accomplish what you are looking for.

I will go ahead and close this as this is a question best suited for the Forum.

Cheers.

**Comment by kapcom01** [comment]
@JediKev Is it ok to open a new feature request for this issue?
