### ISSUE TITLE
How to add additional information at the bottom of the page 

### ISSUE THREAD

**Issue by djkcyl** [osTicket/osTicket#5944]
![image](https://user-images.githubusercontent.com/59153990/128347298-b03ba84d-9b94-4478-abad-c8d7df3e8be6.png)
like this

**Comment by JediKev** [comment]
@djkcyl 

This is more of a question on how to mod osTicket rather than reporting an Issue. Questions like this are best suited for our [Forum](https://forum.osticket.com). GitHub is a place to report Issues (with the code), to make Feature Requests, and to make Pull Requests.

With this being said I’ll quickly reply here for convenience. You must modify the core files to achieve this (specifically the footer files).

Cheers.
