### ISSUE TITLE
Enabling the "auth-password-policy" plugin on v1.17-rc3 causes failure to login.

### ISSUE THREAD

**Issue by CrazyLinuxNerd** [osTicket/osTicket#6224]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

I was preparing our osTicket installation (and server OS) ready for migration to v1.17-rc3 after completing the upgrade process and attempting with clean files / db I was able to reproduce a login failure consistently when the plugin was enabled/installed.

Upon initial upgrade (before upgrader is ran) login is still successful, however subsequent logins will fail.

### Related PHP Error
`[16-Aug-2022 22:29:58 UTC] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string * int in phar:///var/www/html/include/plugins/auth-password-policy.phar/auth.php:106
Stack trace:
#0 /var/www/html/include/class.auth.php(506): PasswordManagementPolicy->onLogin()
#1 /var/www/html/include/class.auth.php(1212): AuthenticationBackend->checkPolicies()
#2 /var/www/html/include/class.auth.php(341): osTicketStaffAuthentication->authenticate()
#3 /var/www/html/scp/login.php(71): AuthenticationBackend::process()
#4 {main}
  thrown in phar:///var/www/html/include/plugins/auth-password-policy.phar/auth.php on line 106`

### Steps to Reproduce

1. Install or upgrade to osTicket v1.17-rc3 (I also used git)
2. Add the plugin, downloaded from the osTicket website "auth-password-policy.phar"
3. Complete setup and/or upgrade
4. Logout, and try to log back in. It will fail and get stuck at "Verifying login" with a spinner.
5. Remove the plugin (or rename to .old like I did)
6. Successful login when plugin is disabled or removed

**Expected behavior:** Successful Login

**Actual behavior:** Login gets stuck at "Verifying Login" spinner

### Versions

osTicket Version: v1.17-rc3 (34c64f1)
Web Server Software: Apache/2.4.51 (Red Hat Enterprise Linux) OpenSSL/3.0.1
MySQL Version: 10.5.16
PHP Version: 8.0.13
Web Browser: Firefox 103.0.2 (64-bit) on OpenSUSE Tumbleweed

**Comment by protich** [comment]
@CrazyLinuxNerd - Thanks once again for the report - I've made a PR in https://github.com/osTicket/osTicket-plugins/pull/232 to address the issue. You can rebuild the plugin and give it a test.

**Comment by CrazyLinuxNerd** [comment]
Don't thank me, thank you for developing and maintaining osTicket :-)

Applied the PR request to the plugin and can confirm login now works again with the plugin enabled :-)

**Comment by protich** [comment]
@CrazyLinuxNerd - Although the issue is fixed at the plugin level based on your report - it will also be nice to fix the issue upstream because there's no way to force plugin upgrade. But we're struggling to replicate the issue on our end and I'm wondering if we can somehow connect for a debug session.  

Meanwhile, can you please post value saved for `expires`  - it should be in ost_config with key of `expires` and plugin instance as the namespace. 

Thanks,

**Comment by CrazyLinuxNerd** [comment]
@protich Hi,

The current expires value is as follows:

Command used:
`SELECT *  FROM `ost_config` WHERE `key` LIKE 'expires'`

| id  | namespace | key | value | updated |
| --- | --- | --- | --- | --- |
| 163 | plugin.2.instance.3 | expires | `{"":"Never expires"}` | 2022-08-16 17:56:11 | 

(I don't think we ever actually set/changed this value)

As for debugging, our system is now running with the patches in place as such it's no longer broken so there's not much to debug there. But with that said I can easily pull a historic backup from our backup archive with a pre-upgrade database to allow you to perform the upgrade yourself and do any necessary testing/debugging and/or a current post-upgrade database.

Unfortunately I deleted the pre-upgrade system a couple of days ago (it wasn't necessary any more) so I'll have to spin up a fresh system based on the backup for you with RHEL9 to test it on and grant your SSH key access to an account if you're comfortable with that. The advantage of this method though is that it won't interrupt live services at all.

Although, please be aware our systems are pretty much CLI exclusive outside of osTicket.

If you'd like to go ahead with this method let me know and I'll email you with further information and access :-)

Note: live ticket data & user accounts will be deleted prior to access being granted... nothing personal! Just keeping to our compliance requirements.

**Comment by protich** [comment]
@CrazyLinuxNerd - Thank you for the response, I don't need access anymore! I was able to replicate the issue (PHP needed to be in strict mode). I was adamant about the issue being fixed at osTicket level because  I had put in too much effort to make sure multi-instance support was backward compatible and I didn't really want to cause access issues post upgrade - since we don't package osTicket with updated plugins and didn't want to auto disable the Plugin with a fat warning to upgrade.

That said, I'm happy to report that the issue was indeed fixable upstream and  plugin upgrade is nolonger necessary. Here is [a commit](https://github.com/osTicket/osTicket/pull/6230/commits/a706866844b2c61cf5ab0219b65715df3bf8e549) that addreses the bug that caused the crash downstream.

Cheers,
