### ISSUE TITLE
MS 365 shared mailbox is not working

### ISSUE THREAD

**Issue by dvillareal22** [osTicket/osTicket#6326]
Hello,

We are trying to setup our emails on osticket 1.17 and we are using shared mailbox on microsoft 365. 
During out setup, we encounter an error that the email was mismatched.

Is there anything we need to know or to do in order to make shared mailbox work?

**Comment by JediKev** [comment]
@dvillareal22 

For the time being you must login as the email you are authorizing for. So you must login as the shared mailbox in order to authorize it. Some community members have mentioned they setup a temporary password for the shared mailbox so they can login and authorize. Once you get a token you won’t have to do that for another 2 years and by that we should have functionality to make it much easier for shared mailboxes.

Cheers.

**Comment by dvillareal22** [comment]
thanks you for your reply. I will try to setup a temporary password for the shared mailbox.
