### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by salehhajiyev** [osTicket/osTicket#6488]
PHP Parse error:  syntax error, unexpected '=' in /var/www/src/public/include/class.forms.php on line 4043

Parse error: syntax error, unexpected '=' in /var/www/src/public/include/class.forms.php on line 4043

**Comment by JediKev** [comment]
@salehhajiyev 

Please post a screenshot of **Admin Panel > Dashboard > Information**. It’s likely you are not running the appropriate PHP version.

Cheers.

**Comment by PandyDev** [comment]
Hello @JediKev,
I experience the same issue while installing. I am using the guide from dockerhub: https://hub.docker.com/r/osticket/osticket
![image](https://user-images.githubusercontent.com/29369237/224842699-57bf7ae0-874c-4ba1-8bfe-f0e37c8b884b.png)

**Comment by JediKev** [comment]
@PandyDev Please read my comment above. Since you can’t install just post what PHP version you are using.

**Comment by PandyDev** [comment]
Basically I am using the Dockerimage linked to the dockerhub. I digged a bit deeper into the build. Seem like its using the base image "php:7.3"

**Comment by JediKev** [comment]
@PandyDev 

That’s your issue. Please read the requirements before installing. osTicket requires PHP 8.0-8.1. Upgrade PHP and you will be fine.

Also it’s worth mentioning that the Docker image you are referring to is not an official image; someone stole the name. We are in the process of recovering our namespace. If you continue to have issues with that docker image then you will need to contact the maker of the image for further assistance. Otherwise I suggest you build your own server and follow the installation docs here:
- https://docs.osticket.com/en/latest/Getting%20Started/Installation.html

Cheers.
