### ISSUE TITLE
Blank white box on new install

### ISSUE THREAD

**Issue by linked-kiwi** [osTicket/osTicket#6596]
I have installed OSTicket before with Apache, and am now trying to get it working with Nginx.  I have installed the latest OSTicket on a clean Ubuntu 22.04, with install php which brings in php8.1.2.   This installs fine, and I can log into osticket/scp but when I add a user it throws up a blank white box.

I have done the same install on Kali Purple, with Nginx, and with the install php which brings in php8.2.  The result is exactly the same - white box.

If I swap out Nginx and pull in Apache2, everything works correctly. Is there a way to get OsTicket working with Nginx?

**Comment by JediKev** [comment]
@linked-kiwi 

Please review/read the prerequisites listed in this repo, the Forum, and our website. They all say "Apache or IIS" with no mention of NGINX. This is because NGINX is not fully supported out of the box. With NGINX you must add rules to the config which we do not have public at this time.

You can search this repo and the Forum for the appropriate rules to use to support NGINX.

Cheers.
