### ISSUE TITLE
[Feature Request] Set end user's department in profile

### ISSUE THREAD

**Issue by randyburrowunt** [osTicket/osTicket#6608]
It would be nice if the end user's had a department attribute on their profile that either they could set, or the support staff could change/update.  This way even if the end user emails a support request, their department is set by the system.

**Comment by protich** [comment]
Users are blind to internal structure by design and I don't see us changing it.  Simply add said user as an Agent and restrict access accordingly. If they must be a User then extend access via organization membership and use filters to set the organization for tickets you want them to have access to.

**Comment by protich** [comment]
Actually a better option is to add a custom  internal `Dynamic Field` of type `Department` to the User (Contact) Form - then use it via filters to route tickets as you wish regardless of the source (email or web)... that should meet your needs.
