### ISSUE TITLE
Showing Email Address 

### ISSUE THREAD

**Issue by NCaur** [osTicket/osTicket#6615]
I want to show the email address when the email is forwarded to another user:

![Screenshot 2023-10-05 112835](https://github.com/osTicket/osTicket/assets/66243012/296f237e-695a-472a-9ed6-f1d774c75379)
In from, you can see the name from whom the email address has been received, however i wanted to see the email address as well.
How can i do that?
in database ost_thread_entry table is storing it in body column without email address, i want to store it and show it for from, to and cc fields.

**Comment by JediKev** [comment]
@NCaur 

This is a limitation of our HTML Parser/Balancer/Sanitizer. Any `<>` characters are seen as HTML tag opening/closing characters by the parser/balancer/sanitizer. So in this case the email would look like `<user@domain.tld>` which would be seen as an invalid/unbalanced HTML tag.  When the system goes to balance the incoming HTML content and since it sees the email as invalid/unbalanced HTML tag it strips the email out completely. There is no way you can display the email in the Thread Entry unless the email in the incoming content doesn't include `<>` characters around it. Disabling the parser/balancer/sanitizer is **_NOT_** recommended in the slightest as you'll open yourself up to security vulnerabilities.

With this being said we aim to have a more modern and less-limited HTML parser/balancer/sanitizer in v2.0 so please stay tuned!

Cheers.
