### ISSUE TITLE
Silent fail with too large attachments over local postfix

### ISSUE THREAD

**Issue by bmorg** [osTicket/osTicket#6617]
When the local postfix has an attachment limit configured (and no SMTP is used), sending a message with a larger file attached fails, but the UI reports "Ticket #123: Reply posted successfully".

### Steps to Reproduce

1. Vanilla install of the `develop` branch
2. Email settings: "Default MTA: None: Use PHP mail function"
3. System settings: "Agent Maximum File Size: 2 mb"
4. Install postfix: `apt-get install postfix`
5. Set an attachment limit lower than 2 MB in postfix (`/etc/postfix/main.cf`): `message_size_limit = 240000`
6. Attach a file of e.g. 1 MB to a message

**Expected behavior:**

An error message should be displayed.

**Actual behavior:**

* Message: > Ticket #123: Reply posted successfully
* An error is logged to the "system log".

System log:

```
Oct 11 10:46:00 osticket-dev-bookworm postfix/postdrop[14905]: warning: uid=33: File too large
Oct 11 10:46:00 osticket-dev-bookworm postfix/sendmail[14904]: warning: mail_stream_cleanup: close error
Oct 11 10:46:00 osticket-dev-bookworm postfix/sendmail[14904]: fatal: ******@*******.com(33): message file too big
```

**Analysis:**

The error is logged in `class.mailer.php` [here](https://github.com/osTicket/osTicket/blob/develop/include/class.mailer.php#L634).

### Versions

* osTicket Version: v1.18-10-gfcdeb542 (fcdeb54)
* Web Server Software: Apache/2.4.57 (Debian)
* MySQL Version: 10.11.4
* PHP Version: 8.2.7
* Debian: Bookworm `12.2`

**Comment by JediKev** [comment]
@bmorg 

This is by design. Even if the outgoing email fails it still posts the reply successfully (which is why the message says "**Reply** posted successfully."). You should see an error in your system logs though (shown in one of the links you posted above).

In v2.0 (or after) we can look at a better way to go about this. We'd have to discuss this internally to figure out the best way though. Please stay tuned!

Cheers.
