### ISSUE TITLE
Email alerts not sent in certain situation

### ISSUE THREAD

**Issue by Tandokude** [osTicket/osTicket#6656]
### Prerequisites

* [ Yes] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ No] Do you have any errors in the PHP error log, or javascript console?
* [ Yes] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

We have a particular situation where someone sends a follow-up email, using the original one they sent to Osticket. It will create the comment, as we expect, however, it does not fire an email alert to the ticket owner or the collaborator so they are unaware of the comment unless they sign in.  It does not appear to matter if the agent assigned comments before the additional comment. 

### Steps to Reproduce

1. User sends email to osticket, new ticket is created
2. Ticket gets assigned
3. User sends another email by responding to their original sent message to osticket.
4. We can see the comment in the ticket, but no notification

**Expected behavior:**If a comment/activity occurs there should be an alert

**Actual behavior:** No alert

### Versions 1.17.5 and 1.15.4

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Debian 11 and Chromium/Firefox/Edge

**Comment by JediKev** [comment]
@Tandokude 

You can debug around here:
- https://github.com/osTicket/osTicket/blob/4689926b2d3d25754f0ddcf8d4e181a2817f6d56/include/class.ticket.php#L3185-L3193

… and here:
- https://github.com/osTicket/osTicket/blob/4689926b2d3d25754f0ddcf8d4e181a2817f6d56/include/class.ticket.php#L1916-L1929

We disable `$autoresponder` in a few different scenarios on a New User Message. Once you figure out where the autoresponder is being disabled you can better track why this is occurring.

Cheers.

**Comment by Tandokude** [comment]
So based on that information, it is the one at line 3185 being hit, and if I capture each variable here is what I see:

[26-Jan-2024 21:17:33 UTC] autorespond - 1 (immediately after line 3188)
[26-Jan-2024 21:17:33 UTC] second -  (after line 3193)
[26-Jan-2024 21:17:33 UTC] mailflags 
[26-Jan-2024 21:17:33 UTC] bounce 
[26-Jan-2024 21:17:33 UTC] auto-reply 
[26-Jan-2024 21:17:33 UTC] reopen 1
[26-Jan-2024 21:17:33 UTC] autorespond 
[26-Jan-2024 21:17:33 UTC] bouncetest 

Is the test isBounceOrAutoReply returning something setting autorespond to nothing? If I force autorespond to be true after line 3193, I get a notification.

**Comment by JediKev** [comment]
@Tandokude 

I would recommend logging both `$message->isBounceOrAutoReply()` and `$vars['autorespond']` after line `3193`.

Cheers.

**Comment by Tandokude** [comment]
@JediKev So here are the results:

$message->isBounceOrAutoReply() returns false
$vars['autorespond'] is blank or false

It appears it is the second else if that checks if $vars['autorespond'] isset and since it is false autorespond is also set to false. Do we know where that $vars is set?

**Comment by JediKev** [comment]
@Tandokude 

It's probably this one:
- https://github.com/osTicket/osTicket/blob/4689926b2d3d25754f0ddcf8d4e181a2817f6d56/include/class.thread.php#L476

Which is determined by:
- https://github.com/osTicket/osTicket/blob/4689926b2d3d25754f0ddcf8d4e181a2817f6d56/include/class.thread.php#L1490-L1500

If this is the case in your instance, it seems like the system is passive threading which silently listens to the conversation instead of broadcasting alerts.

Cheers.

**Comment by Tandokude** [comment]
@JediKev Is there a setting/variable to disable passive threading?

**Comment by JediKev** [comment]
@Tandokude 

No, this is determined by the mail headers. Essentially the Message-ID, References, and In-Reply-To headers were not generated by the helpdesk so it’s unable to decode it and gather information from it. However one or more of those header values do match at least one previous entry in the thread so [it skips this part](https://github.com/osTicket/osTicket/blob/4689926b2d3d25754f0ddcf8d4e181a2817f6d56/include/class.thread.php#L1458-L1460) and [moves on to passive threading](https://github.com/osTicket/osTicket/blob/4689926b2d3d25754f0ddcf8d4e181a2817f6d56/include/class.thread.php#L1490-L1500).

So really, they should reply to the New Ticket Alert (or any other alerts or Agent Replies) instead of their original message. That way the In-Reply-To and References headers will contain the message-id generated by the system and will not be passively threaded.

Cheers.

**Comment by Tandokude** [comment]
@JediKev Agreed it would be nice if users could follow directions, but we just want to avoid the issue if activity is generated in the ticket it would send an alert regardless. That way agents don't have to sit at the dashboard to make sure this doesn't occur.

**Comment by JediKev** [comment]
@Tandokude 

Then you can simply modify the codebase to force `$mailinfo['passive']` to `false` in that statement above.

Cheers.

**Comment by Tandokude** [comment]
Will be doing that, Thanks
