### ISSUE TITLE
Export custom list/variables via CSV 

### ISSUE THREAD

**Issue by philaneous** [osTicket/osTicket#694]
Hi,

I'm running version 1.8.1. My custom lists that I created don't export when I download a csv. Went to class.export.php and noticed that the array obviously only lists the defaults variables. Do I need to edit the select query and add them to the array? I would assume that the cdata function should automatically pick up the SQL variables. Makes no sense that I can make custom lists and not be able to export them.

Any suggestions?

**Comment by saithamsco** [comment]
:+1: 

I would like to open this discussion again. I have just posted this into the osticket forum 
[Link](http://www.osticket.com/forum/discussion/87341/custom-list-elements-in-export-file-build-in-forms-vs-custom-forms)

I understand that its easier to export 'default' values (those in build-in forms) compared to those in custom forms (because they are dependent on the chosen help topic). 

But I would also like to explain our business case and why this would be an important enhancement for us.

We are a SME working B2C (with quite computer un-savy customers) and support requests still either come by phone or by email. We would not be able to make great use of the portal. 
But for us capturing all kinds of information about issues (product, batch no, serial number, fault code etc.) is very important and used for production analysis. At the moment the support team just manually enters those data into an excel file so changing this routine and manually opening a new ticket in OSTicket and manually adding fault codes etc would be OK. But for analysis we would need to be able to export those custom fields to excel to run our analysis. As I said in the forum thread the workaround is OK but it would be more user friendly to have custom fields be called depending on the help topic (=product) chosen. 

Thought this might be interesting / the way we use OSTicket in B2C! Being able to capture and export custom fields would really make our lives easier. Happy to answer any questions.
